<div class="album tab_content" data-id="4" style="margin-top:0.25rem">
    <div class="container " style="width:100%">


        <div class="show_list" id="show_wrap" style="padding-top:0;">

            <div class="item" >

            </div>

        </div>
        <div id="no-video" style="height:15rem;width:100%;text-align:center;margin-top:1rem;background:#F9F9F9;display: none;">
                <img src="/static/wap/images/person/no-video.png" style="width:5rem;height:5rem;">
                    <br>
                <span style="font-size:0.75rem;color:#999">暂无视频</span>
        </div>
    </div>
</div>

<div id="v-loading" style="display:none;width:95px;height:55px;line-height: 68px;background:rgba(0,0,0,0.2);position: fixed;z-index: 106;top:0;left:0;right:0;bottom: 0;margin:auto;border-radius:0.25rem ;text-align:center">
    <div class="loading">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<style>
    .loading{
        width: 75px;
        height: 15px;
        margin: 0 auto;
        text-align: center;
    }
    .loading span{
        display: inline-block;
        width: 7px;
        height: 100%;
        margin-right: 5px;
        background: #50EA82;
        -webkit-animation: load 1.04s ease infinite;
    }
    .loading span:last-child{
        margin-right: 0px;
    }
    @-webkit-keyframes load{
        0%{
            opacity: 1;
            -webkit-transform: scale(1.2);
        }
        100%{
            opacity: .2;
            -webkit-transform: scale(.2);
        }
    }
    .loading span:nth-child(1){
        -webkit-animation-delay:0.13s;
    }
    .loading span:nth-child(2){
        -webkit-animation-delay:0.26s;
    }
    .loading span:nth-child(3){
        -webkit-animation-delay:0.39s;
    }
    .loading span:nth-child(4){
        -webkit-animation-delay:0.52s;
    }
    .loading span:nth-child(5){
        -webkit-animation-delay:0.65s;
    }
</style>
<video   id="v-player" style="display:none"   ></video>
<style>
    #show_wrap .item{
        width:49%;
        height:11rem;
        border-radius:0.2rem;
        border:1px solid #eee;
        margin:0.1rem auto;
        display: inline-block;
    }
    #show_wrap{
        width:96%;
        margin: 0 auto;
    }
</style>
<script>
    $('#show_wrap').on('click','.item',function () {
        $('#v-loading').show();
        $('#v-player').attr('src',$(this).data('url'));
        var video = document.getElementById('v-player');
        video.play();
        video.oncanplay = function () {
            $('#v-loading').hide();
        }

    });
</script>
