<style>
    .form-group {
        min-height: 30px;
        overflow: hidden;
    }

    .form-group .control-label {
        text-align: right;
    }

    .form-group select {
        margin: 0;
    }
</style>
<main class="tab-content" style="border:none">
    <section id="home" class="tab-pane in active">
        <div class="form-group">
            <label for="name" class="col-sm-1 control-label">标题</label>

            <div class="col-sm-10">
                    <span class="col-sm-5">
                        <input type="text" style="height: 40px;line-height: 40px" class="form-control" id="title"
                               name="title" placeholder="网页标题"
                               value="<?php echo $content['remark']  ?>" required
                               data-error="">
                    </span>
                <span class="help-block with-errors"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-1 control-label">内容</label>

            <div class="col-sm-10">
                <div class="col-sm-8">
    <textarea class="message_box" id="txtContent"
              style="min-height: 500px;width: 100%;"><?php echo $content['val'] ?></textarea>
                    <span class="btn btn-primary btnSave" style="margin-top: 10px"><i
                            class="fa fa-send"></i> 立即保存</span>
                </div>
                <span class="help-block with-errors"></span>
            </div>
        </div>
    </section>
</main>
<script>
    seajs.use(['app/panel/panel.base', 'app/app.editor'], function (api, editor) {
        editor.init('#txtContent');
        $(".btnSave").on('click', function () {
            var content = $.trim($("#txtContent").val());
            var title = $.trim($("#title").val());
            if (title == '') {
                tip.showTip('err', '标题不能为空', 1000);
            }
            if (content == '') {
                tip.showTip('err', '内容不能为空', 1000);
            }
            api.requestApi("/api/agreement/save", {key: 'user', 'content': content,'title':title}, function (res) {
                if (res.result == 1) {
                    tip.showTip("ok", '保存成功', 1000)
                }
            })
        })
    })
</script>