<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>恐龙谷社交软件-娱乐自媒体社交平台_美女交友聊天APP_知识问答软件</title>
    <meta name="keywords" content="恐龙谷，美女交友APP，娱乐自媒体平台，知识问答软件，社交聊天软件" />
    <meta name="description" content="恐龙谷社交软件全新版本开启附近圈子社交新时代，红包广场全面开启，精彩就在附近，还能免费开店，视频红包依旧惊喜不断，更有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！年轻人都喜欢的娱乐自媒体社交平台！" />
    <link rel="shortcut icon" href="/static/home/images/favicon.ico"/>
    <link rel="stylesheet" href="/static/home/css/swiper.css">
    <link rel="stylesheet" href="/static/home/css/animate.css">
    <link rel="stylesheet" href="/static/home/css/base.css">
    <link rel="stylesheet" href="/static/home/css/media.css">
    <script>
        var browser = {
            versions: function () {
                var u = navigator.userAgent;
                return {//移动终端浏览器版本信息
                    trident: u.indexOf('Trident') > -1, //IE内核
                    presto: u.indexOf('Presto') > -1, //opera内核
                    webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                    gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                    mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
                    ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                    android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                    iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
                    iPad: u.indexOf('iPad') > -1, //是否iPad
                    webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
                };
            }()
        }
        if (browser.versions.mobile) {
            window.location.href = "http://wap.klgwl.com/Downloads/share"
        }

    </script>
</head>
<body>
<!-- 头部导航 -->
<div class="nav changeBj">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="恐龙谷社交软件">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li>
                    <a href="index" class="active">
                        首页
                    </a>
                    <span class="active navin"></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于恐龙谷</a>
                    <span class="active"></span>
                    <b></b>
                </li>

                <li>
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="swiper-container swiper-container-vertical">
    <div class="swiper-wrapper">
        <div class="swiper-slide swiper-slide-active swiper-slide-one">
            <!-- 内容块 -->
            <div class="container mt64">
                <div class="pro-info pa">
                    <h2 class="title fadeInUp wf">共享闲余时间 结交高颜值朋友</h2>
                    <span class="line"></span>
                    <p class="show-f">来恐龙谷 , 让你的圈子越来越有趣</p>

                    <div class="homepage_download">
                        <ul class="clearfix">
                            <li class="">
                                <em></em>
                                <span>iPhone客户端</span>
                            </li>
                            <li class="">
                                <em></em>
                                <span>Android客户端</span>
                            </li>
                            <li class="fr">
                                <img src="/static/home/images/v2/qr.png" alt="美女交友APP">
                                <span style="text-align: center">扫描下载客户端</span>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
        <div class="swiper-slide swiper-slide-next swiper-slide-two">
            <div class="container clearfix mt64">
                <div class="show-left fl pr leftSlideIn">
                    <h2>刷动态 领红包</h2>
                    <span class="line"></span>
                    <p>海量动态红包抢不停，一键轻松提现</p>
                </div>

            </div>
            <div class="download">
                <ul class="clearfix">
                    <li class="fl">
                        <em></em>
                        <span>iPhone客户端</span>
                    </li>
                    <li class="fl">
                        <em></em>
                        <span>Android客户端</span>
                    </li>
                    <li class="fr">
                        <em></em>
                        <span>扫描下载客户端</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="swiper-slide swiper-slide-there">
            <!-- 内容块 -->
            <div class="container clearfix mt64">
                <div class="show-left fl pr leftSlideIn">
                    <h2>精彩内容打赏不断</h2>
                    <span class="line"></span>
                    <p>发布更有趣的内容 ， 让喜欢你的</p>
                    <p>粉丝给你来点实实在在的爱吧</p>
                </div>
            </div>
            <!--download -->
            <div class="download">
                <ul class="clearfix">
                    <li class="fl">
                        <em></em>
                        <span>iPhone客户端</span>
                    </li>
                    <li class="fl">
                        <em></em>
                        <span>Android客户端</span>
                    </li>
                    <li class="fr">
                        <em></em>
                        <span>扫描下载客户端</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="swiper-slide swiper-slide-four">
            <!-- 内容块 -->
            <div class="container clearfix mt64">
                <div class="show-left fl pr rightSlideIn">
                    <h2>专属秀场</h2>
                    <span class="line"></span>
                    <p>酷炫的视频、 萌动的图片 ， 展现</p>
                    <p>你的魅力</p>
                </div>
            </div>
            <!--download -->
            <div class="download">
                <ul class="clearfix">
                    <li class="fl">
                        <em></em>
                        <span>iPhone客户端</span>
                    </li>
                    <li class="fl">
                        <em></em>
                        <span>Android客户端</span>
                    </li>
                    <li class="fr">
                        <em></em>
                        <span>扫描下载客户端</span>
                    </li>
                </ul>
            </div>
        </div>


        <div class="swiper-slide swiper-slide-next swiper-slide-eight">
            <!-- 内容块 -->
            <div class="container clearfix mt64">
                <div class="show-left fl pr leftSlideIn">
                    <h2>寻觅交友</h2>
                    <span class="line"></span>
                    <p>轻松搭讪 ， 发现心动的那个TA</p>
                </div>

            </div>

            <!-- foot-bj -->
            <div class="foot-bj">
            </div>
            <div class="foot">
                <?php if (strpos($_SERVER['HTTP_HOST'], 'klgwl.com') !== false) { ?>
                    Copyright © 恐龙谷 All Rights Reserved 深圳市恐龙谷网络科技有限公司版权所有
                    <a href="http://www.miitbeian.gov.cn/">粤ICP备15089260号-2</a>
                <?php } else if (strpos($_SERVER['HTTP_HOST'], 'klgwl.cn') !== false) { ?>
                    Copyright © 恐龙谷 All Rights Reserved 深圳市恐龙谷网络科技有限公司版权所有
                    <a href="http://www.miitbeian.gov.cn/">粤ICP备15089260号-6</a>
                <?php } else if (strpos($_SERVER['HTTP_HOST'], '2sf.com') !== false) { ?>
                    Copyright © 恐龙谷 All Rights Reserved 瑞安市恐龙谷网络科技有限公司版权所有
                    <a href="http://www.miitbeian.gov.cn/">浙ICP备17034230号-1</a>
                <?php } ?>
            </div>
            <!--download -->
            <div class="download">
                <ul class="clearfix">
                    <li class="fl">
                        <em></em>
                        <span>iPhone客户端</span>
                    </li>
                    <li class="fl">
                        <em></em>
                        <span>Android客户端</span>
                    </li>
                    <li class="fr">
                        <em></em>
                        <span>扫描下载客户端</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--二维码层-->
    <div class="layer-box" style="display:none">
        <div class="con-block">
            <img src="/static/home/images/1496916678.png" alt="">
            <p>扫描二维码，轻松下载恐龙谷客户端</p>
        </div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets">
        <span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
    </div>
</div>
<div style="display:none">
    <ul>
        <li>
            <a href="http://www.klgwl.cn/">恐龙谷</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">美女交友APP</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">娱乐自媒体平台</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">知识问答软件</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">社交聊天软件</a>
        </li>
    </ul>
</div>
<script src="/static/home/js/jquery-2.1.4.min.js"></script>
<script src="/static/home/js/swiper.min.js"></script>
<script>
    $(function () {

        $(".download ul li,.homepage_download ul li").on("click", function (e) {
            e.stopPropagation();
            var indexli = $(this).index();

            if (indexli == 0) {
                window.location = "https://itunes.apple.com/cn/app/kong-long-gu/id1208329358?mt=8"
            } else if (indexli == 1) {
                window.location = "<?php echo $download_url?>"
            } else if (indexli == 2) {
                $(".layer-box").fadeIn();
                $(document).on("click", function (e) {
                    e.stopPropagation();
                    $(".layer-box").fadeOut();
                })
            }
        });

    })
</script>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        direction: 'vertical',
        mousewheelControl: true,
        parallax: true,
        onSlideChangeStart: function (swiper) {
            var activeIndex = swiper.activeIndex;
            if (activeIndex != 0) {
                $(".nav").attr("class", "nav nav-there")
            } else {
                $(".nav").attr("class", "nav")
            }
        }
    });
</script>
</body>
</html>