<div class="page-header">
    <h1>
        <i class="fa fa-gear"></i> VIP基本设置
        <small>

        </small>
    </h1>
</div>
<style>
    .form-group {
        min-height: 30px;
        overflow: hidden;
    }

    .form-group input[type='number'] {
        width: 100px;
    }

    .form-group .control-label {
        text-align: right;
    }

    .form-group select {
        margin: 0;
    }

    .disabled {
        background-color: #e4e4e4;
        width: 100%;
        height: 100%;
        overflow: hidden;
    }

    .discuss_recommend_wrap, .share_wrap {
        padding-top: 10px;
        margin-bottom: 10px;
        width: 99%;
    }

    .disabled .form-group input {
        background-color: #f5f5f5;
    }

    .disabled .form-group input {
        background-color: #f5f5f5;
    }

    .minus_btn {
        box-sizing: content-box;
        width: 20px;
        height: 20px;
        float: left;
        text-align: center;
        overflow: hidden;
        display: inline-block;
        border: 1px solid #e4e4e4;
        border-radius: 100%;
        margin-right: 5px;
        margin-top: 5px;
        cursor: pointer;
    }

    .list .head {
        background-color: #f5f5f5;
    }
</style>
<p style="border-bottom: 1px dotted #e4e4e4;padding-bottom: 10px;font-weight: bold;color: #111;width: 800px;">普通用户 &
    VIP特权</p>
<table class="list" style="width: 800px">
    <tr class="head">
        <th></th>
        <th>普通用户</th>
        <th>VIP</th>
        <!--        <th>操作</th>-->
    </tr>
    <tbody>
    <tr>
        <td>领取红包上限</td>
        <td><input type="number" min="0" name="normal_package_pick_count"
                   value="<?php echo !empty($package_setting['day_pick_limit']) ? $package_setting['day_pick_limit'] : 0 ?>"/>
        </td>
        <td><input type="number" min="0" name="package_pick_count"
                   value="<?php echo !empty($setting['package_pick_count']) ? $setting['package_pick_count'] : 0 ?>"/>
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>创建群聊个数</td>
        <td><input type="number" min="0" name="normal_add_group_count"
                   value="<?php echo !empty($normal_setting['add_group_count']) ? $normal_setting['add_group_count'] : 0 ?>"/>
        </td>
        <td><input type="number" min="0" name="add_group_count"
                   value="<?php echo !empty($setting['add_group_count']) ? $setting['add_group_count'] : 0 ?>"/></td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>群聊人数</td>
        <td><input type="number" min="0" name="normal_group_member_count"
                   value="<?php echo !empty($normal_setting['group_member_count']) ? $normal_setting['group_member_count'] : 0 ?>"/>
        </td>
        <td><input type="number" min="0" name="group_member_count"
                   value="<?php echo !empty($setting['group_member_count']) ? $setting['group_member_count'] : 0 ?>"/>
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>店铺访客</td>
        <td><input type="number" min="-1" name="normal_shop_visitor"
                   value="<?php echo !empty($normal_setting['shop_visitor']) ? $normal_setting['shop_visitor'] : -1 ?>"/>
        </td>
        <td><input type="number" min="0" name="shop_visitor"
                   value="<?php echo !empty($setting['shop_visitor']) ? $setting['shop_visitor'] : -1 ?>"/>
            【-1表示全部】
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>访客</td>
        <td><input type="number" min="-1" name="normal_user_visitor"
                   value="<?php echo !empty($normal_setting['user_visitor']) ? $normal_setting['user_visitor'] : -1 ?>"/>
        </td>
        <td><input type="number" min="0" name="user_visitor"
                   value="<?php echo !empty($setting['user_visitor']) ? $setting['user_visitor'] : -1 ?>"/>
            【-1表示全部】
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    </tbody>
</table>
<p style="border-bottom: 1px dotted #e4e4e4;padding-bottom: 10px;font-weight: bold;color: #111;width: 900px;">VIP
    购买价格</p>
<table class="list" style="width: 900px">
    <tr class="head">
        <th>月份</th>
        <th>Appstore标识</th>
        <th>价格【元】</th>
        <th>赠送龙钻【仅限安卓】【个】</th>
        <!--        <th>操作</th>-->
    </tr>
    <tbody>
    <tr>
        <td>1</td>
        <td><input type="text" name="appStoreID1" style="width: 300px"
                   value="<?php echo($setting['price_detail'][1]['appStoreID']) ?>"/></td>

        </td>
        <td>￥ <input type="number" min="0" name="price1"
                     value="<?php echo($setting['price_detail'][1]['money'] / 100) ?>"/></td>
        <td><input type="number" min="0" name="diamond1" value="<?php echo($setting['price_detail'][1]['diamond']) ?>"/>
            <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>3</td>
        <td><input type="text" name="appStoreID2" style="width: 300px"
                   value="<?php echo($setting['price_detail'][3]['appStoreID']) ?>"/></td>
        <td>￥ <input type="number" min="0" name="price2"
                     value="<?php echo($setting['price_detail'][3]['money'] / 100) ?>"/></td>
        <td><input type="number" min="0" name="diamond2" value="<?php echo($setting['price_detail'][3]['diamond']) ?>"/>
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    <tr>
        <td>6</td>
        <td><input type="text" name="appStoreID3" style="width: 300px"
                   value="<?php echo($setting['price_detail'][6]['appStoreID']) ?>"/></td>
        <td>￥ <input type="number" min="0" name="price3"
                     value="<?php echo($setting['price_detail'][6]['money'] / 100) ?>"/></td>
        <td><input type="number" min="0" name="diamond3" value="<?php echo($setting['price_detail'][6]['diamond']) ?>"/>
        </td>
        <!--        <td><span class="btn btn-success btn-sm">保存</span></td>-->
    </tr>
    </tbody>
</table>
<p style="border-bottom: 1px dotted #e4e4e4;border-top: 1px dotted #e4e4e4;padding: 10px;font-weight: bold;color: #111;width: 800px;">
    <span class="btn btn-primary btn-sm btn saveBatch"><i class="fa fa-paper-plane"></i> 一键保存</span>

</p>

<script>
    seajs.use('app/panel/panel.base', function (api) {
        //一键保存
        $(".saveBatch").on('click', function () {

            var normal_package_pick_count = $.trim($("input[name='normal_package_pick_count']").val()); //普通用户领红包个数限制
            var vip_package_pick_count = $.trim($("input[name='package_pick_count']").val()); //vip用户领红包个数限制
            var normal_add_group_count = $.trim($("input[name='normal_add_group_count']").val()); //普通用户建群个数限制
            var vip_add_group_count = $.trim($("input[name='add_group_count']").val()); //vip用户建群个数限制
            var normal_group_member_count = $.trim($("input[name='normal_group_member_count']").val()); //普通用户群成员个数限制
            var vip_group_member_count = $.trim($("input[name='group_member_count']").val()); //vip用户群聊成员个数限制
            var normal_shop_visitor = $.trim($("input[name='normal_shop_visitor']").val()); //普通用户店铺访客个数限制
            var vip_shop_visitor = $.trim($("input[name='shop_visitor']").val()); //vip用户店铺访客个数限制

            var normal_user_visitor = $.trim($("input[name='normal_user_visitor']").val()); //普通用户访客个数限制
            var vip_user_visitor = $.trim($("input[name='user_visitor']").val()); //vip用户访客个数限制

            var price1 = $.trim($("input[name='price1']").val()); //1个月 vip价格
            var price2 = $.trim($("input[name='price2']").val()); //3个月 vip价格
            var price3 = $.trim($("input[name='price3']").val()); //6个月 vip价格

            var diamond1 = $.trim($("input[name='diamond1']").val()); //1个月 赠送龙钻
            var diamond2 = $.trim($("input[name='diamond2']").val()); //3个月 赠送龙钻
            var diamond3 = $.trim($("input[name='diamond3']").val()); //6个月 赠送龙钻

            var appStoreID1 = $.trim($("input[name='appStoreID1']").val()); //1个月appStoreID
            var appStoreID2 = $.trim($("input[name='appStoreID2']").val()); //3个月appStoreID
            var appStoreID3 = $.trim($("input[name='appStoreID3']").val()); //6个月appStoreID

            var data = {
                normal_package_pick_count: normal_package_pick_count,
                vip_package_pick_count: vip_package_pick_count,
                normal_add_group_count: normal_add_group_count,
                vip_add_group_count: vip_add_group_count,
                normal_group_member_count: normal_group_member_count,
                vip_group_member_count: vip_group_member_count,
                normal_shop_visitor: normal_shop_visitor,
                vip_shop_visitor: vip_shop_visitor,
                normal_user_visitor: normal_user_visitor,
                vip_user_visitor: vip_user_visitor,
                price1: price1,
                price2: price2,
                price3: price3,
                diamond1: diamond1,
                diamond2: diamond2,
                diamond3: diamond3,
                appStoreID1: appStoreID1,
                appStoreID2: appStoreID2,
                appStoreID3: appStoreID3
            };
            api.requestApi('/api/vip/setting', {data: data}, function (res) {
                if (res.result == 1) {
                    tip.showTip("ok", '保存成功', 1000, function () {
                        window.location.reload();
                    });
                }
            })

        });

    });
    function error(msg) {
        tip.showTip("err", msg, 1000);
        $(".error-widget .error_msg").html(msg);
        $(".error-widget").show();
    }

</script>
