<div class="tabbable">
    <div id="device_data" style="width:600px;height:300px;overflow: hidden"></div>
</div>
<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<script type="text/javascript">
    $(document).ready(function () {
        var myChart_week = echarts.init(document.getElementById('device_data'), 'blue');
        decive_option = {
            title: {
                text: '用户注册设备统计【<?php echo $device_data["total"]?>】',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: [<?php echo $device_data['labels']?>]
            },
            series: [
                {
                    name: '注册用户',
                    type: 'pie',
                    radius: '55%',
                    center: ['50%', '60%'],
                    data:<?php echo json_encode($device_data['values'], JSON_UNESCAPED_UNICODE)?>,
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };


        // 使用刚指定的配置项和数据显示图表。
        myChart_week.setOption(decive_option);
    })


</script>