<style>
    #content {
        margin: 0 20px 0 0;
        z-index: 1;
        position: absolute;
    }

    .module-item .item {
        width: 100px;
        text-align: center;
        float: left;
        font-size: 12px;
        color: #666;
        margin: 0 12px 12px 0;
    }

    .module-item .item dt {
        height: 80px;
        overflow: hidden;
    }

    .module-item .item dt img {
        width: 100px;
    }

    .module-item .item .item-title {
        color: #333;
        margin: 8px 0 4px 0;
    }

    .base-info {
        border: 1px solid #DEEFFB;
        padding: 8px;
        line-height: 200%;
        color: #00752f;
        font-size: 16px;
        font-weight: normal;
    }

    .base-info strong {
        font-weight: normal;
        font-size: 14px;
        color: #666;
    }

    #aside {
        display: none;
        min-width: 300px;
        width: 100%;
        margin: 0 0 0 820px;
        padding: 0 0 0 820px;
        position: absolute;
        right: 0;
        top: 0;
    }

    .accordion .accordion-group {
        margin: 2px 0;
    }

    .accordion-heading {
        line-height: 36px;
        padding: 0 8px;
        border: 1px solid #DEEFFB;
        background: #FEFCEF;
        color: #000;
    }

    .accordion-heading a {
        color: #063;
    }

    .accordion-body {
        text-indent: 24px;
        border: 1px solid #DEEFFB;
        border-top: none;
        padding: 8px;
        font-size: 12px;
    }

    .box-title {
        border-bottom: 1px solid #DEEFFB;
        padding: 0 0 4px;
    }

    .unstyled {
        margin: 8px 0 0 0;
        line-height: 160%;
    }

    .noborder {
        border: none;
    }

    .line {
        margin: 12px 0;
        border: 1px solid #DEEFFB;
        line-height: 36px;
        font-size: 14px;
        padding: 0 8px;
        background: #FEFCEF;
        color: #000;
        font-family: 'Microsoft Yahei';
    }

    .func-list .module-func, .func-list .base-func {
    }

    .func-list .func {
        width: 247px;
        height: 80px;
        float: left;
        font-size: 12px;
        line-height: 120%;
        border: 1px solid #d0dfeb;
        margin: 10px 10px 0 0;
        background: #fff;
        position: relative;
        color: #999;
        overflow: hidden;
        box-shadow: 0 0px 3px rgba(188, 204, 214, 0.3);
    }

    .func-list .func dt {
        width: 80px;
        height: 80px;
        float: left;
        overflow: hidden;
    }

    .func-list .func dt img {
        width: 78px;
        height: 78px;
        padding: 1px;
    }

    .func-list .func dd {
        float: left;
        width: 150px;
        margin: 0 0 0 10px;
    }

    .func-list .func dd .name {
        color: #000;
        font-weight: normal;
        font-size: 14px;
        padding: 8px 0 4px;
        margin: 0;
    }

    .func-list .func dd .price-line {
        line-height: 20px;
        color: #666;
    }

    .func-list .func.choosed {
        border-color: #b5c3cd;
    }

    .func-list .func .checkIcon {
        display: block;
        position: absolute;
        right: 0;
        top: 0;
        background: #fff;
        border: 1px solid #d0dfeb;
        border-right: none;
        border-top: none;
        text-align: center;
        width: 20px;
        height: 20px;
        cursor: pointer;
        line-height: 20px;
    }

    .func-list .func .checkIcon {
        color: #eee;
    }

    .func-list .func.choosed .checkIcon {
        color: #47ae2a;
    }

    .func-list .line {
        border-bottom: 1px solid #d0dfeb;
        line-height: 36px;
        color: #f00;
    }
</style>

<div class="page-header">
    <h1>欢迎来到管理中心</h1>
</div>
{{content()}}
<div class="page-wrap" style="min-width: 1100px;position: relative;">

    <div id="content">

        <h4 class="box-title">账户信息</h4>

        <div class="base-info">
            <p>
                <span class="right">
                    <a href="/panel/setting/index">编辑</a>
                </span>
                <strong>账号ID:</strong>
                <?php echo $admin['id']; ?>
                <strong>管理账号:</strong>
                <?php echo $admin['account']; ?>
                <!-- <strong>管理邮箱</strong>
                 --><?php /*echo $admin->email; */ ?>
            </p>
            <p>
                <strong>用户名称</strong>
                <?php echo $admin['name']; ?>

                <strong>你的角色</strong>
                <?php
                echo $admin['group_name'];
                ?>
            </p>

        </div>
        <h4 class="box-title">服务器信息</h4>

        <div class="base-info">
            <p>
                <span class="right">
                  <!--  <a href="/panel/setting/index">编辑</a>-->
                </span>
                <strong>php版本:</strong>
                <?php echo PHPVERSION(); ?>
                <strong>php框架:</strong>
                <?php
                $phalcon = new ReflectionExtension('phalcon');
                echo 'phalcon' . $phalcon->getVersion(); ?>
                <!-- <strong>管理邮箱</strong>
                 --><?php /*echo $admin->email; */ ?>
            </p>
            <p>
                <strong>服务器引擎</strong>
                <?php echo $_SERVER['SERVER_SOFTWARE']; ?>

            </p>


        </div>
    </div>
</div>
