<div style="padding:7rem 1rem 0;font-size: 0.85rem;width: 100%;text-align: center;height: auto;overflow: hidden">
    <img src="/static/wap/images/warning.png" style="width: 4rem"/>
    <p style="line-height: 3rem;font-weight: bold;font-size: 1rem">已停止访问该网页</p>
    <p style="color: #828282;font-size: 0.75rem;line-height: 1.2rem">网页包含诱导分享、诱导关注内容，被多人投诉，为维护绿色上网环境，已停止访问。</p>
</div>
<p style="position: fixed;bottom: 0;left: 0;width: 100%;height: 1.6rem;line-height: 1.6rem;font-size: 0.7rem;text-align: center;">
    <a href="http://wap.klgwl.com/article/detail/MaT2UxxnMdj2Ewx-NTQ4OA--" style="color:cadetblue">查看规则</a>
</p>