<li class="folder" data-path="<?php echo $item['path']; ?>">
    <fieldset>
        <legend>
            <a href="javascript:;" class="getSubBtn" data-path="<?php echo $item['path']; ?>">
                <i class="fa <?php echo "fa-folder" ?>"></i>
                <span class="name"><?php echo $item['name']; ?></span>
            </a>
        </legend>
    </fieldset>
    <ul class="sub-files" data-path="<?php echo $item['path']; ?>">

    </ul>
</li>