<form action="" method="get" style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px;">
    <label for="name">群聊ID</label>
    <input name="gid" type="text" id="gid" placeholder="群聊ID" value="<?php echo $gid ? $gid : ''; ?>">
    &nbsp;
    <label for="name">云信群聊ID</label>
    <input name="yx_gid" type="text" id="yx_gid" placeholder="云信群聊ID" value="<?php echo $yx_gid ? $yx_gid : ''; ?>">
    &nbsp;
    <label for="name">群主</label>
    <input name="key" type="text" id="key" placeholder="用户昵称/手机/用户ID" value="<?php echo $key; ?>">
    &nbsp;
    <label for="name">群名称</label>
    <input name="name" type="text" id="name" placeholder="群名称" value="<?php echo $name; ?>">
    &nbsp;
    <label for="name">状态</label>
    <select name="status">
        <option value="-1" <?php echo $status == -1 ? 'selected' : ''; ?>>全部</option>
        <option value="0" <?php echo $status == 0 ? 'selected' : ''; ?>>系统封杀</option>
        <option value="1" <?php echo $status == 1 ? 'selected' : ''; ?>>正常</option>
        <option value="2" <?php echo $status == 2 ? 'selected' : ''; ?>>被群主解散</option>
    </select>
    &nbsp;<label for="name">建群时间:</label>
    <input type="text" id="start" value="<?php echo $start; ?>" placeholder="开始时间" name="start"
           data-date-format="yyyy-mm-dd hh:ii"/>
    - <input type="text" id="end" value="<?php echo $end; ?>" placeholder="结束时间" name="end"
             data-date-format="yyyy-mm-dd hh:ii"/>
    <input type="submit" class="btn btn-primary btn-sm" value="搜索">
</form>
<table id="article-list" class=' list'>
    <thead>
    <tr class="head">
        <th style='width:36px'>群ID</th>
        <!--  <th style='width:50px'>云信群ID</th>-->
        <!-- <th style='width:36px'>批量</th>-->
        <th style='width:80px'>群头像</th>
        <th style='width:180px'>创建时间</th>
        <th style='width:80px'>成员数</th>
        <th style='width:100px'>容纳人数</th>
        <th>群名称</th>
        <!--    <th style='width:300px'>审核</th>-->

        <th style='width:90px'>状态</th>
        <th style='width:150px'>群主</th>

        <th>操作</th>
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>
    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">
            <th class='name'><?php echo $item['id']; ?></th>
            <!--    <th class='name'><?php /*echo $item['yx_gid']; */ ?></th>-->
            <!--     <td class="center"><input type="checkbox" class="chk" data-id="<?php /*echo $item['id']; */ ?>"/></td>-->
            <td>
                <img
                    src="<?php echo $item['avatar'] ? $item['avatar'] : $item['default_avatar']; ?>?x-oss-process=image/resize,m_fill,h_160,w_160"
                    width="40"
                    height="40" style="border-radius: 100%"/>
            </td>
            <td><?php echo date('Y-m-d H:i:s', $item['created']); ?></td>
            <td><?php echo $item['member_count'] ?></td>
            <td class="center">
                <?php echo $item['member_limit']; ?>
            </td>
            <td>
                <?php echo $item['name'] ? $item['name'] : $item['default_name']; ?>
            </td>

            <td class="center">
                <?php if ($item['status'] == 0) {
                    echo "<label class='badge badge-danger'>已被系统封杀</label>";
                } else if ($item['status'] == 1) {
                    echo "<label class='badge badge-success'>正常</label>";
                } else if ($item['status'] == 2) {
                    echo "<label class='badge badge-grey'>群主已解散</label>";
                }; ?>
            </td>
            <td>
                <?php echo $item['admin_info']['mark'] ? $item['admin_info']['nick'] : $item['admin_info']['default_nick']; ?>
                【<?php echo $item['user_id']; ?>】

            </td>

            <td>
                <a class="btn btn-sm btn-primary newTarget" href="javascript:;" data-href="/panel/group/detail/<?php echo $item['id']; ?>" data-title="群详情">详情</a>
                <?php if ($item['status'] == 1) { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-danger btn-sm delBtn">封杀</a>
                <?php } else if ($item['status'] == 0) { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-success btn-sm recoveryBtn">恢复正常</a>
                <?php } ?>
            </td>
        </tr>
        <?php
    }
    } else {
        ?>
        <tr>
            <td colspan="9">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--  <tr class="showpage">
          <th class="name">操作</th>
          <td colspan="13">
                  <span>
                      [ <a href="javascript:;" class="selectAll">全选</a> ]
                      [ <a href="javascript:;" class="selectNone">全不选</a> ]
                      [ <a href="javascript:;" class="selectInvert">反选</a> ]
                      <a class="btn-light delAllSelected" href="javascript:;">批量屏蔽</a>
                  </span>
          </td>
      </tr>-->
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="13">
            <?php \Util\Pagination::instance($this->view)->display($this->view); ?>
        </td>
    </tr>
</table>
<div class="modal fade" id="checkModal">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">封杀原因</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <div>
                    <div class="form-group">
                        <label for="form-field-11">审核失败原因:</label>
                        <select name="reason_list" class="reason_list">
                            <option value="0">无</option>
                            <option value="1">涉嫌营销推广</option>
                            <option value="2">涉嫌淫秽色情</option>
                        </select>
                    </div>
                    <textarea id="reason" placeholder="请填写具体原因" class=" form-control"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 100px;"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" value="0" id="group_id"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-type="user" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
    seajs.use('app/panel/group/panel.group', function (api) {
        api.del();
        $(".reason_list").on('change', function () {
            var r_value = $(this).val();
            if (r_value != '0') {
                $("#reason").val($(".reason_list option[value='" + r_value + "']").html());
            }
        })
    });
</script>
<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script>
    /*   seajs.use('app/users/users.bind', function (e) {
     e.deleteUsers('.delBtn');
     e.recoveryUsers('.recoveryBtn');
     e.forbidUsers('.forbidBtn');
     e.unForbidUsers('.unForbidBtn');

     });*/
    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
    $('#end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
</script>
