<style>
    #content_list {
        padding: 0 10px;
    }

    #content_list li {
        list-style-type: none;
        line-height: 30px;
        height: 30px;
        border-bottom: 1px dotted #e4e4e4;
        overflow: hidden;
        cursor: pointer;
    }

    #content_list li img {
        width: 25px;
        height: 25px;
        border-radius: 100%;
        margin-right: 5px;
    }

    #content_list {
        width: 85%;
        margin: auto;
        height: auto;
        display: none;
        border: 1px solid #e4e4e4;
        margin-bottom: 5px;
    }
</style>
<?php
$plat = $this->request->get('plat');
?>
<div class="page-header">
    <h1>
        广告位列表
    </h1>
</div>
<table class="list">
    <thead>
    <tr class="head">
        <th>标号</th>
        <th>标识</th>
        <th>位置</th>
        <th>广告大小(px)</th>
        <!-- <th>价格</th>-->
        <!-- <th>内容模型</th>-->
        <th>更换周期</th>
        <th>广告数量</th>
        <th>本期广告数</th>
        <th>操作</th>
        <!--  <th>下期剩余</th>-->
    </tr>
    </thead>
    <tbody>
    <?php if ($list): ?>
        <?php foreach ($list as $ad): ?>
            <tr>
                <th class="name"><?php echo $ad['id']; ?></th>
                <td><?php echo $ad['ads_key']; ?></td>
                <td><?php echo $ad['name']; ?></td>

                <td>
                    <span class="num"><?php echo $ad['size']; ?></span>
                </td>
                <!-- <td>
                    <span class="num">￥<?php /*echo $ad['price']; */ ?>元</span>
                </td>-->
                <!--  <td class="center">
                    <?php /*echo \service\site\AdvertiseManager::$_type_name[$ad['content_type']] */ ?>
                </td>-->
                <td class=" green">
                    <?php echo \Services\Site\AdvertiseManager::$_frequency_name[$ad['frequency']] ?>
                </td>
                <td>
                    <span class="num">
                        <?php echo $ad['num'] > 0 ? $ad['num'] : '无限制' ?>
                    </span>
                </td>
                <td>
                    <span class="num red" id="this_term_left_<?php echo $ad['id']; ?>">
                        <?php echo $ad['current']; ?>
                    </span>

                </td>
                <td>
                    <a href="javascript:;" class="btn btn-primary add_btn btn-sm"
                       data-key="<?php echo $ad['ads_key'] ?>"><i class="fa fa-plus"></i> 添加</a>
                    <a href="<?php echo $this->uri->baseUrl('ads/list?key=' . $ad['ads_key']) ?>"
                       class="btn btn-purple btn-sm"><i class="fa fa-eye"></i> 查看</a>

                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="12">
                <p class="noData red" style="margin: 20px;">该平台没有广告可以购买</p>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<div class="modal fade" id="adsModal">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">添加广告</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <div>
                    <form class="form-horizontal" role="form" id="adsForm">
                        <input type="hidden" id="ads_key" name="ads_key" value="">

                        <div class="form-group">
                            <label for="ruleName" class="col-sm-2 control-label">广告标题:</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control title" id="title" name="title"
                                       placeholder="广告标题">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-2 control-label">广告图片:</label>

                            <div class="col-sm-10">
                                <input type="text" name="thumb" id="thumb"
                                       value="" class="txt"
                                       readonly/>
                                <a class="btn btn-sm btn-success" id="uploadMainPic" href="javascript:;">广告图片</a>
                                <img src="" alt="" id="thumbPreview"
                                     style="height: 32px;"/>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-2 control-label">广告模型:</label>

                            <div class="col-sm-10">
                                <label>
                                    <input type="radio" class="txt content_type ace active" name="content_type"
                                           data-name="链接"
                                           data-type="link"
                                           value="link" checked/>
                                    <span class="lbl"> <b>普通链接</b></span>
                                </label>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-2 control-label">链接地址:</label>

                            <div class="col-sm-10">
                                <input type="text" class="txt  content_type_link" data-type="link"
                                       name="content_type_link" value=""
                                       style="width: 100%"/>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-2 control-label">权重:</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control sort" id="sort" name="sort"
                                       value="50"
                                       placeholder="权重【越大越靠前】">
                            </div>
                        </div>
                        <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                            <span class="error_msg"></span>
                        </p>
                        <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                            <span class="success_msg"></span>
                        </p>

                        <div class="preview">
                            <img src="" class="pic-preview" alt=""/>
                        </div>
                    </form>

                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" value="0" id="apply_id"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary submitBtn" data-id="0" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->


<script type="text/javascript">
    seajs.use('app/panel/site/advertise', function (api) {
        api.addAdvertiseApp();
    });
</script>
