<link rel="stylesheet" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/panel/js/tools/Url.js"></script>
<style>
    td{
        vertical-align: middle !important;
    }
    select,option{
        font-size:12px;
        /*color:#428bca;*/
        border-radius: 5px;
        /*background-color:#eee;*/
    }
    input[type='text']{
        border-radius:3px !important;
    }
</style>
<label style="font-weight:bold">手机/用户ID：</label><input type="text" name="search" placeholder="请输入手机号/用户ID" value="{{mixed}}">
<label style="font-weight:bold;margin-left:20px">发送时间：</label><input type="text" name="start" value="{{start}}"> - <input type="text" name="end" value="{{end}}">
<button class="btn btn-xs btn-primary" style="padding-top:3px;margin-left:10px" id="search">搜索</button>
<button class="btn btn-xs btn-primary" style="padding-top:3px;margin-left:10px" id="reset">重置</button>
<hr class="hr-10">
<table class="table table-striped table-bordered table-hover">
    <thead class="thin-border-bottom">
    <tr>
        <th class="center" style="width:6%">用户</th>
        <th class="center" style="width:4%">手机</th>
        <th class="center" style="width:5%">
            状态<br>
            <select name="status" id="status">
                <option value="" <?php if(empty($status)) echo "selected" ?> >全部</option>
                <option value="1" <?php if($status==1) echo "selected" ?> >失败(恐龙谷)</option>
                <option value="2" <?php if($status==2) echo "selected" ?> >失败(云片)</option>
                <option value="3" <?php if($status==3) echo "selected" ?> >成功</option>
            </select>
        </th>
        <th class="center" style="width:20%">失败原因</th>
        <th class="center" style="width:3%">
            短信类型<br>
            <select name="type" id="type">
                    <option value="" <?php if(empty($type)) echo "selected" ?> >全部</option>
                <?php foreach( $type as $k => $v) {?>
                    <option value="{{k}}" <?php if($typeBack == $k) echo "selected" ;?> >{{v}}</option>
                <?php } ?>
            </select>
        </th>
        <th class="center" style="width:3%;">
            device<br>
            <select name="device" id="device">
                <option value="" <?php if(empty($device)) echo "selected" ?>>全部</option>
                <option value="ios" <?php if($device == 'ios') echo "selected" ;?> >ios</option>
                <option value="android" <?php if($device == "android") echo "selected" ;?> >android</option>
            </select>
        </th>
        <th class="center" style="width:6%">发送时间</th>
    </tr>
    </thead>
    <tbody>
    <?php if(!empty($list)) { ?>
        <?php foreach( $list as $item ):?>
            <tr>
                <td class="">
                <?php if($item['uid'] != 0) {?>

                    <img class="pull-left" alt="" src="<?php echo $user[$item['uid']]['avatar']?>?x-oss-process=image/resize,m_fill,h_200,w_200" style="border: 2px solid #c9d6e5;border-radius: 100%;max-width: 40px;margin-right: 10px;margin-left: 0;box-shadow: none;">
                    <span style="">
                            <a href="javascript:;" data-href="/panel/users/detail/?user_id={{item['uid']}}" title="{{item['uid']}}" data-id="user_detail_{{item['uid']}}" data-title="用户详情" class="newTarget" target="_blank" style="color:deeppink"><?php echo $user[$item['uid']]['username']?></a>
                            <br>
                            <a href="javascript:;" data-href="/panel/users/detail/?user_id={{item['uid']}}" title="{{item['uid']}}" data-id="user_detail_{{item['uid']}}" data-title="用户详情" class="newTarget" target="_blank" ><?php echo $item['uid'] ?></a>
                    </span>

                <?php }else{?>
                    <img class="pull-left" alt="" src="http://avatorimg.klgwl.com/default/avatar.png?x-oss-process=image/resize,m_fill,h_200,w_200" style="border: 2px solid #c9d6e5;border-radius: 100%;max-width: 40px;margin-right: 10px;margin-left: 0;box-shadow: none;">
                    <span style="height:41px;line-height:41px;">
                        <a href="javascript:;" style="color:deeppink">UID为0</a>
                    </span>

                <?php }?>
                </td>

                <td>
                    <a href="javascript:;">{{item['phone']}}</a>
                </td>

                <td class="center">
                    <?php if($item['status'] == 1) {?>
                        <span class="label  label-danger arrowed-right arrowed-in" title="恐龙谷原因发送失败">失败(恐龙谷)</span>
                    <?php }elseif( $item['status'] == 2 ){?>
                        <span class="label  label-danger arrowed-right arrowed-in" title="云片原因发送失败">失败(云片)</span>


                    <?php }elseif( $item['status'] == 3 ){?>
                        <span class="label  label-success arrowed-right arrowed-in">成功</span>
                        <i href="javascript:;" class="fa fa-commenting-o  green pull-right" data-rel="tooltip" data-placement="top" data-original-title="{{item['content']}}" style="position:relative"></i>
                    <?php }?>
                </td>
                <td class="red">{{item['fail_reason']}}</td>
                <td class="center">
                    <span class="badge badge-info">{{type[item['type']]}}</span>

                </td>
                <td class="center">
                    <?php if( $item['device'] == 'ios' ) {?>
                        <i class="fa fa-apple" aria-hidden="true"></i>
                    <?php }elseif($item['device'] == 'android') {?>
                        <i class="fa fa-android green" aria-hidden="true" ></i>
                    <?php } ?>
                </td>

                <td class="center"><?php echo date('Y/m/d H:i:s',$item['send_time'])?></td>
            </tr>
            <?php endforeach;?>
    <?php }else{ ?>
        <tr>
            <td colspan="7" class="center">无数据</td>
        </tr>
    <?php }?>
    </tbody>
</table>
<?php \Util\Pagination::instance($this->view)->display($this->view) ?>
<script>
    $("[data-rel='tooltip']").tooltip()
    //选择时间
    $("input[name='start'],input[name='end']").datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        },

    });
    //下拉框change事件
    $('select').on('change',function () {
        var _this = this;
        var key = $(_this).attr('name'),
            value = $(_this).val();
        var url = new Url();
        var args = {};
        url.rmArgs(['p']);
        args[key] = value;
        url.setArgs(args);

        window.location.href = url.getUrl();
    });

    //重置
    $('#reset').on('click',function () {
        var url = new Url();
       window.location.href = url.getBaseUrl('panel/sms/record');
    });
    //搜索
    $('#search').on('click',function () {
        var url = new Url();
        var mixed = $("input[name='search']").val(),
            start = $("input[name='start']").val(),
            end = $("input[name='end']").val();
        url.rmArgs(['p']);
        url.setArgs({mixed:mixed,start:start,end:end});
        window.location.href = url.getUrl();
    });
    //enter键
    document.onkeydown = function (event) {
        var e = event || window.event || arguments.callee.caller.arguments[0];
        if (e && e.keyCode === 13) {
            $("#search").click();
        }
    };
</script>