<style>
    .anchorBL {
        display: none
    }
</style>
<link rel="stylesheet" href="/static/panel/css/badge.css">
<form action="" method="get" style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px;">
    <label for="name">邀请人</label>
    <input name="inviter" type="text" id="inviter" placeholder="用户id" value="<?php echo $inviter ? $inviter : ''; ?>">
    &nbsp;
    <label for="name">被邀请人</label>
    <input name="invitee" type="text" id="invitee" placeholder="用户id" value="<?php echo $invitee ? $invitee : ''; ?>">
    &nbsp;
    <label for="name">时间:</label>
    <input type="text" id="start" value="<?php echo $start; ?>" placeholder="开始时间" name="start"
           data-date-format="yyyy-mm-dd hh:ii"/>
    - <input type="text" id="end" value="<?php echo $end; ?>" placeholder="结束时间" name="end"
             data-date-format="yyyy-mm-dd hh:ii"/>
    <input type="submit" class="btn btn-primary btn-sm" value="搜索">
</form>

<table id="article-list" class=' list'>
    <thead>
    <tr class="head">
        <th style='width:100px'>邀请用户id</th>
        <th style='width:100px'>邀请用户名</th>
        <th style='width:150px'>被邀请人用户id</th>
        <th style='width:150px'>被邀请人用户名</th>
        <th style='width:150px'>被邀请人手机号</th>
        <th style='width:150px'>邀请者获得爱心值</th>
        <th style='width:150px'>被邀请者获得爱心值</th>
        <th style='width:150px'>创建时间</th>
        <th style='width:80px'>状态</th>
        <th style='width:100px'>激活方式</th>
        <th>操作</th>
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>
    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">
            <!--    <th class='name'><?php /*echo $item['yx_gid']; */ ?></th>-->
            <!--     <td class="center"><input type="checkbox" class="chk" data-id="<?php /*echo $item['id']; */ ?>"/></td>-->
            <td><a href="javascript:;" class="newTarget" data-title="用户详情"
                   data-href="/panel/users/detail/?user_id=<?php echo $item['inviter'] ?>"><?php echo $item['inviter']; ?></a>
            </td>

            <td><?php echo $users[$item['inviter']]['username'] ?></td>
            <td><a href="javascript:;" class="newTarget" data-title="用户详情"
                   data-href="/panel/users/detail/?user_id=<?php echo $item['user_id'] ?>"><?php echo $item['user_id']; ?></a>
            </td>

            <td><?php echo $users[$item['user_id']]['username'] ?></td>

            <td>
                <?php echo $users[$item['user_id']]['phone'] ?>
            </td>
            <td>
                <?php echo $item['point'] ?>
            </td>
            <td>
                <?php echo $item['register_point'] ?>
            </td>
            <td><?php echo date('Y-m-d H:i', $item['created']); ?></td>

            <td>
                <?php echo $item['is_active'] == 1 ? "<span class='badge badge-success'>已激活</span>" : "<span class='badge badge-gray'>未激活</span>" ?>
            </td>
            <td>
                <?php if ($item['is_active']) { ?>
                    <?php echo $item['active_type'] == 1 ? "<span class='badge badge-success'>扫码</span>" : "<span class='badge badge-success'>登录</span>" ?>
                <?php } ?>

            </td>
            <td></td>
        </tr>
        <?php
    }
    } else {
        ?>
        <tr>
            <td colspan="9">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--  <tr class="showpage">
          <th class="name">操作</th>
          <td colspan="13">
                  <span>
                      [ <a href="javascript:;" class="selectAll">全选</a> ]
                      [ <a href="javascript:;" class="selectNone">全不选</a> ]
                      [ <a href="javascript:;" class="selectInvert">反选</a> ]
                      <a class="btn-light delAllSelected" href="javascript:;">批量屏蔽</a>
                  </span>
          </td>
      </tr>-->
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="13">
            <?php \Util\Pagination::instance($this->view)->display($this->view); ?>
        </td>
    </tr>
</table>

<script src="/srv/static/panel/js/tools/Url.js"></script>
<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script>
    /*   seajs.use('app/users/users.bind', function (e) {
     e.deleteUsers('.delBtn');
     e.recoveryUsers('.recoveryBtn');
     e.forbidUsers('.forbidBtn');
     e.unForbidUsers('.unForbidBtn');

     });*/
    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
    $('#end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
</script>

<script src="/srv/static/ace/js/jquery.colorbox-min.js"></script>

<script type="text/javascript">
    $(function () {
        var colorbox_params = {
            reposition: true,
            scalePhotos: true,
            scrolling: false,
            previous: '<i class="fa fa-arrow-left"></i>',
            next: '<i class="fa fa-arrow-right"></i>',
            close: '&times;',
            current: '{current}/{total}',
            maxWidth: '100%',
            maxHeight: '100%',
            onOpen: function () {
                document.body.style.overflow = 'hidden';
            },
            onClosed: function () {
                document.body.style.overflow = 'auto';
            },
            onComplete: function () {
                $.colorbox.resize();
            }
        };
        $('.ace-thumbnails').each(function () {
            $('.ace-thumbnails [data-rel="' + $(this).attr('data-id') + '"]').colorbox(colorbox_params);
        });
        $("#cboxLoadingGraphic").append("<i class='fa fa-spinner orange'></i>");//let's add a custom loading icon

        var order = '<?php echo $sort ?>'
        var sort_order = '<?php echo $sort_order ?>'
        if (order != '' && sort_order != '') {
            var current = $(".arrow[data-order='" + order + "']");
            current.addClass("active");
            current.attr('data-sort', sort_order);
            if (sort_order == 'desc') {
                current.find('.arrow-down').addClass('active');
                current.find('.arrow-up').addClass('disabled');
            } else {
                current.find('.arrow-down').addClass('disabled');
                current.find('.arrow-up').addClass('active');
            }
        }
        var url = new Url();
        $(".arrow").on('click', function () {
            var order = $(this).attr('data-order');
            var sort = $(this).attr('data-sort');
            sort = sort == 'desc' ? 'asc' : 'desc';
            url.setArgs({order: sort, sort: order, p: 1});
            window.location.href = url.getUrl();
        });
    })
</script>
