<div class="page-header">
    <h1>
        <i class="fa fa-gear"></i> 租人配置
        <small>

        </small>
    </h1>
</div>
<style>
    .form-group {
        min-height: 30px;
        overflow: visible;
    }

    .form-group .control-label {
        text-align: right;
    }

    .form-group select {
        margin: 0;
    }

    .list {
        width: 98%;
        margin: auto;
        display: none;
    }

    .btn {
        display: inline-block;
        cursor: pointer;
    }

    .cancelBtn, .saveBtn {
        display: none;
    }

    .skill_head {
        width: 98%;
        margin: auto;
        border: 1px solid #e2e2e2;
        margin-bottom: 0;
        line-height: 40px;
        border-radius: 2px 2px 0 0;
        padding: 0 10px;
        font-weight: bold;
    }

    .skill_head .spread {
        cursor: pointer;
    }

    textarea.desc {
        min-height: 100px;
    }

    .list input {
        max-width: 80px;
    }

    .title input {
        max-width: 200px;
    }

    .skill_head:first-child {
        border-bottom: none;
    }

    .tip {
        position: relative;
        overflow: visible;
    }

    .tip_box {
        position: absolute;
    }

    img {
        background: #fff;;
    }
</style>
<main class="tab-content" style="border:none; ">

    <section id="home" class="tab-pane in active" style="border:  1px solid #e4e4e4">
        <p class="alert alert-info" style="border-top:none;border-left: none;border-right: none">
            <i class="fa fa-cogs"></i> 基础设置<br/>

        </p>
        <div class="form-group " style="">

            <label for="name" class="col-sm-3 control-label">邀请人获得爱心值:</label>

            <div class="col-sm-9">
                <input type="number" class="point" value="<?php echo $setting['point'] ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">被邀请人获得爱心值:</label>

            <div class="col-sm-9">
                <input type="number" class="register_point" value="<?php echo $setting['register_point'] ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">多少爱心值可兑换一元:</label>

            <div class="col-sm-9">
                <input type="number" class="rate"
                       value="<?php echo $setting['rate'] ?>"/>
            </div>
        </div>
        <hr style="border:none;border-bottom: 1px dotted #e4e4e4;"/>

        <div class="form-group">
            <label for="name" class="col-sm-1 control-label"></label>

            <div class="col-sm-10" style="padding: 0 0 0 30px;">
                <button type="submit" class="btn btn-primary btn-sm btnSave" name="btn-base">
                    <i class="fa fa-paper-plane"></i>立即保存
                </button>
            </div>
        </div>
    </section>

</main>
<script>
    seajs.use('app/panel/panel.base', function (api) {
        $(".btnSave").on('click', function () {
            var point = $(".point").val();
            var register_point = $(".register_point").val();
            var rate = $(".rate").val();

            var data = {
                point: point,
                register_point: register_point,
                rate: rate
            };

            api.requestApi('/api/welfare/setting', data, function (res) {
                if (res.result == 1) {
                    tip.showTip("ok", '保存成功', 1000, function () {
                        window.location.reload();
                    });
                }
            })
        })
    });
</script>

