
<div id="res">
初始化0
</div>
<script src="/static/ace/js/jquery-1.10.2.min.js"></script>
<script src="/static/wap/klgJsSdk.js?1.0.18"></script>

<script >

    klg.ready(function(){
        $('#res').html(26);
    });
    /*klg.onMenuShareAppMessage({
        "title":'测试标题',
        'success':function () {
            $('#res').html('成功回调');
        },
        'cancel':function(){
            $('#res').html('用户取消分享');
        }
    })*/

</script>