<form action="javascript:;" method="get"
      style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px; line-height: 50px;">
    <label for="name">关键字</label>
    <input name="key" type="text" id="key" placeholder="商家名称" value="<?php /*echo $key; */ ?>">
    &nbsp;
    <label for="name">状态</label>
    <select name="status" id="status">
        <option value="-1" selected>全部</option>
        <option value="1">正常</option>
        <option value="0">禁用</option>
    </select>
    &nbsp;
    <input type="submit" class="btn btn-primary btn-sm btnSearch" value="搜索">
    <span class="btn btn-primary btn-sm btnAdd right"><i class="fa fa-plus"></i> 添加供应商</span>
</form>
<table id="article-list" class='list'>
    <thead>
    <tr class="head">
        <th style='width:80px'>商户号</th>
        <th style='width:150px'>商家名称</th>
        <th style='width:80px'>商家logo</th>
        <th style='width:80px'>文网文</th>
        <th style='width:80px'>icp</th>
        <th style='width:80px'>ji</th>
        <th style='width:150px' class="arrow" data-sort="" data-order="status">
            <span class="text">状态</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up"></i>
            </span>
        </th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody class="listData">
    <tr>
        <td colspan="12">
            <li class="loading"
                style="text-align: center;display:none;width: 100%;line-height: 100px;height: 100px;vertical-align: middle">
                <img
                    style="width: 40px" src="/srv/static/panel/images/admin/loading2.gif"></li>
        </td>
    </tr>
    </tbody>
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="17">
            <div class="pageBar"></div>
        </td>
    </tr>
    <tr class="showpage">
        <th class="name">操作</th>
        <td colspan="13">
            <span class="btn btn-xs btn-inverse btnAdd"><i class="fa fa fa-plus"></i> 添加提供商</span>
        </td>
    </tr>
</table>
<div class="modal fade" id="tagModal">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">商家编辑</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-2 control-label">商家名称:</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name"
                                   placeholder="游戏名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-2 control-label">商家logo：</label>
                        <div class="col-sm-10">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="thumb" id="thumb" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon upTagThumb"  href="javascript:;">选择图片</a>
                                </div>
                            </div>
                        <span class="col-xs-4 pic-review picReviewer"  data-list-item-id="12">
                            <img src=""
                                 class="preview-thumb"
                                 style="height: 32px;" title="选择图片">
                            <label class="help-block with-errors"></label>
                        </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-2 control-label">文网文：</label>
                        <div class="col-sm-10">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="ncbl" id="ncbl" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon upTagThumb"  href="javascript:;">选择图片</a>
                                </div>
                            </div>
                            <span class="col-xs-4 pic-review picReviewer"  data-list-item-id="12">
                            <img src=""
                                 class="preview-thumb"
                                 style="height: 32px;" title="选择图片">
                            <label class="help-block with-errors"></label>
                        </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-2 control-label">icp：</label>
                        <div class="col-sm-10">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="icp" id="icp" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon upTagThumb"  href="javascript:;">选择图片</a>
                                </div>
                            </div>
                            <span class="col-xs-4 pic-review picReviewer"  data-list-item-id="12">
                                <img src=""
                                     class="preview-thumb"
                                     style="height: 32px;" title="选择图片">
                                <label class="help-block with-errors"></label>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-2 control-label">bp：</label>
                        <div class="col-sm-10">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="bp" id="bp" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon upTagThumb"  href="javascript:;">选择图片</a>
                                </div>
                            </div>
                            <span class="col-xs-4 pic-review picReviewer"  data-list-item-id="12">
                            <img src=""
                                 class="preview-thumb"
                                 style="height: 32px;" title="选择图片">
                            <label class="help-block with-errors"></label>
                        </span>
                        </div>
                    </div>
                    <div class="form-group submit_yunpian">
                        <label for="ruleName" class="col-sm-2 control-label">可用:</label>
                        <div class="col-sm-10">
                            <input id="status" type="checkbox"
                                   class="ace ace-switch ace-switch-5"/>
                            <span class="lbl"></span>
                        </div>
                    </div>
                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <input type="hidden" value="0" id="customer_id"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<link rel="stylesheet" href="/srv/static/panel/css/lightbox/lightbox.css"/>

<script src="/srv/static/panel/js/jquery/lightbox/lightbox.js"></script>

<script type="text/javascript">

    $('[data-rel=tooltip]').tooltip();
    seajs.use(['/srv/static/panel/js/app/panel/customer/game.js?v=1.0.0', '/srv/static/panel/js/app/panel/panel.base'], function (api, base) {
        api.CustomerList();
        base.pageList({'url': '/api/game/getCustomerList'});
    });
    $(document).ready(function () {
        lightbox.option({
            albumLabel: '%1/%2',
            'resizeDuration': 200,
            "fadeDuration":0,
            "imageFadeDuration":0
        });
    })

</script>


