<form action="javascript:;" method="get"
      style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px; line-height: 50px;">
    <label for="name">关键字</label>
    <input name="key" type="text" id="key" placeholder="应用名称" value="<?php /*echo $key; */ ?>">
    &nbsp;
    <label for="name">状态</label>
    <select name="status" id="status">
        <option value="-1" selected>全部</option>
        <option value="1">正常</option>
        <option value="0">禁用</option>
    </select>
    &nbsp;
    <label for="name">应用提供商</label>
    <select name="customer">
        <option value="-1" selected>全部</option>
        <?php foreach ($customers as $c) { ?>
            <option value="<?php echo $c['id'] ?>"><?php echo $c['name'] ?></option>
        <?php } ?>
    </select>
    <input type="submit" class="btn btn-primary btn-sm btnSearch" value="搜索">
    <span class="btn btn-primary btn-sm btnAdd right"><i class="fa fa-plus"></i> 添加应用</span>
</form>
<table id="article-list" class='list'>
    <thead>
    <tr class="head">
        <!--    <th style='width:70px'>标识ID</th>-->
        <th style='width:120px'>应用名称</th>
        <th style='width:150px'>应用提供商</th>
        <th style='width:80px'>应用logo</th>
        <th style='width:120px'>APP_ID</th>
        <th style='width:120px'>APP_KEY</th>
<!--        <th style='width:200px'>APK签名【安卓】【小写】</th>-->
<!--        <th style='width:120px'>安卓包名</th>-->
<!--        <th style='width:180px'>bundle_id【ios】</th>-->
<!--        <th style='width:200px'>bundle_id【ios测试环境】</th>-->

        <!-- <th style='width:200px'>链接地址</th>-->

        <!-- <th style='width:80px' class="arrow" data-sort="" data-order="sort_num">
             <span class="text">排序</span>
             <span class="arrow_wrap">
                 <i class="fa fa-caret-down arrow-down"></i>
                 <i class="fa fa-caret-up arrow-up"></i>
             </span>
         </th>-->

        <th style='width:80px' class="arrow" data-sort="" data-order="status">
            <span class="text">状态</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up"></i>
            </span>
        </th>
        <!--  <th style='width:90px'>app内登录</th>-->
        <th>操作</th>
    </tr>
    </thead>
    <tbody class="listData">
    <tr>
        <td colspan="12">
            <li class="loading"
                style="text-align: center;display:none;width: 100%;line-height: 100px;height: 100px;vertical-align: middle">
                <img
                    style="width: 40px" src="/srv/static/panel/images/admin/loading2.gif"></li>
        </td>
    </tr>
    </tbody>
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="17">
            <div class="pageBar"></div>
        </td>
    </tr>
    <tr class="showpage">
        <th class="name">操作</th>
        <td colspan="13">
            <span class="btn btn-xs btn-inverse btnAdd"><i class="fa fa fa-plus"></i> 添加游戏</span>
        </td>
    </tr>
</table>
<div class="modal fade" id="tagModal">
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">应用编辑</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">提供方:</label>
                        <div class="col-sm-9">
                            <select name="customer" id="customer">
                                <?php foreach ($enable_customers as $c) { ?>
                                    <option value="<?php echo $c['id'] ?>"><?php echo $c['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">应用名称:</label>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="name"
                                   placeholder="应用名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">apk签名【安卓,小写】:</label>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="apk_sign"
                                   placeholder="apk签名【安卓提供】">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">安卓包名:</label>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="package_id"
                                   placeholder="安卓包名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">bundle_id【ios】:</label>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="bundle_id"
                                   placeholder="bundle_id【ios提供】">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">测试环境bundle_id【ios】:</label>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="dev_bundle_id"
                                   placeholder="bundle_id【ios提供】">
                        </div>
                    </div>
                    <!--   <div class="form-group">
                           <label for="ruleName" class="col-sm-2 control-label">链接地址:</label>

                           <div class="col-sm-10">
                               <input type="text" class="form-control" id="url"
                                      placeholder="游戏地址:http://XXX">
                           </div>
                       </div>-->
                    <!--     <div class="form-group">
                             <label for="ruleName" class="col-sm-2 control-label">排序:</label>

                             <div class="col-sm-10">
                                 <input type="text" class="form-control" id="sort_num" placeholder="排序越小越靠前">
                             </div>
                         </div>-->
                    <div class="form-group">
                        <label for="logo" class="col-sm-3 control-label">应用logo：</label>
                        <div class="col-sm-9">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="thumb" id="thumb" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon" id="upTagThumb" href="javascript:;">选择图片</a>
                                </div>
                            </div>
                    <span class="col-xs-4 pic-review" id="picReviewer" data-list-item-id="12">
                        <img src=""
                             class="preview-thumb"
                             style="height: 32px;" title="选择图片">
                        <label class="help-block with-errors"></label>
                    </span>
                        </div>
                    </div>
                    <div class="form-group submit_yunpian">
                        <label for="ruleName" class="col-sm-3 control-label">可用:</label>
                        <div class="col-sm-9">
                            <input id="status" type="checkbox"
                                   class="ace ace-switch ace-switch-5"/>
                            <span class="lbl"></span>
                        </div>
                    </div>
                    <!--   <div class="form-group">
                           <label for="ruleName" class="col-sm-2 control-label">支持App内登录:</label>
                           <div class="col-sm-10">
                               <input id="support_login" type="checkbox"
                                      class="ace ace-switch ace-switch-5"/>
                               <span class="lbl"></span>
                           </div>

                       </div>-->
                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <input type="hidden" value="0" id="game_id"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<link rel="stylesheet" href="/srv/static/panel/css/lightbox/lightbox.css"/>

<script src="/srv/static/panel/js/jquery/lightbox/lightbox.js"></script>
<script src="/srv/static/ace/js/jquery-ui-1.10.3.full.min.js"></script>
<link href="/srv/static/ace/css/jquery-ui-1.10.3.custom.min.css" rel="stylesheet"/>
<script type="text/javascript">

    $('[data-rel=tooltip]').tooltip();
    seajs.use(['/srv/static/panel/js/app/panel/customer/game.js?v=1.1.4', '/srv/static/panel/js/app/panel/panel.base'], function (api, base) {
        api.GameList();
        base.pageList({'url': '/api/game/getList'});
    });
    $(document).ready(function () {
        lightbox.option({
            albumLabel: '%1/%2',
            'resizeDuration': 200,
            "fadeDuration": 0,
            "imageFadeDuration": 0
        });
    })
    $(function () {
        $(".list th").resizable();
    });

</script>


