<script src="/srv/static/panel/js/tools/Url.js"></script>
<div style="width:700px">
    <label for="name">
        <span style="">名称：</span>
    </label>
    <input type="text" id="name" value="{{name}}" placeholder="请输入游戏名称">
    <input type="button" value="搜索" style="margin-left:10px" class="btn btn-xs btn-primary" id="search">
    <input type="button" value="添加游戏" style="margin-left:10px" class="btn btn-xs btn-success" id="add-game">

    <div style="float:right;margin-top:5px">
        <label for="" style="">
            <span style="">游戏模块开发中：</span>
        </label>
        <label >
            <input id="game-switch" name="switch-field-1" class="ace ace-switch ace-switch-6" type="checkbox" <?php if( !($this->di->get('redis')->originalGet('game_switch') == 'false') ) echo "checked"; ?>>
            <span class="lbl"></span>
        </label>
    </div>

</div>

<hr class="hr-10">
<div class="" style="width:700px">
    <style>
        table tbody tr th,table tbody tr td{
            vertical-align: middle;
        }
    </style>
    <table id="article-list" class=" list">
        <thead>
        <tr class="head">
            <th class="center" style="width:36px">ID</th>
            <th class="center" style="width:80px;">名称</th>
            <th class="center" style="width:50px">LOGO</th>
            <th class="center" style="width:30px">链接</th>
            <th class="center" style="width:100px">操作</th>

        </tr>
        </thead>
        <tbody class="listData">
        <?php if(!empty($list)) {?>
            <?php foreach($list as $item) :?>
        <tr class="item" data-id="{{item['id']}}">
            <th class="name center">
                {{item['id']}}
            </th>
            <td>
                {{item['name']}}
            </td>
            <td>
                <img src="{{item['logo']}}" alt="" style="height:60px;max-width:50px">
            </td>
            <td class="center">
                <a href="{{item['link']}}" class="btn btn-xs" target="_blank">预览</a>
            </td>
            <td class="center btns">
                <a href="javascript:;" class="btn btn-xs btn-primary edit" data-action="edit" style="margin-left:10px">
                    编辑
                </a>
                <?php if($item['status'] == 1) {?>
                    <a href="javascript:;" class="btn btn-xs btn-danger down" data-action="down" >
                        下架
                    </a>
                <?php }elseif( $item['status'] == 0 ) {?>
                    <a href="javascript:;" class="btn btn-xs btn-success up" data-action="up" >
                        上架
                    </a>
                <?php } ?>
                <a href="javascript:;" class="btn btn-xs btn-danger del" data-action="del" style="">
                    删除
                </a>
            </td>
        </tr>
                <?php endforeach; ?>
        <?php }else{?>
            <tr>
                <td colspan="5" class="center red">暂无数据</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<div class="clearfix"></div>
<?php \Util\Pagination::instance($this->view)->display($this->view) ?>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">添加H5游戏</h4>
            </div>
            <div class="modal-body">
                <div class="col-xs-10" >
                    <form class="form-horizontal" role="form">
                        <input type="hidden" id="action" >
                        <input type="hidden" id="edit-id" >
                        <div class="form-group">
                            <label for="new-name" class="col-sm-3 control-label">游戏名称：</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="new-name" placeholder="请输入游戏名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="new-link" class="col-sm-3 control-label">链接：</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="new-link" placeholder="请输入游戏链接">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="new-logo" class="col-sm-3 control-label" style="height:50px;line-height: 50px;">游戏LOGO：</label>
                            <div class="col-sm-9" style="height:50px;line-height: 50px;">
                                <img id="new-logo" src="" alt="" style="width:50px;height:50px">
                                <a href="javascript:;" class="btn btn-xs btn-primary" style="" id="select-logo">选择LOGO</a>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary save">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>
<script>
    $('#test').on('click',function () {
        console.log($(this).is(':checked'));
    });
    seajs.use('app/panel/panel.base',function (api) {
        //搜索
        $('#search').on('click',function () {
            var name = $.trim($('#name').val());
            var url = new Url();
            url.rmArgs(['p']);
            url.setArgs({'name':name});
            window.location.href = url.getUrl();
        });
        //操作按钮
        $('.btns').on('click',function () {
            var target = event.target;
            if (target.tagName === 'TD')
                return;
            if( $(target).data('action') === 'edit' )
                return;
            var id = $(target).closest('tr').data('id');
            var action = $(target).data('action');
            api.requestApi('/api/game/operate',{id:id,action:action},function (res) {
                if(res.result === 1)
                {
                    tip.showTip('ok','操作成功',1000,function () {
                        window.location.reload();
                    })
                }else
                {
                    tip.showTip('err','操作失败',2000)
                }

            })
        });

        //显示添加新游戏
        $('#add-game').on('click',function () {
            $('#new-name').empty();
            $('#new-link').empty();
            $('#new-logo').attr('src','');
            $('#action').val('add');
            $('#myModal').modal('show');
        });
        //添加图片
        $('#select-logo').on('click',function () {
            $node_file = $('<input type="file" style="display:none">');
            $node_file.on('change',function () {
                var file = this.files[0]; //获取file对象
                //判断file的类型是不是图片类型。
                if(!/image\/\w+/.test(file.type)){
                    alert("文件必须为图片！");
                    return false;
                }

                var reader = new FileReader(); //声明一个FileReader实例
                reader.readAsDataURL(file); //调用readAsDataURL方法来读取选中的图像文件
                //最后在onload事件中，获取到成功读取的文件内容，并以插入一个img节点的方式显示选中的图片
                reader.onload = function(e){
                    $('#new-logo').attr('src',this.result);
                }
            });
            $node_file.get(0).click();
        });
        //保存
        $('.save').on('click',function () {
            var id = $('#edit-id').val();
            var name = $.trim($('#new-name').val());
            var link = $.trim($('#new-link').val());
            var logo = $.trim($('#new-logo').attr('src'));
            var action = $.trim($('#action').val());
            var arr = {
                name:name,
                link:link,
                logo:logo
            };
            var isOk = true;
            //验证字段
            $.each(arr,function (index,value) {
                if(value === '')
                {
                    switch (index)
                    {
                        case 'name':
                            tip.showTip('err','请输入游戏名称',2000);
                            $('#new-name').focus();
                            break;
                        case 'link':
                            tip.showTip('err','请输入游戏链接',2000);
                            $('#new-link').focus();
                            break;
                        case 'logo':
                            tip.showTip('err','请选择游戏LOGO',2000);
                            break;
                    }
                    isOk = false;
                    return false;
                }
            });
            if(isOk)
            {
                api.requestApi('/api/game/operate',{id:id,name:name,link:link,logo:logo,action:action},function (res) {
                    if( res.result === 1 )
                    {
                        $('#myModal').modal('hide');
                        tip.showTip('ok','保存成功','1000',function () {
                            location.reload();
                        })
                    }

                })
            }
        });

        //编辑
        $('.edit').on('click',function () {
            var id = $(this).closest('tr').data('id');
            var name = $.trim($(this).closest('tr').find('td:eq(0)').text());
            var logo = $.trim($(this).closest('tr').find('td:eq(1) img').attr('src'));
            var link = $.trim($(this).closest('tr').find('td:eq(2) a').attr('href'));
            $('#action').val('edit');
            $('#edit-id').val(id);
            $('#new-name').val(name);
            $('#new-link').val(link);
            $('#new-logo').attr('src',logo);
            $('#myModal').modal('show');
        });

        $('#game-switch').on('click',function () {
            var val = $('#game-switch').is(':checked');
            api.requestApi('/api/game/operate',{val:val,action:'game_switch'},function (res) {
                if( res.result === 1 )
                {
                    tip.showTip('ok','操作成功',1000);
                }
            })
        });

    });


</script>