<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>恐龙谷</title>
    <meta name="keywords" content="恐龙谷">
    <meta name="description" content="恐龙谷">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="applicable-device" content="pc,mobile">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="/static/wap/css/detail.css">
    <script type="text/javascript" src="/static/wap/js/jquery/jquery-1.11.0.min.js"></script>
</head>
<body class="detail Mobile ">
<div class="mask" id="j-mask"></div>
<div class="container">
    <div class="detail-wrap ">
        <div class="detail-top clearfix">
            <div class="app-icon">
                <img src="/static/wap/images/logo.png" itemprop="image" width="78" height="78" alt="">
            </div>
            <div class="app-info">
                <p class="app-name">
                    <span class="title" itemprop="name">恐龙谷<span style="color: #fdd209;">（iOS）</span></span>
                </p>

                <p class="tagline">
                    恐龙谷-多元化自媒体社交平台
                </p>

                <div class="download-wp">
                    <a id="down1" class="install-btn i-source" rel="nofollow" style="display:inline-block;">
                        立即下载
                    </a>
                </div>
            </div>
        </div>
        <div class="cols clearfix">
            <div class="col-left">
                <div class="screenshot">
                    <h2 class="block-title">恐龙谷 截图</h2>

                    <div class="scroll-wp">
                        <div class="img-wp" style="width:775px">
                            <img itemprop="screenshot" alt="" height="266" src="/static/wap/images/download/dvalley1.png">
                            <img itemprop="screenshot" alt="" height="266" src="/static/wap/images/download/dvalley2.png">
                            <img itemprop="screenshot" alt="" height="266" src="/static/wap/images/download/dvalley3.png">
                            <img itemprop="screenshot" alt="" height="266" src="/static/wap/images/download/dvalley4.jpg">
                        </div>
                    </div>
                </div>
                <div class="desc-info">
                    <h2 class="block-title">恐龙谷 描述</h2>
                    <div class="con">
                        &#12288;&#12288;恐龙谷是一款功能全面的移动社交应用，独特的朋友圈标签动态，快速找到同好小伙伴，还有多种动态发布方式让你的朋友圈更加精彩。与好友随时随地进行语音、视频通话，畅享沟通的乐趣。
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a id="down2" class="comeon-uc i-source" rel="nofollow">
        <div class="p-logo">
            <img src="/static/wap/images/logo.png" width="40px" height="40px">
        </div>
        <div class="desc">
            <p class="txt">恐龙谷</p>
        </div>
        <span class="green-btn">立即下载（iOS）</span>
    </a>
</div>
<img id="imgtip" style="width:100%; position: absolute; top: 0; left: 0;"/>
<script type="text/javascript">
    var u = navigator.userAgent.toLowerCase();
    $("#down1,#down2").click(function () {
        if(isWeiXin() || isQQ()){
            if (u.indexOf('android') > -1 || u.indexOf('linux') > -1) {
                $("#imgtip").attr("src", "/static/wap/images/download/androdtips.png");
            } else if (u.indexOf('iphone') > -1) {
                $("#imgtip").attr("src", "/static/wap/images/download/appletips.png");
            }
        }else{
            if(u.toLowerCase().indexOf('iphone')>-1||u.toLowerCase().indexOf('ipad')>-1){
                window.location.href = "itms-services://?action=download-manifest&url=https://www.hotniao.com/demoapp/konglongguv1.0.plist";
            }else{
                //window.location.href = "http://yk.liveniao.com/download/170213.apk";
            }
        }
    })
    function isWeiXin() {
        var ua = window.navigator.userAgent.toLowerCase();
        if (ua.match(/MicroMessenger/i) == 'micromessenger') {
            return true;
        } else {
            return false;
        }
    }
	function isQQ() {
        var ua = window.navigator.userAgent.toLowerCase();
        if (ua.match(/QQ/i) == 'qq') {
            return true;
        } else {
            return false;
        }
    }
</script>
</body>
</html>