<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>恐龙谷</title>
    <link rel="stylesheet" href="/static/wap/css/download_v4.css?2.1">
    <script src="/static/wap/js/jquery/jquery2.1.4.min.js"></script>

    <script>
    	// 通过js适配不同的屏幕大小
    	(function (doc, win) {
    	  var docEl = doc.documentElement,
    	    resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize',
    	    recalc = function () {
    	      var clientWidth = docEl.clientWidth;
    	      if (!clientWidth) return;
    	      // 根据设备的比例调整初始font-size大小
    	      if(clientWidth>640) clientWidth = 640;
    	      docEl.style.fontSize = 40 * (clientWidth / 375) + 'px';
    	    };
    	  if (!doc.addEventListener) return;
    	  win.addEventListener(resizeEvt, recalc, false);
    	  doc.addEventListener('DOMContentLoaded', recalc, false);
    	})(document, window);

        var APPCommon = {
            iphoneSchema: 'DValleyNew://',
            iphoneDownUrl: 'https://itunes.apple.com/cn/app/kong-long-gu/id1208329358?mt=8',
            androidSchema: 'klg://klg.com/?type=open',
            androidDownUrl: "<?php echo $download_url?>",
            openApp: function(){
                //event.stopPropagation();
                var this_  =  this;
                //微信
                var u = navigator.userAgent.toLowerCase();
                if(this_.isWeixin()){
                    if (u.indexOf('android') > -1 || u.indexOf('linux') > -1) {//安卓手机
                        $("#imgtip").show();
                        $("#imgtip").attr("src", "/static/wap/images/download_v3/androdtips.png");
                    } else if (u.indexOf('iphone') > -1) {//苹果手机
                        window.location.href=APPCommon.iphoneDownUrl;
                        /*$("#imgtip").show();
                        $("#imgtip").attr("src", "/static/wap/images/download_v3/appletips.png");*/
                    }
                }else{//非微信浏览器
                    if (u.toLowerCase().indexOf('iphone')>-1||u.toLowerCase().indexOf('ipad')>-1) {
                        window.location.href=APPCommon.iphoneDownUrl;
                    }else if (navigator.userAgent.match(/android/i)) {
                        window.location.href=APPCommon.androidDownUrl;
                    }
                }
            },
            isWeixin: function(){ //判断是否是微信
                var ua = navigator.userAgent.toLowerCase();
                if (ua.match(/MicroMessenger/i) == "micromessenger") {
                    return true;
                } else {
                    return false;
                }
            },
            init:function(){//打开手机上安装的软件
                var u = navigator.userAgent.toLowerCase();
                if (u.toLowerCase().indexOf('iphone')>-1||u.toLowerCase().indexOf('ipad')>-1) {
                    window.location.href=APPCommon.iphoneSchema;
                }else if (navigator.userAgent.match(/android/i)) {
                    window.location.href=APPCommon.androidSchema;
                }
            }
        };

        var browser = {
            versions: function () {
                var u = navigator.userAgent, app = navigator.appVersion;
                return {//移动终端浏览器版本信息
                    trident: u.indexOf('Trident') > -1, //IE内核
                    presto: u.indexOf('Presto') > -1, //opera内核
                    webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                    gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                    mobile: !!u.match(/AppleWebKit.*Mobile.*/) , //是否为移动终端
                    ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                    android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                    iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
                    iPad: u.indexOf('iPad') > -1, //是否iPad
                    webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
                };
            }()
        }
        if (!browser.versions.mobile ) {
            window.location.href="http://www.klgwl.cn/"
        }
    </script>
</head>
<body >
    <div class="main-container">
        <div class="content">
            <ul class="page">
                <li>
                    <img src="/static/wap/images/download_v4/p1.png" alt="">
                    <span class="btn">立即下载</span>
                </li>
                <li><img src="/static/wap/images/download_v4/p2.png" alt=""></li>
                <li><img src="/static/wap/images/download_v4/p3.png" alt=""></li>
                <li><img src="/static/wap/images/download_v4/p4.png" alt=""></li>
                <li><img src="/static/wap/images/download_v4/p5.png" alt=""></li>
                <li><img src="/static/wap/images/download_v4/p6.png" alt=""></li>
            </ul>
        </div>
        <div class="footer" >
            <img src="/static/wap/images/download_v4/bar.2x.png" alt="">
            <span class="download-btn">立即下载</span>
        </div>

    </div>
    <img src="/static/wap/images/download_v3/appletips.png" id="imgtip" alt="" >

</body>
</html>

<script src="/static/wap/js/wap/download/v4/main.js?1.3"></script>
