<div style="width:100%;height:100%;">
    <div style="text-align: center;margin-top:200px">
        <h2>
            游戏首页
        </h2>
    </div>
    <div style="width:100%;text-align: center">
        <div style="border:1px solid #ccc;width:90%;margin:5% 20px;padding:10px;">
            <?php
                if($this->session->has('username'))
                    echo $this->session->get('username');
                else
                    echo "未登录";

            ?>
        </div>
    </div>

    <div style="width:100%;text-align: center;margin-top:10px;">
        <a href="javascript:;" class="btn btn-xs btn-info" id="auth">恐龙谷登录</a>
    </div>
<?php /*var_dump($_SESSION)*/?>
</div>
<?php $state = rand(10000,99999);
$this->session->set('state',$state); ?>
<script>
$('#auth').on('click',function () {
    window.location.href = "http://openauth.klgwl.com/connect/login?client_id=5&redirect_uri=http://wap.klgwl.com/index/callback&response_type=code&scope=klgapi_userinfo&state=<?php echo $state?>";

});
<?php
    $state = rand(10000,99999);
    $this->session->set('state',$state);
    if(!$this->request->has('canel_auth') && !$this->session->has('username'))
:?>
    //window.location.href = "http://openauth.klgwl.com/connect/login?client_id=5&redirect_uri=http://wap.klgwl.com/index/callback&response_type=code&scope=klgapi_userinfo&state=<?php echo $state?>";
    <?php endif;?>
</script>