

<style>
    ul li{
        height:1.5rem;
        line-height:1.5rem;
        font-size:0.8rem;
        font-weight:bold;
    }
    ul li a{
        text-decoration: underline;
    }
</style>
<div style="margin-top:1rem">
    <h2 class="center" style="font-size:0.9rem;">H5小游戏</h2>
    <ul class="center" style="margin-top:1rem">
        <li><a href="/static/game/2048/index.html">2048</a></li>
        <li><a href="/static/game/clumsy-bird/index.html">clusmsy-bird</a></li>
        <li><a href="/static/game/hextris/index.html">hextris</a></li>
        <li><a href="/static/game/0hn0/index.html">0hn0</a></li>
    </ul>

</div>
