<link rel="stylesheet" type="text/css" href="/static/panel/js/tools/trumbowyg/ui/trumbowyg.css">
<script type="text/javascript" src="/static/panel/js/tools/trumbowyg/trumbowyg.js"></script>
<style>
    .trumbowyg-modal-box label:nth-child(even) {
        display: none !important;
    }
</style>
<label for="" class="field-label" style="float:left;margin-top: 15px;">文字内容:</label>
<div class="col-sm-6" style="float: left">
    <textarea class="message_box"></textarea>
</div>
