<style>
    .plus,.minus {
        width: 20px;
        height: 20px;
        display: inline-block;
        text-align: center;
        background-color: darkgreen;
        color: #e4e4e4;
        line-height: 20px;
        vertical-align: middle;
        border-radius: 100%;
        overflow: hidden;
        margin: 10px;
        cursor: pointer;
    }

    .minus:hover {
        background-color: #00a0c7;
        color: #ddd
    }

    .tpl3_model {
        border-bottom: 1px dotted #e4e4e4;
    }


</style>
<section>
    <article class="tpl3_model" data-id="1">
        <p style="border-bottom: 1px dotted #e4e4e4;" class="btn_wrap">
            <span class="plus" style=""><i class="fa fa-plus"></i></span>
            <label>添加一组</label>
        </p>
        <div class="field set-field">
            <label for="" class="field-label">选择图文：</label>
            <select name="" id="" class="chose-existing">
                <option value="">--选择--</option>
                <?php foreach ($list as $item) :?>
                    <option value="{{item['id']}}">{{item['title']}}</option>
                <?php endforeach; ?>
            </select>
            <span class="tip"><span class="red"><*可选*></span><span class="blue">选择现有图文后以下信息将自动填充</span></span>
        </div>
        <div class="field set-field">
            <label for="" class="field-label">标题</label>
            <input type="text" class="title" name="title[]" style="width: 400px;"/>
            <span class="tip"><span class="red"></span></span>
        </div>
        <div class="field set-field">
            <label for="" class="field-label">链接地址</label>
            <input type="text" class="link" name="link[]" value="http://" style="width: 400px;"/>
            <span class="tip"><span class="red"></span></span>
        </div>
        <div class="field set-field">
            <label for="" class="field-label">图片</label>
            <span class="upload-widget" data-unique="1"><a class="btn btn-sm btn-success  browse-button"
                                                           href="javascript:;">选择图片</a></span>
            <img alt="请选择图片" src="" class="thumb" id="thumb_1"
                 style="height: 32px;display:none ;"/>
            <span class="tip"><span class="red"></span></span>
        </div>
    </article>
</section>
<script>

</script>






