<section>
    <article>
        <div class="field set-field">
            <label for="" class="field-label">选择发送群体</label>
            <label>
                <input type="radio" name="user_type" class="ace user_type " checked value="1">
                <span class="lbl"><b>所有用户</b></span>
            </label>
            <label>
                <input type="radio" name="user_type" class="ace user_type" value="2">
                <span class="lbl"><b>自定义用户</b></span>
            </label>
            <span class="tip"><span class="red"></span></span>
        </div>
        <div class="user_avatar_list">
            <label for="" class="field-label"></label>
            <label class="avatar_list">
            </label>
        </div>
    </article>
</section>