<tr class="item item_" data-id="<?php echo $item['id']; ?>"
    data-content="<?php echo base64_encode(json_encode($item)) ?>">
    <!--   <td class="center"><input type="checkbox" class="chk" data-id="<?php /*echo $item['id'];
                    */ ?>"/></td>-->
    <th class="name"><?php echo $item['id']; ?></th>


    <td><?php echo $item['name']; ?></td>
    <td><?php echo $item['next_run_time'] ? date('Y-m-d H:i:s', $item['next_run_time']) : '' ?></td>
    <td><?php echo \Services\Task\TaskManager::$task_type[$item['trigger']] ?></td>

    <td><?php foreach ($item['trigger_args'] as $k => $t) {
            echo "<span style='margin-right: 2px' class='badge badge-primary'>" . Services\Task\TaskManager::$key_name[$k] . "：" . $t . '</span>';
        }; ?></td>
    <!--    <td>--><?php //echo $item['params']['url'] ?><!--</td>-->
    <!--    <td style="min-width: 300px;">-->
    <!--        --><?php //if ($item['params']['data']) { ?>
    <!--            <span-->
    <!--                class="json_content"-->
    <!--                data-content="--><?php //echo base64_encode(json_encode($item['params']['data'])); ?><!--">-->
    <!--            </span>-->
    <!--        --><?php //} ?>
    <!--    </td>-->
    <!--    <!--                <td>--><?php ///*echo $item['ip'] */ ?><!--</td>-->
    <!---->-->
    <!--    <td>--><?php //echo $item['params']['cmd'] ?><!--</td>-->
    <td><?php echo date('Y-m-d H:i:s', $item['extra']['time']) ?></td>

    <!--                <td><?php /*echo $item['time'] > 1000 ? ($item['time'] / 1000) . 's' : $item['time'] . 'ms' */ ?></td>
-->
    <td>
        <span class="btn btn-xs btn-purple btnDetail"><i class="fa fa-eye"></i> 查看详情</span>
        <span class="btn btn-xs btn-primary btnEdit"><i class="fa fa-edit"></i> 编辑</span>
        <?php if ($item['next_run_time']) { ?>
            <span class="btn btn-xs btn-danger btnPause"><i class="fa fa-stop"></i> 暂停</span>
        <?php } else { ?>
            <span class="btn btn-xs btn-success btnStart"><i class="fa fa-play"></i> 恢复</span>
        <?php } ?>
        <span class="btn btn-xs btn-danger btnRemove"><i class="fa fa-remove"></i> 删除</span>
    </td>
</tr>
