<link rel="stylesheet" href="/static/wap/js/swiper/swiper.css"/>
<script src="/static/wap/js/swiper/swiper.js"></script>
<link rel="stylesheet" type="text/css" href="/static/wap/css/photoswipe/photoswipe.css"/>
<link rel="stylesheet" type="text/css" href="/static/wap/css/photoswipe/default-skin.css"/>
<script type="text/javascript" src="/static/wap/js/app/photoswipe/photoswipe.min.js"></script>
<script type="text/javascript" src="/static/wap/js/app/photoswipe/photoswipe-ui-default.min.js"></script>
<style>
    body {
        background-color: #F0F0F5;
    }

    .swiper-slide img {
        width: 100%;
    }

    .swiper-pagination-bullet {
        width: 0.4rem;
        height: 0.4rem;
    }

    .swiper-pagination-bullet-active {
        background-color: #000;
    }

    .swiper-pagination {
        line-height: 1rem;
    }

    .package {
        position: fixed;
        right: 0.75rem;
        bottom: 4.7rem;
        display: block;
        width: 2.05rem;
        height: 2.35rem;
        background: url(/static/panel/images/admin/red_package.png) no-repeat;
        background-size: cover
    }

    .tooltips {
        position: fixed;
        background: rgba(0, 0, 0, 0.72);
        border: 1px solid rgba(0, 0, 0, 0.72);
        border-radius: 15px;
        font-size: 0.67rem;
        color: white;
        right: 0.75rem;
        bottom: 7rem;
        margin-bottom: 20px;
        padding: 10px 30px;

    }

    .arrow {
        position: absolute;
        width: 0;
        height: 0;
        line-height: 0;
        border-width: 20px 15px 0;
        border-style: solid dashed dashed dashed;
        border-left-color: transparent;
        border-right-color: transparent;
        bottom: -20px;
    }

    .arrow-border {
        color: rgba(0, 0, 0, 0.72);
        bottom: -20px;
        right: 0.6rem;
    }
</style>
<link rel="stylesheet" type="text/css" href="/static/wap/css/footer.css"/>
<header>
    <?php $this->partial('base/footer'); ?>
</header>
<?php if ($item['images']) {
    $images = explode(',', $item['images']);
    ?>
    <div class="swiper-container" style="position: relative">
        <ul class="swiper-wrapper gallery">
            <?php foreach ($images as $i) { ?>
                <!--  <div class="">-->
                <li class="swiper-slide"
                    data-src="<?php echo $i; ?>"
                    data-size="<?php echo \Util\ImgSize::getSizeFromUrl($i) ?>"
                    data-med-src="<?php echo $i; ?>"
                    data-med-size="<?php echo \Util\ImgSize::getSizeFromUrl($i) ?>"
                    style="width: 100%;height:17.5rem;background-image: url('<?php echo $i; ?>'); background-repeat: no-repeat;background-position: center;background-size: cover">
                    <img src="<?php echo $i; ?>" style="display: none"/>
                </li>
                <!--  </div>-->
            <?php } ?>
        </ul>
        <div style="position: absolute;display: block;right:0.75rem;bottom: 0.5rem;z-index:100">
            <label
                style="font-size: 0.7rem;float: left;color: #fff;margin-right: 0.25rem;line-height: 1.125rem"><?php echo count($images) ?></label>
            <img src="/static/wap/images/pic_img.png" style="width: 1.125rem;height: 1.125rem;float: left">
        </div>
        <div
            style="position: absolute;display: block;left:0.75rem;bottom: 0.5rem;z-index:100;font-size: 0.75rem;color: #fff">
            <?php echo $item['name'] ?>
        </div>
        <div class="swiper-pagination"></div>

        <!--   <div class="swiper-button-prev"></div>
           <div class="swiper-button-next"></div>-->
    </div>
    <script>
        $(document).ready(function () {

            var mySwiper = new Swiper('.swiper-container', {

                direction: 'horizontal',  //轮播方向

                autoplay: 2000,  //自动轮播

                loop: false,   //循环
                pagination: '.swiper-pagination',
                autoplayDisableOnInteraction: false  //用户操作后不停止

            });

        });
    </script>

<?php } ?>
<style>
    .shop_detail {
        padding: 0.75rem;
        background: #fff;
        padding-bottom: 0;;
    }

    .item.brief {
        font-size: 1rem;
        border-bottom: 1px solid #e4e4e4;
        padding-bottom: 0.75rem;
        margin-bottom: 0.75rem;
        line-height: 1.5rem
    }

    .item.address {
        width: 100%;
        border-bottom: 1px solid #e4e4e4;
        padding-bottom: 0.75rem;
        height: auto;
        overflow: hidden
    }

    .item.address .pos {
        float: left;
        line-height: 2rem;
        vertical-align: middle;
        display: table-cell;
    }

    .item.address .pos img {
        width: 1.125rem;
        vertical-align: middle;
    }

    .item.address .address_detail {
        font-size: 0.65rem;
        color: #333;
        line-height: 1rem;
        float: left;
        margin-left: 0.5rem
    }

    .item.address .address_detail .address {
        max-width: 12rem;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;

    }

    .item.address .phone {
        float: right;
        line-height: 2rem;
        vertical-align: middle;
        display: table-cell;
    }

    .item.address .phone .contact_number {
        height: 1rem;
        width: 1px;
        background-color: #e0e0e0;
        line-height: 1rem;
        vertical-align: middle;
        margin-right: 0.5rem
    }

    .item.address .phone img {
        width: 1.125rem;
        vertical-align: middle;
    }

    .item.item_link {
        line-height: 1rem;
        font-size: 0.8rem;
        padding: 0.75rem 0;
        border-bottom: 1px solid #e4e4e4;
    }

    .item.item_link img {
        width: 1.125rem;
        vertical-align: middle;
    }

    .item:last-child {
        border-bottom: none;
    }

    .goods_box {
        margin-top: 1rem;
    }

    .goods_item {
        font-size: 0.65rem;
        position: relative;
        overflow: hidden;
        height: 4.5rem;
        margin-bottom: 1.25rem;
    }

    .goods_item .thumb {
        width: 4.5rem;
        height: 4.5rem;
        position: absolute;
        left: 0;
        top: 0;
    }

    .goods_item .detail {
        position: absolute;
        left: 5rem;
        right: 0;
    }

    .goods_item .detail .name {
        font-size: 0.85rem
    }

    .goods_item .detail .price {
        font-size: 0.7rem;
        color: #FC6B38;
        line-height: 1.5rem;
    }

    .goods_item .detail .brief {
        color: #999;
        font-size: 0.6rem;
        line-height: 1rem;
    }

</style>
<?php if (!strpos($this->request->getUserAgent(), 'KLG') > 0) { ?>
    <style>
        .goods_list {
            margin-bottom: 6rem;
        }
    </style>
<?php } ?>
<div class="shop_detail">
    <div class="item brief"><?php echo $item['brief'] ?></div>
    <div class="item address">
        <div class="pos">
            <!--   <a href="http://m.amap.com/navi/?dest=<?php /*echo $item['lng'] */ ?>,<?php /*echo $item['lat'] */ ?>&destName=<?php /*echo $item['name'] */ ?>&key=1d0fd0703b49e09fb43e32b55cb72880
"><img src="/static/wap/images/pos.png"/></a>-->

            <a href="http://m.amap.com/navi/?dest=<?php echo $item['lng'] ?>,<?php echo $item['lat'] ?>&destName=<?php echo $item['name'] ?>&hideRouteIcon=1&key=1d0fd0703b49e09fb43e32b55cb72880"><img
                    src="/static/wap/images/pos.png"/></a></div>

        <?php if ($item['address']) { ?>
            <a class="address_detail"
               href="http://m.amap.com/navi/?dest=<?php echo $item['lng'] ?>,<?php echo $item['lat'] ?>&destName=<?php echo $item['name'] ?>&hideRouteIcon=1&key=1d0fd0703b49e09fb43e32b55cb72880"
               target="_blank">
                <p class="address"><?php echo $item['address'] ?></p>
                <p><?php echo $item['address_detail'] ?></p>
            </a>
        <?php } ?>

        <?php if ($item['contact_number']) { ?>
            <div class="phone">
                <span class="contact_number"></span>
                <a href="tel:<?php echo $item['contact_number'] ?>"><img src="/static/wap/images/phone.png" id="phone"/></a>
            </div>
        <?php } ?>
    </div>
    <?php if ($item['url']) { ?>
        <div class="item item_link">
            <img src="/static/wap/images/link.png"/>
            <a href="<?php echo $item['url'] ?>" target="_blank"
               style="margin-left: 0.5rem"><?php echo $item['url'] ?></a>
        </div>
    <?php } ?>
</div>
<div class="goods_list"
     style="margin-top: 0.25rem;background-color: #fff;height: auto;overflow: hidden;padding: 0.75rem">
    <p style="line-height: 1rem;border-left: 0.15rem solid #fc6b38;font-size: 0.85rem;padding-left: 0.25rem;">商品</p>
    <?php if ($good_count == 0) { ?>
        <div class="no_good" style="text-align: center">
            <img src="/static/wap/images/no_goods.png" style="width: 6rem"/>
            <p style="font-size: 0.8rem;color: #999">暂无商品</p>
        </div>
    <?php } else { ?>
        <ul class="goods_box">
            <ul class="dynamic_detail" id="goods_wrap">
                <li class="goods_item"></li>
            </ul>
        </ul>

        <script>
            seajs.use('/static/wap/js-dev/app/shop/shop.js', function (api) {
                api.shop(<?php echo $item['id']?>);
            });
        </script>
    <?php } ?>
</div>
<div id="gallery" class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="pswp__bg"></div>

    <div class="pswp__scroll-wrap">

        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <div class="pswp__counter" style="font-size:0.625rem;font-weight: bold"></div>

                <!--<button class="pswp__button pswp__button--close" title="Close (Esc)"></button>-->

                <button class="pswp__button pswp__button--share" title="Share"></button>

                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- <div class="pswp__loading-indicator"><div class="pswp__loading-indicator__line"></div></div> -->

            <!--<div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip">
                     <a href="#" class="pswp__share--facebook"></a>
                    <a href="#" class="pswp__share--twitter"></a>
                    <a href="#" class="pswp__share--pinterest"></a>
                    <a href="#" download class="pswp__share--download"></a>
                </div>
            </div>-->

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
            <div class="pswp__caption">
                <div class="pswp__caption__center">
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    APPCommon.setParams("type=shop&shop_id=<?php echo $item['id']?>&uid=<?php echo $item['user_id']?>")
    seajs.use(['app/ps.init.js?v=1.1.0'], function (ps) {
        $(function () {
            ps.init();
        });
    });
</script>


