<style>
    .sort-nav {
        padding: 10px;
        border: 1px solid #DEEFFB
    }

    .sort-nav span {
        padding: 8px;
        border: 1px solid #d0dbe7;
        color: #428bca;
        background-color: #f0f0f0;
        cursor: pointer;
    }

    .sort-nav span.active {
        background: #4cb329;
        border-color: #4cb329;
        color: #fff;
    }
</style>
<form action="" method="get" style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px;">
    <label for="name">用户id</label>
    <input name="user_id" type="text" id="user_id" value="<?php echo $this->request->get('user_id'); ?>">
    <input type="submit" class="btn btn-primary btn-sm" value="搜索">
</form>

<table id="article-list" class=' list'>
    <thead>
    <tr class="head">
        <th style='width:36px'>ID</th>
        <!--      <th style='width:36px'>批量</th>-->
        <th style='width: 50px;'>用户头像</th>
        <th style='width: 50px;'>用户ID</th>
        <th style='width: 100px;'>用户昵称</th>


        <th style='width:100px' class="arrow" data-sort="" data-order="history">
            <span class="text">历史龙币值</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
        </th>
        <th style='width:100px' class="arrow" data-sort="" data-order="available">
            <span class="text">当前可用龙币值</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
        </th>
        <th style='width:100px' class="arrow" data-sort="" data-order="frozen">
            <span class="text">冻结龙币值</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
        </th>
        <th style='width:80px'>开户时间</th>

        <th style='width:100px'>操作</th>
        <!-- <th style='width:50px'>操作</th>-->
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>
    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">

            <th class='name'><?php echo $item['id']; ?></th>

            <td>
                <img
                    src="<?php echo $users[$item['user_id']]['avatar'] ?>?x-oss-process=image/resize,m_fill,h_160,w_160"
                    width="40"
                    height="40" style="border-radius: 2px"/>
            </td>
            <td>
                <?php echo $item['user_id']; ?>
            </td>
            <td>
                <?php echo $users[$item['user_id']]['username'] ?>
            </td>


            <td class="green bold">
                <?php echo $item['history_count'] ?>
            </td>
            <td class="">
                <?php echo $item['available_count'] ?>
            </td>
            <td class="">
                <?php echo $item['frozen_count'] ?>

            </td>
            <td class="">
                <?php echo date('Y-m-d H:i', $item['created']) ?>
            </td>
            <td class="">
                <a href="javascript:;" data-title="龙币记录【<?php echo $item['user_id'] ?>】"
                   data-href="/panel/coins/records?user_id=<?php echo $item['user_id'] ?>"
                   class='newTarget btn btn-sm btn-primary' data-id="<?php echo $item['id']; ?>"><i
                        class="fa fa-eye"></i> 查看历史记录</a>
            </td>
        </tr>
        <?php
    }
    }
    else {
        ?>
        <tr>
            <td colspan="11">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--   <tr class="showpage">
           <th class="name">操作</th>
           <td colspan="10">
                   <span>
                       [ <a href="javascript:;" class="selectAll">全选</a> ]
                       [ <a href="javascript:;" class="selectNone">全不选</a> ]
                       [ <a href="javascript:;" class="selectInvert">反选</a> ]
                       <a class="btn-light delAllSelected" href="javascript:;">批量删除</a>
                   </span>
           </td>
       </tr>-->
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="<?php if (isset($curCid) && $curCid > 0): ?>11<?php else: ?>10<?php endif; ?>">
            <?php \Util\Pagination::instance($this->view)->display($this->view); ?>
        </td>
    </tr>
</table>
<script src="/static/panel/js/tools/Url.js"></script>

<script>
    var order = '<?php echo $sort ?>'
    var sort_order = '<?php echo $sort_order ?>'
    if (order != '' && sort_order != '') {
        var current = $(".arrow[data-order='" + order + "']");
        current.addClass("active");
        current.attr('data-sort', sort_order);
        if (sort_order == 'desc') {
            current.find('.arrow-down').addClass('active');
            current.find('.arrow-up').addClass('disabled');
        } else {
            current.find('.arrow-down').addClass('disabled');
            current.find('.arrow-up').addClass('active');
        }
    }
    var url = new Url();
    $(".arrow").on('click', function () {
        var order = $(this).attr('data-order');
        var sort = $(this).attr('data-sort');
        sort = sort == 'desc' ? 'asc' : 'desc';
        url.setArgs({order: sort, sort: order, p: 1});
        window.location.href = url.getUrl();
    });
</script>
