<style>
    .form-group {
        min-height: 30px;
        overflow: hidden;
    }

    .form-group input[type='number'] {
        width: 100px;
    }

    .form-group .control-label {
        text-align: right;
    }

    .form-group select {
        margin: 0;
    }

    .disabled {
        background-color: #e4e4e4;
        width: 100%;
        height: 100%;
        overflow: hidden;
    }

    .discuss_recommend_wrap, .share_wrap {
        padding-top: 10px;
        margin-bottom: 10px;
        width: 99%;
    }

    .disabled .form-group input {
        background-color: #f5f5f5;
    }
</style>
<div class="page-header">
    <h1>
        <i class="fa fa-gear"></i> api频控设置
        <small>

        </small>
    </h1>
</div>
<div class="main mainSetting" style="border: 1px solid #e4e4e4;padding: 10px">
    <div class="form-group">
        <div class="col-sm-10">
            开启api频控:
            <input id="enable" type="checkbox" <?php echo $config['enable'] == 1 ? "checked" : '' ?>
                   class="ace ace-switch ace-switch-5"/>
            <span class="lbl"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-10">
            开启ip自动拉黑:
            <input id="black_enable" type="checkbox" <?php echo $config['black_enable'] == 1 ? "checked" : '' ?>
                   class="ace ace-switch ace-switch-5"/>
            <span class="lbl"></span>
        </div>
    </div>
    <div class="form-group black_limit_wrap"
         style="border-bottom: 1px dotted #e4e4e4;padding-bottom: 10px;<?php echo $config['black_enable'] == 1 ? 'display:block' : 'display:none' ?>">
        <div class="col-sm-10">
            超过多少次api频控-ip自动拉黑:
            <input id="black_limit" type="number" min="0" value="<?php echo $config['black_limit'] ?>"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10">
            <span class="btn btn-sm btn-primary btnSetting"><i class="fa fa-paper-plane"></i> 保存设置</span>
        </div>
    </div>
</div>
<table class="list ">
    <thead>
    <tr class="head">
        <th>动作描述</th>
        <th>是否可用</th>
        <th>1分钟内最大调用次数</th>
        <th>1小时内最大调用次数</th>
        <th>24小时内最大调用次数</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody class="listData">
    <?php foreach (\Services\User\Behavior\BehaviorDefine::$name as $k => $name) {
        $item = isset($config['limit'][$k]) ? $config['limit'][$k] : '';

        if ($item) {
            ?>
            <tr class="item item_<?php echo $k ?>" data-key="minute" data-id="<?php echo $k ?>">
                <td><?php echo \Services\User\Behavior\BehaviorDefine::$name[$k] ?></td>
                <td><input id="enable" type="checkbox" <?php echo $item['enable'] == 1 ? "checked" : '' ?>
                           data-id="<?php echo $k ?>"
                           class="ace ace-switch ace-switch-5"/>
                    <span class="lbl"></span></td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>"
                           value="<?php echo !empty($item['m_limit']) ? $item['m_limit'] : '' ?>" class="m_limit">
                </td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>"
                           value="<?php echo !empty($item['h_limit']) ? $item['h_limit'] : '' ?>" class="h_limit">
                </td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>"
                           value="<?php echo !empty($item['d_limit']) ? $item['d_limit'] : '' ?>" class="d_limit">
                </td>
                <td><span class="btn btn-sm btn-success btnSave" data-id="<?php echo $k ?>"><i
                            class="fa fa-paper-plane"></i> 保存</span></td>

            </tr>

        <?php } else { ?>
            <tr class="item item_<?php echo $k ?>" data-key="minute" data-id="<?php echo $k ?>">
                <td><?php echo \Services\User\Behavior\BehaviorDefine::$name[$k] ?></td>
                <td><input id="enable" type="checkbox"
                           data-id="<?php echo $k ?>"
                           class="ace ace-switch ace-switch-5"/>
                    <span class="lbl"></span></td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>" value="" class="m_limit">
                </td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>" value="" class="h_limit">

                </td>
                <td>
                    <input type="number" data-id="<?php echo $k ?>" value="" class="d_limit">
                </td>
                <td><span class="btn btn-sm btn-success btnSave" data-id="<?php echo $k ?>"><i
                            class="fa fa-paper-plane"></i> 保存</span></td>
            </tr>

        <?php } ?>
    <?php } ?>
    <tr class="">
        <th class="name">操作</th>
        <td colspan="13">
            <span class="btn btn-sm btn-success btnSaveAll"><i class="fa fa fa-paper-plane"></i> 全部保存</span>
        </td>
    </tr>
    </tbody>

</table>
<script>
    seajs.use('app/panel/panel.base', function (api) {
        $("#black_enable").on('change', function () {
            if ($(this).prop('checked') == false) {
                $(".black_limit_wrap").hide();
            } else {
                $(".black_limit_wrap").show();
            }
        });
        //保存设置
        $(".btnSetting").on('click', function () {
            var enable = 0;
            var black_enable = 0;
            var black_limit = $("#black_limit").val();
            if ($(".mainSetting #enable").prop('checked') == true) {
                enable = 1;
            }
            if ($(".mainSetting #black_enable").prop('checked') == true) {
                black_enable = 1;
            } else {
                black_enable = 0;
            }
            data = {
                enable: enable,
                black_enable: black_enable,
                black_limit: black_limit
            };
            api.requestApi('/api/tools/saveIpSetting', {type: 'main', data: data}, function (res) {
                if (res.result == 1) {
                    api.showTip('ok', '修改成功', 1000, function () {
                        window.location.reload();
                    })
                }
            });
        });
        $(".btnSave").on('click', function () {
            var id = $(this).attr('data-id');
            var item = $(".item_" + id);
            var enable = 0;
            var m_limit = item.find(".m_limit").val();
            var h_limit = item.find(".h_limit").val();
            var d_limit = item.find(".d_limit").val();
            if (item.find("#enable").prop('checked') == true) {
                enable = 1;
            }
            data = {
                enable: enable,
                m_limit: m_limit,
                h_limit: h_limit,
                d_limit: d_limit,
                id: id
            };
            api.requestApi('/api/tools/saveIpSetting', {type: 'config', data: data}, function (res) {
                if (res.result == 1) {
                    api.showTip('ok', '修改成功', 1000, function () {
                        window.location.reload();
                    })
                }
            });
        });
        $(".btnSaveAll").on("click", function () {
            var data = [];
            $(".listData .item").each(function () {
                var id = $(this).attr('data-id');
                var item = $(this);
                var enable = 0;
                var m_limit = item.find(".m_limit").val();
                var h_limit = item.find(".h_limit").val();
                var d_limit = item.find(".d_limit").val();
                if (item.find("#enable").prop('checked') == true) {
                    enable = 1;
                }
                tmp = {
                    enable: enable,
                    m_limit: m_limit,
                    h_limit: h_limit,
                    d_limit: d_limit,
                    id: id
                };
                data.push(tmp);
            });
            api.requestApi('/api/tools/saveIpSetting', {type: 'saveAll', data: data}, function (res) {
                if (res.result == 1) {
                    api.showTip('ok', '修改成功', 1000, function () {
                        window.location.reload();
                    })
                }
            });
        })
    });
</script>
