<form action="" method="get"
      style="border: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px;border-radius: 5px;line-height: 50px;">
    <label for="name">IP地址:</label>
    <input name="ip" type="text" style="width: 200px" id="ip" value="<?php echo $ip; ?>">
    <input type="submit" class="btn btn-primary btn-sm" value="搜索">
    <span class="btn btn-inverse btn-sm btnAdd"><i class="fa fa-plus"></i> 添加ip</span>
</form>
<table class="list ">
    <thead>
    <tr class="head">
        <th>ip地址</th>
        <th>加入黑名单时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody class="listData">
    <?php if ($ips) { ?>
        <?php foreach ($ips as $k => $ip) {
            $ip = json_decode($ip, true);
            ?>
            <tr class="item item_<?php echo base64_encode($k) ?>">
                <td><?php echo $k ?></td>
                <td><?php echo date('Y-m-d H:i', $ip['time']) ?></td>
                <td><span class="btn btn-xs btn-primary btnRemove" data-key="<?php echo base64_encode($k) ?>"
                          data-id="<?php echo $k ?>">移除黑名单</span></td>
            </tr>

        <?php } ?>
    <?php } ?>
    </tbody>

</table>
<script>
    seajs.use('app/panel/panel.base', function (api) {
        $(".btnRemove").on('click', function () {
            var ip = $(this).data('id');
            api.requestApi('/api/tools/removeIp', {ip: ip}, function (res) {
                    if (res.result == 1) {
                        api.showTip('ok', "删除成功", 1000, function () {
                            $(".item_" + base64.encode(ip)).remove();
                        })
                    }
                }
            )
        });
        $(".btnAdd").on('click', function () {
            var ip = $("#ip").val();
            if (!ip || !/^((\d){1,3}\.){3}(\d){1,3}$/.test(ip)) {
                api.showTip("err", "请输入正确的ip地址", 1000);
                return;
            }
            api.requestApi('/api/tools/addIp', {ip: ip}, function (res) {
                    if (res.result == 1) {
                        api.showTip('ok', "添加成功", 1000, function () {
                            window.location.reload();
                        })
                    }
                }
            )
        })
    })
</script>