<li style='cursor:pointer;user-select:none'>
    <b>
        <input type='checkbox' <?php echo $item['enable'] == 0 ? 'disabled' : '' ?>
               data-phone='<?php echo $item['phone'] ?>'
               data-username='<?php echo $item['username'] ?>'
               data-avatar='<?php echo $item['avatar'] ?>' data-id='<?php echo $item['id'] ?>'
               class='user chk ace' value='<?php echo $item['id'] ?>'/>
        <span class='lbl'></span>
    </b>
    <img
        src='<?php echo $item['avatar'] ?>?x-oss-process=image/resize,m_fill,h_100,w_100'/>  <?php echo $item['id'] ?>
    【<?php echo $item['username'] ?>】
    <i class='fa <?php echo $item['sex'] == 1 ? 'fa-mars pink' : 'fa-venus blue' ?>'></i>
    <!--    <span class='right'>--><?php //echo $item['created'] ?><!--   </span>-->
</li>