<div>
    <?php var_dump($_COOKIE);
    if (!empty($_COOKIE['klg_UID'])) {
        echo "恐龙谷UId:" . $_COOKIE['klg_UID'] . "=====" . \Util\EasyEncrypt::decode($_COOKIE['klg_UID']);
    }

    ?>
    <p class="cookie"></p>
</div>
<script>
    $(function () {
        $(".cookie").html("恐龙谷UID:" + getCookie('klg_UID'));
    });
    function getCookie(c_name) {
        if (document.cookie.length > 0) {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1) {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start, c_end))
            }
        }
        return ""
    }
</script>