<tr class="item" data-id="<?php echo $item['id']; ?>">
    <td>
        <img style="width: 50px;height: 50px;border-radius: 100%"
             src="<?php echo $item['avatar'] . '?x-oss-process=image/resize,m_fill,h_100,w_100' ?>"/>
        <?php echo $item['username'] ?>
    </td>

    <td>
        <?php echo sprintf('%.2f', $item['money'] / 100) . "元" ?>
        <?php if ($item['best'] == 1) { ?>
            <span class="badge badge-primary">手气最佳</span>
        <?php } ?>
    </td>
    <td><?php echo date('Y-m-d H:i:s', $item['created']); ?></td>
</tr>