<style>
    #imgbox-loading {
        position: absolute;
        top: 0;
        left: 0;
        cursor: pointer;
        display: none;
        z-index: 90;
    }

    #imgbox-loading div {
        background: #FFF;
        width: 100%;
        height: 100%;
    }

    #imgbox-overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        display: none;
        z-index: 80;
    }

    .imgbox-wrap {
        position: absolute;
        top: 0;
        left: 0;
        background: #FFF;
        display: none;
        z-index: 90;
    }

    .imgbox-img {
        padding: 0;
        margin: 0;
        border: none;
        width: 100%;
        height: 100%;
        vertical-align: top;
    }

    .imgbox-title {
        padding-top: 10px;
        font-size: 11px;
        text-align: center;
        font-family: Arial;
        color: #333;
        display: none;
    }

    .imgbox-bg-wrap {
        position: absolute;
        padding: 0;
        margin: 0;
        display: none;
    }

    .imgbox-bg {
        position: absolute;
        width: 20px;
        height: 20px;
    }

    img {
        background-color: #fff;
    }

</style>
<div class="page-header">
    <h1>音乐分类列表
        <span class="pull-right">
          <!--  <span class="btn-group">-->
               <span class="btn btn-primary btn-sm btnAdd"><i class="fa fa-plus"></i> 添加分类</span>
            <!--            </span>
            -->        </span>
    </h1>
    <!-- /.col-lg-12 -->
</div>
<table id="article-list" class='list' style="width: 80%">
    <thead>
    <tr class="head">
        <!-- <th style='width:36px'>标签ID</th>-->
        <th style='width:100px'>分类名称</th>
        <th style='width:120px'>排序大小 <a href="javascript:;" class="fa fa-question-circle blue tooltip-info"
                                        data-rel="tooltip"
                                        data-placement="top" data-original-title="越小显示越靠前"></a></th>
        <th style='width:100px'>小图标</th>
        <th style='width:150px'>状态</th>
        <th style='width:150px'>歌曲数量</th>
        <th>操作</th>
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>
    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">
            <!-- <th class='name'><?php /*echo $item['id']; */ ?></th>-->
            <th class='name'><?php echo $item['name']; ?></th>
            <td>
                <?php echo $item['sort_num'] ?>
            </td>
            <td><?php if ($item['icon']) { ?><a data-lightbox="roadtrip" href="<?php echo $item['icon'] ?>"><img
                        width="50"
                        height="50"
                        src="<?php echo $item['icon'] ?>"/>
                    </a><?php } ?>
            </td>
            <td><?php echo $item['enable'] == 1 ? '正常' : '禁用' ?></td>
            <td>
                <?php if ($item['music_count'] > 0) { ?>
                   <a href="javascript:;" data-title="歌曲列表-<?php echo $item['id'] ?>" data-href="/panel/music/list?cat_id=<?php echo $item['id'] ?>" class="newTarget"> <?php echo $item['music_count'] ?></a>
                <?php } else { ?>
                    <?php echo $item['music_count']  ?>
                <?php } ?>
            </td>

            <td>
                <a href="JavaScript:;"
                   data-id="<?php echo $item['id']; ?>"
                   data-name="<?php echo $item['name']; ?>"
                   data-enable="<?php echo $item['enable']; ?>"
                   data-sort_num="<?php echo $item['sort_num']; ?>"
                   data-thumb="<?php echo $item['icon']; ?>"
                   class="btn btn-primary btn-sm editBtn"><i class="fa fa-edit"></i> 编辑</a>
                <?php if ($item['enable'] == 1) { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-danger btn-sm lockBtn"><i class="fa fa-remove"></i> 禁用</a>
                <?php } else { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-purple btn-sm unLockBtn"><i class="fa fa-check"></i> 取消禁用</a>
                <?php } ?>
            </td>
        </tr>
        <?php
    }
    } else {
        ?>
        <tr>
            <td colspan="9">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--  <tr class="showpage">
          <th class="name">操作</th>
          <td colspan="13">
                  <span>
                      [ <a href="javascript:;" class="selectAll">全选</a> ]
                      [ <a href="javascript:;" class="selectNone">全不选</a> ]
                      [ <a href="javascript:;" class="selectInvert">反选</a> ]
                      <a class="btn-light delAllSelected" href="javascript:;">批量屏蔽</a>
                  </span>
          </td>
      </tr>-->
    <tr class="showpage">
        <th class="name">操作</th>
        <td colspan="13">
            <span class="btn btn-xs btn-inverse btnAdd"><i class="fa fa fa-plus"></i> 添加分类</span>
        </td>
    </tr>
</table>
<div class="modal fade" id="catModal">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">分类编辑</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-2 control-label">分类名称:</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name"
                                   placeholder="标签名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-2 control-label">排序:</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="sort_num" placeholder="排序越小越靠前">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-2 control-label">封面图：</label>
                        <div class="col-sm-10">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="thumb" id="thumb" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon" id="upTagThumb" href="javascript:;">选择图片</a>
                                </div>
                            </div>
                    <span class="col-xs-4 pic-review" id="picReviewer" data-list-item-id="12">
                        <img src=""
                             class="preview-thumb"
                             style="height: 32px;" title="选择图片">
                        <label class="help-block with-errors"></label>
                    </span>
                        </div>
                    </div>
                    <div class="form-group submit_yunpian">
                        <label for="ruleName" class="col-sm-2 control-label">可用:</label>
                        <div class="col-sm-10">
                            <input id="enable" type="checkbox"
                                   class="ace ace-switch ace-switch-5"/>
                            <span class="lbl"></span>
                        </div>

                    </div>
                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <input type="hidden" value="0" id="cat_id"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<link rel="stylesheet" href="/srv/static/panel/css/lightbox/lightbox.css"/>

<script src="/srv/static/panel/js/jquery/lightbox/lightbox.js"></script>

<script type="text/javascript">

    $('[data-rel=tooltip]').tooltip();
    seajs.use('app/panel/music/music.category.js?v=1.1', function (api) {
        api.edit();
    });
    $(document).ready(function () {
        lightbox.option({
            albumLabel: '%1/%2',
            'resizeDuration': 200,
            "fadeDuration": 0,
            "imageFadeDuration": 0
        });
    })

</script>


