<?php
//③、在支持成功回调通知中处理成功之后的事宜，见 notify.php
/**
 * 注意：
 * 1、当你的回调地址不可访问的时候，回调通知会失败，可以通过查询订单来确认支付是否成功
 * 2、jsapi支付时需要填入用户openid，WxPay.JsApiPay.php中有获取openid流程 （文档可以参考微信公众平台“网页授权接口”，
 * 参考http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html）
 */
?>

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>微信公众号安全支付</title>
    <script type="text/javascript">
        //调用微信JS api 支付
        function jsApiCall() {
            WeixinJSBridge.invoke(
                'getBrandWCPayRequest',
                <?php echo $jsApiParameters; ?>,
                function (res) {
                    if (res.err_msg && res.err_msg == "get_brand_wcpay_request:ok") {
                        alert("支付成功，即将跳转到订单页");
                        setTimeout(function () {
                            window.location.href = '<?php echo $uri->appUrl()?>order/detail/<?php echo $order_number; ?>';
                        }, 2000);
                    }
                    else if(res.err_msg == "get_brand_wxpay_request:cancel") {
                        alert("您选择取消支付，这样将影响到您购买的商品发货，请及时支付！");
                    }
                    else {
                        alert("支付失败，请跟客服联系，或者选择其他支付方式！微信支付返回信息：" + res.err_msg);
                        history.back();
                    }
                }
            );
        }

        function callpay() {
            if (typeof WeixinJSBridge == "undefined") {
                if (document.addEventListener) {
                    document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
                } else if (document.attachEvent) {
                    document.attachEvent('WeixinJSBridgeReady', jsApiCall);
                    document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
                }
            } else {
                jsApiCall();
            }
        }
        //获取共享地址
        /*function editAddress() {
            WeixinJSBridge.invoke(
                'editAddress',
                <?php //echo $editAddress; ?>,
                function (res) {
                    if(res.err_msg) {
                        alert("您没有使用共享的收货地址");
                    }
                    else {
                        var value1 = res.proviceFirstStageName;
                        var value2 = res.addressCitySecondStageName;
                        var value3 = res.addressCountiesThirdStageName;
                        var value4 = res.addressDetailInfo;
                        var tel = res.telNumber;

                        alert("您选择的地址为：" + value1 + value2 + value3 + value4 + ":" + tel);
                    }
                }
            );
        }*/

        /*window.onload = function () {
            if (typeof WeixinJSBridge == "undefined") {
                if (document.addEventListener) {
                    document.addEventListener('WeixinJSBridgeReady', editAddress, false);
                } else if (document.attachEvent) {
                    document.attachEvent('WeixinJSBridgeReady', editAddress);
                    document.attachEvent('onWeixinJSBridgeReady', editAddress);
                }
            } else {
                editAddress();
            }
        };*/

    </script>
</head>
<body>
<br/>
<?php if($hasError):?>
    <div style="display: block; width: 300px; color: #9ACD32; margin: 30px auto;"><b>请求发生错误：<span style="color:#f00;"><?php echo $errorMessage?></span></b></div>
<?php else:?>
<div style="display: block; width: 300px; color: #9ACD32; margin: 30px auto;"><b>该笔订单支付金额为￥<span style="color:#f00;font-size:50px"><?php echo $shop_order->paid_cash?></span>元</b></div>
<div align="center">
    <button
        style="width:210px; height:50px; border-radius: 15px;background-color:#FE6714; border:0px #FE6714 solid; cursor: pointer;  color:white;  font-size:16px;"
        type="button" onclick="callpay()">立即支付
    </button>
</div>
<?php endif;?>
</body>
</html>