<?php
//    问题进度进度
    $status = [
            1 => '等待回答',
            2 => '已回答',
            3 => '超时退款',
            4 => '视频已删除',
    ];
?>

<link rel="stylesheet" href="/static/wap/css/layer.css">
<script type="text/javascript" src="/static/wap/js/app/layer.js"></script>
<script type="text/javascript" src="/static/panel/js/tools/clipboard/clipboard.min.js"></script>
<div class="" style="padding:20px 10px 10px 10px;">
    <form action="" method="get">
        <select name="user_type" id="" style="height:30px">
            <option value="uid" <?php if( $user_type == 'uid') echo 'selected' ?> >提问者</option>
            <option value="to_uid" <?php if( $user_type == 'to_uid') echo 'selected' ?> >被提问者</option>
        </select>
        <input type="text" name="user_id" placeholder="请输入用户ID" value="{{user_id}}">
        <label for="" style="margin: 0 10px" >
            问题状态：
            <select name="status" id="" style="height:29px">
                <option value=0 <?php if( $status_back == 0) echo 'selected' ?>>--请选择--</option>
                <option value=1 <?php if( $status_back == 1) echo 'selected' ?>>未回答</option>
                <option value=2 <?php if( $status_back == 2) echo 'selected' ?>>已回答</option>
                <option value=3 <?php if( $status_back == 3) echo 'selected' ?>>超时退款</option>
                <option value=4 <?php if( $status_back == 4) echo 'selected' ?>>视频删除</option>
            </select>
        </label>
        <input type="submit" class="btn btn-primary btn-sm" value="搜索" style="padding:1px 9px">
    </form>

</div>
<hr class="hr-10">
<div class="col-xs-12">
    <table id="article-list" class=' list'>
        <thead>
        <tr class="head">
            <th style="width: 70px" class="center">QID</th>
            <th style='width:30%' class="center">用户</th>
            <!--<th style='width:10%' class="center">提问对象</th>-->
            <th style='width:270px' class="center">问题</th>
            <th style='width:' class="center">红包金额(元)</th>

            <th style='width:5%' class="center">视频</th>
            <th style='width:' class="center">进度</th>
            <th style='width:' class="center">支付流水号</th>
            <th style='width:' class="center">提问时间</th>
            <!--<th style='width:' class="center">问题状态</th>-->
            <th style="width:" class="center">操作</th>
        </tr>
        </thead>
            <?php
            if ($qList) {
            ?>

            <tbody class="listData">
            <?php

            foreach ($qList as $k => $item) {

                ?>
                <tr class="item" data-key="<?php echo $k?>">


                    <td class="center">
                        <?php echo $item['id']; ?>
                    </td>
                    <td style="vertical-align: middle;">
                        <div style="float:left">
                            <img class="pull-left" alt="" src="<?php echo json_decode($item['user_info_ask'],true)['avatar']?>?x-oss-process=image/resize,m_fill,h_200,w_200" style="border: 2px solid #c9d6e5;border-radius: 100%;max-width: 40px;margin-right: 10px;margin-left: 0;box-shadow: none;">
                            <span style="height:41px;line-height:41px;">
                                <a href="javascript:;" data-href="/panel/users/detail/?user_id=<?php echo $item['uid']?>" title="<?php echo $item['uid']?>" data-id="user_detail_<?php echo $item['uid']?>" data-title="用户详情" class="newTarget" target="_blank" title="查看用户详情" style="color:deeppink"><?php echo json_decode($item['user_info_ask'],true)['username']?></a>
                            </span>
                        </div>
                    <div style="float:left;vertical-align: middle;height:50px;padding:10px 20px">
                        <span class="label  label-danger arrowed-right arrowed-in" style="width:50px;">
                            问
                        </span>
                    </div>
                        <div style="float:left">
                        <img class="pull-left" alt="" src="<?php echo json_decode($item['user_info_answer'],true)['avatar']?>?x-oss-process=image/resize,m_fill,h_200,w_200" style="border: 2px solid #c9d6e5;border-radius: 100%;max-width: 40px;margin-right: 10px;margin-left: 0;box-shadow: none;">
                        <span style="height:41px;line-height:41px;">
                            <a href="javascript:;" data-href="/panel/users/detail/?user_id=<?php echo $item['to_uid']?>" title="<?php echo $item['to_uid']?>" data-id="user_detail_<?php echo $item['to_uid']?>" data-title="用户详情" class="newTarget" target="_blank" title="查看用户详情" style="color:deeppink"><?php echo json_decode($item['user_info_answer'],true)['username']?></a>
                        </span>
                        </div>
                    </td>
                    <td class="">
                        <?php
                            echo mb_substr($item['question'],0,10,'utf-8');
                            if( mb_strlen($item['question']) > 10 )
                                echo "...";
                        ?>
                        <i href="javascript:;" class="fa fa-commenting-o blue tooltip-info pull-right" data-rel="tooltip" data-placement="top" data-original-title="<?php echo $item['question']?>"></i>

                    </td>
                    <td class="center ">
                       <span class="red" style="font-weight:bold"><?php echo sprintf("%.2f",$item['money'] / 100) ?></span>
                    </td>

                    <td class="center">
                        <?php
                            if( $item['status'] == 2)
                            {
                                $video = json_decode($item['video_info'],true);
                                $link = explode('?',$video['url']);

                        ?>
                        <a href="javascript:;" data-video-src="<?php echo $link[1]?>"  class="video">查看视频</a>
                                <?php }?>
                    </td>
                    <td class="center">
                        <?php $color = [
                                1 => 'label-warning',
                                2 => 'label-success',
                                3 => '',
                                4 => 'label-danger',
                        ]?>
                        <span class="label  <?php echo $color[$item['status']]?> arrowed-right arrowed-in">
                            <?php
                                echo $status[$item['status']]
                            ?>
                        </span>
                    </td>
                    <td class="center">

                        <input  id="<?php echo $item['pay_id']?>" class="copy btn btn-xs" type="button" data-clipboard-text="<?php echo $item['pay_id']?>" data-title="Copied" data-placement="right" data-trigger="manual" value="复制">
                    </td>
                    <td class="center">
                        <span><?php echo date("Y/m/d H:i:s",$item['created']); ?></span>
                    </td>
                    <!--<td class="center">
                        <?php /*if( $item['enable'] == 1 ){*/?>
                            <span class="badge badge-success">正常</span>
                        <?php /*}else{*/?>
                            <span class="badge badge-danger">已删除</span>
                        <?php /*}*/?>
                    </td>-->
                    <td class="center">
                        <?php if($item['status'] == 2) :?>
                        <a href="javascript:;" data-href="/panel/show/video?video_id={{video['vid']}}"  data-id="user_detail_50030" data-title="视频列表" class="newTarget" target="_blank" >
                            管理
                        </a>
                        <?php endif; ?>

                    </td>
                </tr>
                <?php
            }
            } else {
                ?>
                <tr>
                    <td colspan="10">
                        <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
                    </td>
                </tr>
            <?php } ?>

            </tbody>
        <tr class="showpage">
            <th>页码</th>
            <td colspan="10">
                <span>
                    <?php \Util\Pagination::instance($this->view)->display($this->view)?>
                </span>
            </td>
        </tr>
    </table>

</div>
<script>
    $(function () {

        $('.video').on('click', function(){
            var _this = this;
            var video_src = $(_this).data('video-src');
            var loadStr='<video ' +
                'width="100%" ' +
                'height="100%"  ' +
                'controls="controls" ' +
                'autobuffer="autobuffer"  ' +
                'autoplay="autoplay" ' +
                'loop="loop" ' +
                'style="max-height:70%">' +
                '<source src="' + video_src + '" type="video/mp4">' +
                '</source></video>'
            layer.open({
                type:2,
                title: false,
                area: ['630px', '360px'],
                shade: 0.8,
                closeBtn: 0,
                content: loadStr,
                success:function(){
                    $('.layui-m-layercont').find('i').remove();
                }
            });
        });
        $('[data-rel="tooltip"]').tooltip();
    });
    seajs.use('app/panel/panel.base');
    var clipboard = new Clipboard('.copy',{});
    clipboard.on('success',function (e) {
        var sel = "#"+e.text;
        $(sel).tooltip('show');
        setTimeout(function(){
            $(sel).tooltip('hide');
        },1500);
    });
    

</script>