<div class="page-header">
    <h1>资料设置</h1>
</div>

{{ content() }}

{{ form('developer/setting/index', 'id': 'registerForm', 'class': 'form-horizontal', 'onbeforesubmit': 'return false', 'data-toggle':"validator", 'role':'form') }}
<fieldset class="col-sm-5">
    <!--  <legend>账号信息</legend>-->
    <div class="form-group">
        <label class="col-sm-2 control-label">登陆账号</label>

        <div class="col-sm-10">
            <p class="form-control-static">{{admin.account}}</p>
        </div>
    </div>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">用户姓名</label>

        <div class="col-sm-10">
    <span class="col-sm-5">
        <input type="text" class="form-control" id="name" name="name" placeholder="用户姓名" value="{{admin.name}}"
               required data-error="用户姓名">
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">App账号</label>

        <div class="col-sm-10">
    <span class="col-sm-5">
        <input type="text" class="form-control" id="app_uid" name="app_uid" placeholder="App账号"
               value="<?php echo $admin->app_uid == 0 ? '' : $admin->app_uid; ?>"
               data-error="App账号">
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="contact" class="col-sm-2 control-label">角色权限</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <?php
                echo $admin->group_name;
                ?>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"></label>
    <span style="margin: 0 0 0 24px;">
    {{ submit_button('保存', 'class': 'btn btn-primary btn-sm') }}
    </span>
    </div>
</fieldset>

{{end_form()}}