<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于我们 - 恐龙谷</title>
    <meta name="keywords" content="恐龙谷,恐龙谷app,美女交友app,娱乐自媒体平台,聊天交友,知识问答软件,社交聊天软件,交友软件,视频红包,同城交友,手机交友,视频社交,android,iphone" />
    <meta name="description" content="恐龙谷社交软件app开启附近圈子社交新时代，红包广场全面开启，精彩就在附近，全民开店，视频红包依旧惊喜不断，更有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！年轻人都喜欢的娱乐自媒体社交应用平台！" />
    <link rel="stylesheet" href="/static/home/css/swiper.css">
    <link rel="stylesheet" href="/static/home/css/animate.css">
    <link rel="stylesheet" href="/static/home/css/base.css?v=1.02">
    <link rel="stylesheet" href="/static/home/css/about.css?v=1.01">
</head>
<style>
    .swiper-slide{
        background-color:#f5f5f5;
    }
    .product_body h4{
        font-size:20px;
        color:#ffa800;
    }
    .product_body p{
        font-size:14px;
        color:#333;
        padding-left:0
    }
</style>
<body style="position: relative;" >
<!-- 头部导航 -->
<div class="nav" style="background-color: #FFA800">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li >
                    <a href="index" class="active">
                        首页
                    </a>
                    <span class=""></span>
                    <b></b>
                </li>

                <li class="line-two">
                    <a href="/dynamic" class="active ">恐龙谷动态</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于我们</a>
                    <span class="active navin"></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/service" class="active">特色服务</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/guide" class="active">用户帮助</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                    <b></b>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="swiper-container swiper-container-vertical">
    <div class="swiper-wrapper">
        <div class="swiper-slide swiper-slide-active about-one">
            <!-- 内容模块 -->
            <div class="container mt64">
                <h4 class="top-title">公司介绍</h4>
                <div class="content-block pr">
                    <img src="/static/home/images/v2/pic_p1.png" alt="" class="bigpic">
                    <div class="desc pa" style="background-color: #FFA800">
                        <h3>恐龙谷网络科技有限公司</h3>
                        <span class="line"></span>
                        <p>
                            恐龙谷全新版本打造娱乐自媒体社交新时代，红包广场全面开启，广告曝光更加给力；申请开店并成为恐龙谷合伙人，合作共赢将人脉变钱脉共享平台收益；以社交为核心，真正实现了社交引流，电商变现的创新型商业模式。还有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！</p>
                        <p class="p-two">
                            深圳市恐龙谷网络科技有限公司成立于2014年，坚持以“和谐、积极、乐观、进取”的团队理念发展。恐龙谷的愿景是希望更多的人通过移动互联网，发现身边美好的人和事，享受分享带来的乐趣.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-slide swiper-slide-next about-there">
            <div class="container mt64">
                <h4 class="top-title">产品介绍</h4>

                <div style="background-color: white;padding:50px 85px 50px 85px;">
                    <div style="float:left;width:45%">
                        <div class="product_body">
                            <h4 style="">特色功能</h4>
                            <p>
                                恐龙谷全新版本打造娱乐自媒体社交新时代，全民开店、全民合伙，附近商圈，多样化的推广方式助力“社交引流，电商变现”，还可以参与红包游戏，赢取现金奖励。</p>
                        </div>
    
                        <div class="product_body">
                            <h4>注册流程</h4>
                            <p>用户只能通过没有注册过的手机号码注册成为恐龙谷用户，一个手机号码只能注册一个恐龙谷账号。</p>
                            <p>1、打开恐龙谷社交APP客户端-选择手机号注册-获取验证码-完成注册</p>
                            <p>2、上传个性头像、选择个性标签、选择生日、性别等基本信息</p>
                            <p>3、完善个人资料</p>
                            <p>4、开启畅聊体验以及丰富的红包玩法</p>
    
                        </div>
    
                        <div class="product_body">
                            <h4 style="">软件版本</h4>
                            <p>最新版本：2.2.4402 <br>
                            <p>更新时间：2018年3月9日 <br>
                            <p>系统要求：需要Android 4.3以上</p>
                        </div>
                    </div>
                    <div style="float:right">
                        <img src="/static/home/images/v3/icon_shouji_cpjs.png" alt="">
                    </div>
                    <div class="clearfix"></div>
                </div>
                
            </div>
        </div>
        <div class="swiper-slide swiper-slide-next about-two">

            <!-- 内容模块 -->
            <div class="container mt64">
                <h4 class="top-title">团队风采</h4>
                <div class="team pr">
                    <div class="team-top clearfix">
                        <div class="team-top-left fl">
                            <div class="top-list clearfix">
                                <div class="zoom fl pr" data-type="0">
                                    <img src="/static/home/images/pic1_samll.jpg" alt="" class="sm-pic">
                                    <img src="" alt="" class="big-pic">
                                </div>
                                <div class="zoom fl pr" data-type="0">
                                    <img src="/static/home/images/pic2_samll.jpg" alt="" class="sm-pic">
                                    <img src="" alt="" class="big-pic">
                                </div>
                            </div>
                            <div class="bottom-list clearfix">
                                <div class="zoom fl w-one pr" data-type="0">
                                    <img src="/static/home/images/pic4_samll.jpg" alt="" class="sm-pic">
                                    <img src="" alt="" class="big-pic">
                                </div>
                                <div class="zoom fl w-two pr" data-type="0">
                                    <img src="/static/home/images/pic5_samll.jpg" alt="" class="sm-pic">
                                    <img src="" alt="" class="big-pic">
                                </div>
                            </div>
                        </div>
                        <div class="team-top-right fl">
                            <div class="zoom h-one pr" data-type="0">
                                <img src="/static/home/images/pic3_samll.jpg" alt="" class="sm-pic">
                                <img src="" alt="" class="big-pic">
                            </div>
                            <div class="zoom h-two pr" data-type="0">
                                <img src="/static/home/images/pic6_samll.jpg" alt="" class="sm-pic">
                                <img src="" alt="" class="big-pic">
                            </div>
                        </div>
                    </div>
                    <div class="team-bottom">
                        <div class="zoom fl pr" data-type="1">
                            <img src="/static/home/images/pic7_samll.jpg" alt="" class="sm-pic">
                            <img src="" alt="" class="big-pic">
                        </div>
                        <div class="zoom fl pr" data-type="1">
                            <img src="/static/home/images/pic8_samll.jpg" alt="" class="sm-pic">
                            <img src="" alt="" class="big-pic">
                        </div>
                        <div class="zoom fl pr" data-type="1">
                            <img src="/static/home/images/pic9_samll.jpg" alt="" class="sm-pic">
                            <img src="" alt="" class="big-pic">
                        </div>
                        <div class="zoom fl pr" data-type="1">
                            <img src="/static/home/images/pic10_samll.jpg" alt="" class="sm-pic">
                            <img src="" alt="" class="big-pic">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-slide swiper-slide-next about-there">

            <div class="container mt64">
                <h4 class="top-title">联系我们</h4>
                <div class="map pr">
                    <div style="width:1200px;height:620px;border:#ccc solid 1px;font-size:12px" id="map"></div>
                    <div class="pa address-detail" style="background-color: #FFA800">
                        <h3>公司地址</h3>
                        <span class="line"></span>
                        <p>地址：深圳市南山区粤海街道大冲国际中心5号楼5层</p>
                        <p class="youb">邮编地址:518055</p>
                        <h3 class="peo-kf">客服帮助</h3>
                        <span class="line"></span>
                        <p>为及时解决您的问题，建议您通过提交意见反馈，我们会尽快在24小时内受理您的问题</p>
                        <p class="tel">客户热线：0755-26418647(服务时间9:00-18:00)</p>
                        <p>
                            邮件：konglonggu@hot.com
                        </p>
                    </div>
                </div>
            </div>

            <style>
                .footer ul li{
                    display:inline-block;
                }
            </style>
            <div class="footer" style="position:absolute;bottom:0">
                <div style="margin-bottom:6px">
                    <ul>
                        <li><a href="/about">关于恐龙谷</a></li>
                        |
                        <li><a href="/service">特色服务</a></li>
                        |
                        <li><a href="/dynamic">恐龙谷动态</a></li>
                        |
                        <li><a href="/agreement">用户协议</a></li>
                        |
                        <li><a href="/guide">用户帮助</a></li>
                    </ul>
                </div>
                Copyright © 恐龙谷 All Rights Reserved 深圳市恐龙谷网络科技有限公司版权所有
                <a href="http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action">粤ICP备15089260号-2</a>
            </div>

        </div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets">
        <span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>
        <span class="swiper-pagination-bullet"></span>
        <span class="swiper-pagination-bullet"></span>
    </div>
</div>
<script src="/static/home/js/swiper.min.js"></script>
<script src="/static/home/js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=7vlTrukbPjljTlbguBwgBetkqrGa7NRP"></script>
<script>
    $(function () {
        /*$(".nav-list ul li").hover(function(){
         $(".nav-list ul li span").removeClass("navout");
         $(this).find("span").addClass("navin");
         },function(){
         $(".nav-list ul li span").removeClass("navin");
         $(this).find("span").addClass("navout");
         });*/
        var thisImg, currentImg;
        $(".zoom").mouseenter(function () {
            thisImg = $(this);
            var type = $(this).data("type");
            if (type == 0) {
                var topL = 0;
            } else {
                var topL = 210;
            }
            var topNum = $(this).offset().top - $(this).parent().offset().top;
            var leftNum = $(this).offset().left;
            var src = $(this).children("img").attr("src").replace("samll", "big");
            currentImg = $(this).children(".big-pic");
            currentImg.mouseleave(function () {
                currentImg.removeClass("anim");
                currentImg.addClass("anim_reverse");
            });
            if (currentImg.attr("src") == "") {
                currentImg.attr("src", "");
                currentImg.attr("src", src);
            }
            currentImg.css("top", -($(this).children("img").height() / 2 - $(this).children("img").height() / 2 + topL));

            currentImg.css("left", -(currentImg.width() / 2 - $(this).children("img").width() / 2));
            currentImg.removeClass("anim_reverse");
            currentImg.addClass("anim");
            currentImg.show();
        });
        $(".team").mouseleave(function () {
            currentImg.removeClass("anim");
            currentImg.addClass("anim_reverse");
        });
        //创建和初始化地图函数：
        function initMap() {
            createMap();//创建地图
            setMapEvent();//设置地图事件
            addMapControl();//向地图添加控件
            addMapOverlay();//向地图添加覆盖物
        }

        function createMap() {
            map = new BMap.Map("map");
            map.centerAndZoom(new BMap.Point(113.961149, 22.54854), 18);
        }

        function setMapEvent() {
            map.enableScrollWheelZoom();
            map.enableKeyboard();
            map.enableDragging();
            map.enableDoubleClickZoom()
        }

        function addClickHandler(target, window) {
            target.addEventListener("click", function () {
                target.openInfoWindow(window);
            });
        }

        function addMapOverlay() {
            var markers = [
                {
                    content: "欢迎光临",
                    title: "深圳市恐龙谷网络科技有限公司",
                    imageOffset: {width: 0, height: 3},
                    position: {lat: 22.548339, lng: 113.95999}
                }
            ];
            for (var index = 0; index < markers.length; index++) {
                var point = new BMap.Point(markers[index].position.lng, markers[index].position.lat);
                var marker = new BMap.Marker(point, {
                    icon: new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png", new BMap.Size(20, 25), {
                        imageOffset: new BMap.Size(markers[index].imageOffset.width, markers[index].imageOffset.height)
                    })
                });
                var label = new BMap.Label(markers[index].title, {offset: new BMap.Size(25, 5)});
                var opts = {
                    width: 200,
                    title: markers[index].title,
                    enableMessage: false
                };
                var infoWindow = new BMap.InfoWindow(markers[index].content, opts);
                marker.setLabel(label);
                addClickHandler(marker, infoWindow);
                map.addOverlay(marker);
            }
            ;
        }

        //向地图添加控件
        function addMapControl() {
            var scaleControl = new BMap.ScaleControl({anchor: BMAP_ANCHOR_BOTTOM_LEFT});
            scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
            map.addControl(scaleControl);
            var navControl = new BMap.NavigationControl({
                anchor: BMAP_ANCHOR_TOP_LEFT,
                type: BMAP_NAVIGATION_CONTROL_LARGE
            });
            map.addControl(navControl);
            var overviewControl = new BMap.OverviewMapControl({anchor: BMAP_ANCHOR_BOTTOM_RIGHT, isOpen: true});
            map.addControl(overviewControl);
        }

        var map;
        initMap();
    })
</script>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        direction: 'vertical',
        mousewheelControl: true,
        parallax: true
    });
</script>
</body>
</html>