<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户帮助 - 恐龙谷</title>
    <meta name="keywords" content="恐龙谷,恐龙谷app,美女交友app,娱乐自媒体平台,聊天交友,知识问答软件,社交聊天软件,交友软件,视频红包,同城交友,手机交友,视频社交,android,iphone" />
    <meta name="description" content="恐龙谷社交软件app开启附近圈子社交新时代，红包广场全面开启，精彩就在附近，全民开店，视频红包依旧惊喜不断，更有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！年轻人都喜欢的娱乐自媒体社交应用平台！" />
    <link rel="shortcut icon" href="/static/home/images/favicon.ico"/>
    <link rel="stylesheet" href="/static/home/css/animate.css">
    <link rel="stylesheet" href="/static/home/css/base.css?v=1.02">
    <link rel="stylesheet" href="/static/home/css/media.css">
    <script src="/static/home/js/jquery-2.1.4.min.js"></script>
    <script>
        if ( !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/) ) {
            window.location.href = "http://wap.klgwl.com/Downloads/share"
        }
    </script>
    <style>
        .help-menu{
            float:left;
            /*padding-top: 41px;*/
            padding-left:119px;
            padding-right:42px;
            width:350px;
            border-right:2px solid #E1E1E1;
            margin-top:40px;
            position:relative;
        }
        .help-menu .arrow{
            display: block;
            position: absolute;
            right: -6px;
            top: 31px;
            width: 10px;
            height: 10px;
            border:solid #E1E1E1;
            border-width: 2px 0 0 2px;
            background-color: #FFF;
            -webkit-box-sizing: content-box;
            -moz-box-sizing: content-box;
            box-sizing: content-box;
            -webkit-transform: rotate(-45deg);
            -ms-transform: rotate(-45deg);
            transform: rotate(-45deg);
        }
        .help-menu ul li{
            position:relative;
            padding-bottom:26px;
            padding-top:26px;
            cursor:pointer;
        }
        .help-menu ul li span{
            padding-left:48px;
            font-size:16px;

        }
        .help-menu ul li img {
            position:absolute;
            top:50%;
            margin-top:-17px;
        }

        .help-menu ul li.active span{
            font-size:18px;
            font-weight:bold;

        }
        .help-right{
            width:850px;
            float:left;
            padding-left:80px;
            padding-right:80px;
            margin-top:40px;
            min-height:400px;
            padding-bottom:30px;
            position:relative;
        }
        .help-right .help-search div{
            cursor: pointer;
        }
        .help-right .help-search input{
            height:36px;
            width:84%;
            border:1px #c4c2c2 solid;
            margin-right:10px;
            position:relative;
            top:-7px;
            padding:13px;
            font-size:14px;
            color:#636363;
        }
        .help-right .help-search div{
            box-sizing: border-box;
            display:inline-block;
            background-color:#ffa800;
            height:36px;
            width:90px;
            text-align: center;
        }
        .help-right .help-search img{
            padding-top:5px;
        }
        .help-right .help-main{
            margin-top:25px;
        }
        .help-right .help-main ul{
            margin-top:15px;
        }
        .help-right .help-main ul li{
            font-size:14px;
            color:#636363;
            line-height:2em;
            cursor: pointer;
        }
        .help-right .help-main .hot-ques,.help-right .help-main .newest-ques{
            float:left;
            width:50%;
        }
        .help-right .help-main .hot-ques ul li,.help-right .help-main .newest-ques ul li{
            list-style: decimal inside;
            overflow:hidden;
            text-overflow:ellipsis;
            white-space:nowrap;
            width:100%;
            cursor: pointer;
        }
        .help-right .help-main h4{
            font-size:18px;
            color:#ffa800;
        }
        .help-right .help-main .go{
            margin-top:15px;
            font-size:14px;
            color:#8a8a8a;
            cursor: pointer;
        }
        .help-right .help-qlist{
            margin-top:25px;
        }
        .help-right .help-qlist ul{
            margin-top:15px;
        }
        .help-right .help-qlist h4 span{
            font-size:18px;
            color:#ffa800;
        }
        .help-right .help-qlist ul li{
            font-size:14px;
            color:#636363;
            line-height:2em;
        }
        .help-right  .help-qlist ul li{
            list-style: decimal inside;
            overflow:hidden;
            text-overflow:ellipsis;
            white-space:nowrap;
            width:100%;
            cursor:pointer;
        }
        .help-right .help-detail{
            margin-top:25px;
        }
        .help-right .help-detail h4 span{
            font-size:16px;
        }
        .help-right .help-detail h4 span:nth-child(2){
            color:#ffa800;
        }
        .help-right .help-detail div{
            margin-top:15px;
            font-size:14px;
            color:#636363;
        }
        .help-right .help-detail div img{
            max-width:100%;
        }
    </style>
</head>
<body>

<!-- 头部导航 -->
<div class="nav" style="background-color: #FFA800">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li >
                    <a href="index" class="active">
                        首页
                    </a>
                    <span class=""></span>
                    <b></b>
                </li>

                <li class="line-two">
                    <a href="/dynamic" class="active ">恐龙谷动态</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于我们</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/service" class="active">特色服务</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/guide" class="active">用户帮助</a>
                    <span class="active navin"></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                    <b></b>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>

</script><div class="container" style="margin-top:64px;/*height:100%;*/padding-bottom:20px;">
    <div style="background-color:white">
        <div class="help-menu">
            <ul>
                <li class="active" data-id="0" data-img-default="/static/home/images/v3/icon_bangzhushouye_default.png" data-img-selected="/static/home/images/v3/icon_bangzhushouye_selected.png">
                    <img src="/static/home/images/v3/icon_bangzhushouye_default.png" alt="" >
                    <span >帮助首页</span>
                </li >
                <li data-id="1" data-img-default="/static/home/images/v3/icon_zuixinwenti_default.png" data-img-selected="/static/home/images/v3/icon_zuixinwenti_selected.png">
                    <img src="/static/home/images/v3/icon_zuixinwenti_default.png" alt="">
                    <span>最新问题</span>
                </li>
                <li data-id="2" data-img-default="/static/home/images/v3/icon_remenwenti_default.png" data-img-selected="/static/home/images/v3/icon_remenwenti_selected.png">
                    <img src="/static/home/images/v3/icon_remenwenti_default.png" alt="">
                    <span>热门问题</span>
                </li>
                <li data-id="3" data-img-default="/static/home/images/v3/icon_zhanghaoanquan_defaultl.png" data-img-selected="/static/home/images/v3/icon_zhanghaoanquan_selected.png">
                    <img src="/static/home/images/v3/icon_zhanghaoanquan_defaultl.png" alt="">
                    <span>账号与账号安全</span>
                </li>
                <li data-id="4" data-img-default="/static/home/images/v3/icon_gongnengjieshao_default.png" data-img-selected="/static/home/images/v3/icon_gongnengjieshao_selected.png">
                    <img src="/static/home/images/v3/icon_gongnengjieshao_default.png" alt="">
                    <span>功能介绍</span>
                </li>
            </ul>
            <div class="arrow"></div>
        </div>
        <div class="help-right">
            <div class="help-search">
                <input type="text" id="kw" placeholder="热门关键词：红包、开店、推广、游戏">
                <div id="search">
                    <img src="/static/home/images/v3/icon_sousuo.png" alt="">
                </div>

            </div>
            <div class="help-main" style="display:none" ><!--帮助首页-->
                <div class="hot-ques">
                    <h4 data-id="2">热门问题</h4>
                    <ul>


                    </ul>
                    <div class="go" >
                        了解更多 >>
                    </div>

                </div>
                <div class="newest-ques">
                    <h4 data-id="1">最新问题</h4>
                    <ul>


                    </ul>
                    <div class="go">
                        了解更多 >>
                    </div>
                </div>
            </div>

            <div class="help-qlist">
                <h4 >
                    <span > </span>
                </h4>

                    <ul>

                    </ul>

            </div>
            <div class="help-detail" style="display:none">
                <h4>
                    <span data-id="1">最新问题 > </span>
                    <span data-id="">怎么发起红包游戏</span>
                </h4>
                <div>
                    
                </div>
            </div>
            <div class="loading" style="position: absolute;top:50%;left:50%;display:none">
                <img src="/srv/static/wap/images/download_v4/loading.gif" alt="" style="margin-left:-16px;margin-top:-16px;">
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="clearfix"></div>
<?php $this->partial("index/v3/partial/footer") ?>
<div style="display:none">
    <ul>
        <li>
            <a href="http://www.klgwl.cn/">恐龙谷</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">美女交友APP</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">娱乐自媒体平台</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">知识问答软件</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">社交聊天软件</a>
        </li>
    </ul>
</div>
</body>
</html>
<script>
    var doc_h = $(document).height();
    var win_h = $(window).height();
    var h = doc_h < win_h ? win_h : doc_h;
    $('body > div.container').height(h);
    //菜单
    var menus =
        {
            1 :'最新问题',
            2 :'热门问题',
            3 :'账号与账号安全',
            4 :'功能介绍'
        };
    var menu_top = $('.help-menu').offset().top;
    var height_li = $('.help-menu li:eq(0)').height();
    $('.help-menu').on('click','li',function(){
        //样式
        var $old = $(this).siblings('.active');
        $old.removeClass('active').find('img').attr('src',$old.data('img-default'));
        $(this).addClass('active').find('img').attr('src',$(this).data('img-selected'));
        console.log($(this).find('span').css('padding-left'));
        $('.help-menu .arrow').css('top',($(this).offset().top - menu_top + height_li + 7));
        //内容
        var _this = this;
        var cid = $(_this).data('id');
        if( cid == 0)
        {
            $('.help-detail').hide();
            $('.help-qlist').hide();
            $('.help-main').fadeIn();
            //首页热门问题
            $.get('api/guide',{type:'list',cid:2},function (res) {
                if( res.result === 1 )
                {
                    var html = "";
                    var i = 0;
                    $.each(res.data,function(k,v){
                        if( i>= 5 )//帮助首页问题数
                            return false;
                        html += "<li data-id=" + v.id + ">" + v.question + "</li>" ;
                        i++;
                    });
                    $('.help-main > div.hot-ques > ul').html(html);
                }
            },'json');
            //首页最新问题
            $.get('api/guide',{type:'list',cid:1},function (res) {
                if( res.result === 1 )
                {
                    var html = "";
                    var i = 0;
                    $.each(res.data,function(k,v){
                        if( i>= 5 )//帮助首页问题数
                            return false;
                        html += "<li data-id=" + v.id + ">" + v.question + "</li>" ;
                        i++;
                    });
                    $('.help-main > div.newest-ques > ul').html(html);
                }
            },'json');
        }else {
            $.get('api/guide',{type:'list',cid:cid},function (res) {
                if( res.result === 1 )
                {
                    $('.help-main').hide();
                    $('.help-detail').hide();
                    $('.help-qlist h4').show();
                    $('.help-qlist').fadeIn();
                    $.get('api/guide',{type:'list',cid:cid},function (res) {
                        if( res.result === 1 )
                        {
                            var html = "";
                            $.each(res.data,function(k,v){
                                html += "<li data-id=" + v.id + ">" + v.question + "</li>" ;
                            });
                            $('.help-qlist > ul').html(html);
                        }
                    },'json');
                    $('.help-qlist h4 span').text($(_this).text()).data('id',cid);

                }
            },'json');
        }

    });
    //首页了解更多
    $('.hot-ques,.newest-ques').on('click','.go',function () {
        var btn = {
            'newest-ques':1,
            'hot-ques':2
        };
        var cls = $(this).parent('div').attr('class');
        $('.help-menu li[data-id=' + btn[cls] + ']').get(0).click();
    });
    //查看问题详情
    $('.hot-ques ul,.newest-ques ul,.help-qlist ul').on('click','li',function () {
        var _this = this;
        var qid = $(_this).data('id');
        showQuesDetail(qid);
    });
    function showQuesDetail(qid){
        $('.help-main,.help-qlist,.help-detail').hide();
        $('.loading').fadeIn();
        $.get('api/guide',{type:'detail',cid:qid},function (res) {
            if( res.result === 1 )
            {
                //去除菜单高亮
                $('.help-menu li').each(function () {
                    if( $(this).hasClass('active') )
                    {
                        $(this).removeClass('active');
                        return false;
                    }
                });
                //当前问题所属分类高亮
                $('.help-menu li[data-id=' + res.data.type + ']').addClass('active');
                //标题
                $('.help-detail h4 span:eq(0)').text(menus[res.data.type] + ' > ');
                $('.help-detail h4 span:eq(1)').text(res.data.question);

                $('.help-detail > div').html(res.data.answer);
                $('.loading').hide();
                $('.help-detail').fadeIn();
                //$('body > div.container').height($('.help-detail > div').height() );

            }
        },'json');
    }
    //搜索
    $('#search').on('click',function(){
        var kw = $('#kw').val();
        $.get('api/guide',{type:'search',kw:kw},function (res) {
            if( res.result === 1 )
            {
                $('.help-qlist h4').hide();
                var html = "";
                $.each(res.data,function(k,v){
                    html += "<li data-id=" + v.id + ">" + v.question + "</li>" ;
                });
                $('.help-main').hide();
                $('.help-detail').hide();
                $('.help-qlist').fadeIn();
                if(html === '')
                    html = '<div style="text-align:center;color:#ffa800">没有搜索到相关问题</div>'
                $('.help-qlist > ul').html(html);
            }
        },'json');
    });
    $('#kw').on('keyup',function (e) {
        if(e.keyCode === 13)
            $('#search').get(0).click()
    });
    //加载帮助首页数据

    var type = GetQueryString('type');
    var id = GetQueryString('cid');
    if( type !== '' && id !== '')
        showQuesDetail(id);
    else
        $('.help-menu li:eq(0)').get(0).click();

    function GetQueryString(name) {
        var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
        var r = window.location.search.substr(1).match(reg);
        var context = "";
        if (r != null)
            context = r[2];
        reg = null;
        r = null;
        return context == null || context == "" || context == "undefined" ? "" : context;
    }
</script>