<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>恐龙谷社交软件官网-娱乐自媒体社交平台_美女交友聊天app知识问答软件</title>
    <meta name="keywords" content="恐龙谷,恐龙谷app,美女交友app,娱乐自媒体平台,聊天交友,知识问答软件,社交聊天软件,交友软件,视频红包,同城交友,手机交友,视频社交,android,iphone" />
    <meta name="description" content="恐龙谷社交软件app开启附近圈子社交新时代，红包广场全面开启，精彩就在附近，全民开店，视频红包依旧惊喜不断，更有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！年轻人都喜欢的娱乐自媒体社交应用平台！" />
    <link rel="shortcut icon" href="/static/home/images/favicon.ico"/>
    <link rel="stylesheet" href="/static/home/css/animate.css">
    <link rel="stylesheet" href="/static/home/css/base.css?v=1.02">
    <link rel="stylesheet" href="/static/home/css/media.css">
    <script src="/static/home/js/jquery-2.1.4.min.js"></script>
    <script>
        if ( !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/) ) {
            window.location.href = "http://wap.klgwl.com/Downloads/share"
        }
    </script>
    <style>
        .container .snapshoot ul li{
            float:left;
            margin-right:5px;
        }
        .container .snapshoot ul li img{
            width:236px
        }
        .addon{
            padding-top:180px;
            text-align: center;
        }
        .addon p{
            font-size:18px;
            color:#333;
            line-height:1.7em;
        }
        .ques{
            padding-bottom:80px;
        }
        .ques h5{
            font-size:18px;
            color:#434343;
            padding-bottom:10px;
            font-weight:bold
        }
        .ques p a{
            font-size:16px;
            color:#968F8F;
            line-height:2em;
        }
        .banner{
            position:relative;
        }
        .banner .qr{
            position: absolute;
            bottom:0;
            padding-left:35%;
            width:100%;
        }
        .banner .qr div{
            padding-bottom:50px;
            position: relative;
        }
        .banner .qr div span{
            position: absolute;
            color:white;
            top:10px;
            padding-left:12px;
            font-size:18px;
        }
        .banner .qr .qr-img{
            position: absolute;
            left:53%;
            top:0;
            text-align: center;
        }
        .banner .qr .qr-img div{
            color:white;
            font-size:16px;
        }

    </style>
</head>
<body>
<!-- 头部导航 -->
<div class="nav" style="background-color: #FFA800">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li >
                    <a href="index" class="active">
                        首页
                    </a>
                    <span class="active navin"></span>
                    <b></b>
                </li>

                <li class="line-two">
                    <a href="/dynamic" class="active ">恐龙谷动态</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于我们</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/service" class="active">特色服务</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/guide" class="active">用户帮助</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                    <b></b>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>

</script>
<div class="banner">
    <img src="/static/home/images/v3/banner.png" alt="" style="width:100%">
    <div class="qr">
        <div>
            <img src="/static/home/images/v3/icon_apple_small.png" alt="">
            <span>iPhone客户端</span>
        </div>
        <div>
            <img src="/static/home/images/v3/icon_android_small.png" alt="">
            <span>Android客户端</span>
        </div>
        <div class="qr-img">
            <img src="/static/home/images/v3/qr.png" alt="">
            <div>扫描下载客户端</div>
        </div>
    </div>
</div>

<div class="container" style="">
    <div style="font-size:40px;color:black;text-align: center;padding-top:180px;">
        总有商圈在身边
    </div>
    <div style="padding-top:40px;font-size:30px;color:black;text-align: center;">
        进入恐龙谷的世界，通过商圈去探索那些附近的惊喜
    </div>

    <div class="snapshoot" style="padding-top:80px;">
        <ul>
            <li style="margin-right:5px;">
                <img src="/static/home/images/v3/banner_1.png?" alt="" >
            </li>
            <li>
                <img src="/static/home/images/v3/banner_2.png?" alt="">
            </li>
            <li>
                <img src="/static/home/images/v3/banner_3.png?" alt="">
            </li>
            <li style="margin-left:-5px;">
                <img src="/static/home/images/v3/banner_4.png?" alt="" >
            </li>
            <li>
                <img src="/static/home/images/v3/banner_5.png?" alt="">
            </li>


        </ul>
    </div>
    <div style="clear:both"></div>
    <div class="addon">
        <p>其实，红包还有更多的玩法</p>
        <p>其实，在家里你就能轻轻松松逛遍附近商圈</p>
        <p>其实，附近的人都能成为你的朋友</p>
        <p>......</p>
        <p>加入恐龙谷APP</p>
        <p>不做城市的漂泊者</p>
        <p>邂逅擦肩而过的朋友，跟他们一起玩红包、逛商圈</p>
    </div>

    <div style="padding-top:80px;padding-bottom:78px">
        <img src="/static/home/images/v3/icon_wanghongzhaopian.png" alt="">
    </div>

    <div class="ques">
        <div style="float:left;padding-left:114px;width:614px;border-right:1px dashed #ccc;padding-right:114px;" >
            <h5 style="">
                用户帮助
                <span style="float:right;"> <a style="color:#434343;" href="/guide"> >> </a></span>
            </h5>
            <?php foreach( $newest_ques as $item) :?>
                <p style="cursor:pointer"><a href="/guide?type=detail&cid=<?php echo $item['id'] ?>"><?php echo $item['question'] ?></a></p>
            <?php endforeach; ?>

        </div>
        <div style="float:left;padding-left:114px;width:500px;" >
            <h5 style="">
                恐龙谷动态
                <span style="float:right;"> <a href="/dynamic" style="color:#434343">>></a></span>
            </h5>
            <?php foreach( $newest_dynamic as $item) :?>
                <p style="cursor:pointer"><a href="/dynamic/<?php echo $item['id'] ?>.html"><?php echo $item['title'] ?></a></p>
            <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
    </div>

</div>
<?php $this->partial("index/v3/partial/footer") ?>
<div style="display:none">
    <ul>
        <li>
            <a href="http://www.klgwl.cn/">恐龙谷</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">美女交友APP</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">娱乐自媒体平台</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">知识问答软件</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">社交聊天软件</a>
        </li>
    </ul>
</div>

</body>
</html>
<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?fdc02f1210d0e2ecece5eabc082ace41";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();

    $(window).scroll(function(){
        var h = $(window).scrollTop();
        var t = h / 616;
        $('.nav').css('background-color','rgba(255,168,0,' + t + ')');
    });
</script>