<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>特色服务 - 恐龙谷</title>
    <meta name="keywords" content="恐龙谷,恐龙谷app,美女交友app,娱乐自媒体平台,聊天交友,知识问答软件,社交聊天软件,交友软件,视频红包,同城交友,手机交友,视频社交,android,iphone" />
    <meta name="description" content="恐龙谷社交软件app开启附近圈子社交新时代，红包广场全面开启，精彩就在附近，全民开店，视频红包依旧惊喜不断，更有千万人一起红包游戏、知识问答竞赛开战，奖金多多拿到你手软！年轻人都喜欢的娱乐自媒体社交应用平台！" />
    <link rel="shortcut icon" href="/static/home/images/favicon.ico"/>
    <link rel="stylesheet" href="/static/home/css/animate.css">
    <link rel="stylesheet" href="/static/home/css/base.css?v=1.04">
    <link rel="stylesheet" href="/static/home/css/media.css">
    <script src="/static/home/js/jquery-2.1.4.min.js"></script>
    <script>
        if ( !!navigator.userAgent.match(/AppleWebKit.*Mobile.*/) ) {
            window.location.href = "http://wap.klgwl.com/Downloads/share"
        }
    </script>
</head>
<body>

<!-- 头部导航 -->
<div class="nav" style="background-color: #FFA800">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li >
                    <a href="index" class="active">
                        首页
                    </a>
                    <span class=""></span>
                    <b></b>
                </li>

                <li class="line-two">
                    <a href="/dynamic" class="active ">恐龙谷动态</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于我们</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/service" class="active">特色服务</a>
                    <span class="active navin"></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/guide" class="active">用户帮助</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                    <b></b>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>

</script>
<div class="container" style="margin-top:64px;height:100%">
    <div style="">
        <div class="service-name">自主开店</div>
        <div class="service-desc" >
            <img src="/static/home/images/v3/service-1.png" alt="" >
            <div class="desc">
                <p>
                    用户可以通过两种方式自主申请开店，一种是使用邀请码申请，一种是直接申请。使用邀请码申请开店，在服务费上会有折扣，开店需要审核，请正确提交真实信息。
                    成功开店后，可以在恐龙谷进行营销推广，平台也会把店铺推荐给店铺附近的其他用户，店主可以直接在红包广场推广自己的店铺
                </p>
            </div>
        </div>
    </div>
    <div style="">
        <div class="service-name" style="padding-top:6px">成为合伙人</div>
        <div class="service-desc">
            <img src="/static/home/images/v3/service-2.png" alt="" >
            <div class="desc" style="right:-22px">
                <p>
                    合伙人是恐龙谷推出的，用户与平台互惠互利的一种合作方式，加入恐龙谷成为合伙人之后，用户可以获得平台下发的唯一邀请码，并通过邀请好友开店得到平台奖励。
                </p>
            </div>
        </div>
    </div>

</div>
<?php $this->partial("index/v3/partial/footer") ?>
<div style="display:none">
    <ul>
        <li>
            <a href="http://www.klgwl.cn/">恐龙谷</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">美女交友APP</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">娱乐自媒体平台</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">知识问答软件</a>
        </li>
        <li>
            <a href="http://www.klgwl.cn/">社交聊天软件</a>
        </li>
    </ul>
</div>
</body>
</html>