<style>
    .inner-nav, .page-header {
        background: #fff;
    }

    .inner-nav {
        box-shadow: none;
    }

    .page-header {
        margin: -5px;;
        margin-bottom: 5px;
        border-bottom: 1px solid #e4e4e4;
        position: fixed;
        top: 0;
        left: 196px;
        width: 100%;
        max-width: 100%;
        padding-right: 280px;;
        padding-bottom: 5px;
    }

    .page-content {
        padding: 4px;
    }

    .main-container:after, .page-content {
        background: #ececec
    }

    .abbr {
        border-radius: 100%;
        display: inline-block;
        width: 26px;
        height: 26px;
        line-height: 26px;
        vertical-align: middle;
        text-align: center;
        background-color: #e4e4e4;
        cursor: pointer;
    }

    .float_bar {
        height: auto;
        min-height: 100px;
        width: 50px;
        border: 1px solid #e4e4e4;
        position: fixed;
        right: 20px;
        border-radius: 5px;
        padding: 10px 0;
        background: #fff;

    }

    .float_bar ul {
        margin: 0;
    }

    .float_bar ul li {
        text-align: center;

    }

    .float_bar ul li.active .abbr, .abbr:hover {
        color: white;
        background-color: #0b6cbc;

    }

    .content_item {
        width: 100%;
        height: auto;
        overflow: hidden;
    }

    .content_item .header {
        padding-left: 15px;
        font-weight: bold;
        border-bottom: none;
    }

    .content_item .header a {
        display: inline-block;
        height: 30px;
        width: 30px;
        line-height: 30px;
        text-align: center;
        vertical-align: middle;
        background: #fff;
        border: 1px solid #e4e4e4;
        border-radius: 100%;
    }

    .content_item .header .current {
        background: #0b6cbc;
        border: 1px solid #0b6cbc;
        color: #fff;
        box-shadow: 3px 3px 5px #ddd;
    }

    .content_item ul {
        border-bottom: 1px dotted #e4e4e4;
        width: 100%;
        height: auto;
        overflow: hidden;
        margin: 0;
        padding-bottom: 10px;
        padding-left: 15px;;
    }

    .content_item li {
        float: left;
        padding: 2px 10px;
        border: 1px solid #e4e4e4;
        border-radius: 10px;
        margin-right: 5px;
        overflow: hidden;
        max-height: 25px;
        margin-bottom: 10px;;
    }

    .content_item li.current {
        border: 1px solid rebeccapurple;
    }

    .content_item li i {
        cursor: pointer;
    }

    .page-header .search {
        width: 500px;
        height: 40px;
        line-height: 40px;
        vertical-align: middle;
        border-radius: 5px !important;
        margin-left: 10px;
        margin-top: 2px;;
    }

    .search_result {
        position: absolute;
        width: 500px;
        border-radius: 0 0 5px 5px;
        max-height: 300px;
        overflow-y: scroll;
        border: 1px solid #e4e4e4;
        top: 42px;
        left: 10px;
        background: #eee;
        margin: 0;
        display: none;
        max-width: 100%;
        overflow-x: hidden;
    }

    .search_result li {
        height: 40px;
        line-height: 40px;
        vertical-align: middle;
        font-size: 14px;
        padding-left: 5px;;
        color: #444;
        border-bottom: 1px dotted #e4e4e4;
        cursor: pointer;
    }

    .search_result li:hover {
        background-color: #438EB0;
        border-bottom: 1px dotted #438EB0;
        color: #fff;
    }

</style>
<div class="page-header">
    <h1>
        <div style="float: left">
            <span>共 “<b class="green"><?php echo $list['count'] ?></b>” 个敏感词</span>
            <div style="position: relative;display: inline-block">
                <input type="text" class="search" placeholder="拼接每个汉字的首写字母/汉字进行查找"/>&nbsp;<label
                    class="tip green">如:ny，nY，NY，Ny，女优</label>

                <ul class="search_result">
                </ul>
            </div>
        </div>
        <span class="pull-right">
          <!--  <span class="btn-group">-->
               <span class="btn btn-primary btn-sm btnAdd" style="margin-top: 6px;"><i
                       class="fa fa-plus"></i> 添加</span>
            <!--            </span>
            -->        </span>
    </h1>
    <!-- /.col-lg-12 -->
</div>
<div
    style="width: 90%;min-height: 400px;border: 1px solid #e4e4e4;background-color: #fff;overflow: hidden;padding-bottom: 10px;margin-top: 56px">
    <?php $i = 0;
    foreach ($list['content'] as $k => $item) { ?>
        <div class="content_item" style="">
            <p class="header" data-key="<?php echo $k ?>">
                <a href="javascript:;" class="<?php echo $i == 0 ? 'current' : '' ?>"
                   name="<?php echo $k ?>"><?php echo $k ?></a>
            </p>
            <ul class="words">
                <?php foreach ($item as $i) { ?>
                    <li style="" data-key="<?php echo $i['key'] ?>"
                        data-item="<?php echo $i['item'] ?>"><?php echo $i['words'] ?>
                        <i class="fa fa-close red delBtn" style="display: none"></i></li>
                <?php } ?>
            </ul>
        </div>
        <?php $i++;
    } ?>
</div>
<div class="float_bar">
    <ul>
        <?php foreach ($list['keys'] as $k => $item) { ?>
            <li class="<?php echo $k == 0 ? 'active' : '' ?>" data-key="<?php echo $item ?>"><label
                    class="abbr"><?php echo $item ?></label></li>
        <?php } ?>
    </ul>
</div>
<div class="modal fade" id="wordModal">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">添加敏感词</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-2 control-label">敏感词:</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="word"
                                   placeholder="多个敏感词以@分割">
                        </div>
                    </div>
                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    seajs.use('app/panel/site/sensitive', function (api) {
        api.sensitive("normal")
    })
</script>

