<div class="page-header">
    <h1>
        <i class="fa fa-gear"></i> 租人配置
        <small>

        </small>
    </h1>
</div>
<style>
    .form-group {
        min-height: 30px;
        overflow: visible;
    }

    .form-group .control-label {
        text-align: right;
    }

    .form-group select {
        margin: 0;
    }

    .list {
        width: 98%;
        margin: auto;
        display: none;
    }

    .btn {
        display: inline-block;
        cursor: pointer;
    }

    .cancelBtn, .saveBtn {
        display: none;
    }

    .skill_head {
        width: 98%;
        margin: auto;
        border: 1px solid #e2e2e2;
        margin-bottom: 0;
        line-height: 40px;
        border-radius: 2px 2px 0 0;
        padding: 0 10px;
        font-weight: bold;
    }

    .skill_head .spread {
        cursor: pointer;
    }

    textarea.desc {
        min-height: 100px;
    }

    .list input {
        max-width: 80px;
    }

    .title input {
        max-width: 200px;
    }

    .skill_head:first-child {
        border-bottom: none;
    }

    .tip {
        position: relative;
        overflow: visible;
    }

    .tip_box {
        position: absolute;
    }

    img {
        background: #fff;;
    }
</style>
<main class="tab-content" style="border:none; ">

    <section id="home" class="tab-pane in active" style="border:  1px solid #e4e4e4">
        <p class="alert alert-info" style="border-top:none;border-left: none;border-right: none">
            <i class="fa fa-clock-o"></i>基础设置/时间限制<br/>

        </p>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">是否开启自动审核:</label>

            <div class="col-sm-9">
                <input id="AutomaticAudit"
                       type="checkbox" <?php echo $config['AutomaticAudit'] == 1 ? 'checked="checked"' : '' ?>
                       class="ace ace-switch ace-switch-5"/>
                <span class="lbl"></span>
            </div>
        </div>
        <div class="form-group AuditDuration_wrap"
             style="<?php echo $config['AutomaticAudit'] == 1 ? '' : 'display:none' ?>">
            <label for="name" class="col-sm-3 control-label">自动审核时长:</label>

            <div class="col-sm-9">
                <input type="number" class="AuditDuration" value="<?php echo $config['AuditDuration'] ?>"/> 秒
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">买家正常下单付款后，卖家剩余的接单时间:</label>

            <div class="col-sm-9">
                <input type="number" class="deadline" value="<?php echo $config['DeadLine'] / 60 ?>"/> 分钟
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">买家加急下单付款后，卖家剩余的接单时间:</label>

            <div class="col-sm-9">
                <input type="number" class="deadline_immediately"
                       value="<?php echo $config['DeadLineImmediately'] / 60 ?>"/> 分钟
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">买家下单后，剩余的付款时间:</label>

            <div class="col-sm-9">
                <input type="number" class="pay_due_time" value="<?php echo $config['PayDueTime'] / 60 ?>"/> 分钟
            </div>
        </div>

        <div class="form-group">
            <label for="name" class="col-sm-1 control-label"></label>

            <div class="col-sm-10" style="padding: 0 0 0 30px;">
                <button type="submit" class="btn btn-primary btn-sm saveTime" name="btn-base">
                    <i class="fa fa-paper-plane"></i>立即保存
                </button>
            </div>
        </div>
    </section>

</main>
<main class="tab-content" style="border:none;padding-top: 0;">

    <section id="home" class="tab-pane in active" style="border:  1px solid #e4e4e4">
        <p class="alert alert-info" style="border-top:none;border-left: none;border-right: none">
            <i class="fa fa-anchor"></i> 技能列表&nbsp;
            <span class="btn  btn-primary btn-sm btn-inverse btnAdd"><i class="fa fa-plus"></i> 添加技能</span>

        </p>
        <?php
        $skill = json_decode($config['Skill'], true);
        foreach ($skill as $i => $item) { ?>
            <p class="skill_head">
                <span>

                    <?php if ($item['icon']) { ?>
                        <img src="<?php echo $item['icon'] ?>" style="max-height:30px"/> &nbsp;
                    <?php } ?>
                    <?php echo $item['title'] ?>【<?php echo $item['weight'] ?>】
                    <a href="javascript:;" class="editTop" data-title="<?php echo $item['title'] ?>"
                       data-type="<?php echo $item['type'] ?>" data-icon="<?php echo $item['icon'] ?>"  data-weight="<?php echo $item['weight'] ?>"><i
                            class="fa fa-pencil"></i></a></span>
                <span class="right spread" data-id="<?php echo $item['type'] ?>" style="font-size: 20px"><i
                        class="fa fa-angle-double-down"></i></span>
            </p>
            <table id="article-list" class='list list_<?php echo $item['type'] ?>'>
                <thead>
                <tr class="head">
                    <th style="width: 50px">批量</th>
                    <th>技能名称</th>
                    <th style="width: 120px">最低出售价格</th>
                    <th style="width: 120px">最高出售价格</th>
                    <th style="width: 120px">平台服务费率</th>
                    <th style="width: 120px">是否为线下服务</th>
                    <th style="width: 400px">技能描述</th>
                    <th style="width: 100px">技能限制&nbsp;<a href="javascript:;"
                                                          class="fa blue fa-question-circle tip"></a></th>
                    <th style="width: 80px">权重&nbsp;<a href="javascript:;"
                                                       class="fa blue fa-question-circle tooltip-info"  data-rel="tooltip"
                                                       data-placement="top" data-original-title="越大越靠前"></a></th>
                    <th style="width: 100px">是否热门</th>

                    <th>操作</th>
                </tr>
                </thead>
                <tbody class="listData">
                <?php
                foreach ($item['skills'] as $s) { ?>
                    <tr data-type="<?php echo $item['type'] ?>" data-title="<?php echo $item['title'] ?>"
                        data-subtype="<?php echo $s['subtype'] ?>">
                        <td class="center"><label>
                                <input type="checkbox" name="chk_<?php echo $item['type'] ?>"
                                       value="<?php echo $s['subtype'] ?>" class="chk ace"/>
                                <span class="lbl"></span>
                            </label>
                        </td>
                        <td class="title" data-old="<?php echo $s['title'] ?>"><?php echo $s['title'] ?></td>
                        <td class="min_price"
                            data-old="<?php echo $s['min_price'] ?>"><?php echo $s['min_price'] ?>分
                        </td>
                        <td class="max_price"
                            data-old="<?php echo $s['max_price'] ?>"><?php echo $s['max_price'] ?>分
                        </td>
                        <td class="service_rate"
                            data-old="<?php echo $s['service_rate'] * 100 ?>"><?php echo $s['service_rate'] * 100 ?>%
                        </td>
                        <td class="offline"
                            data-old="<?php echo $s['offline'] ?>"><?php echo $s['offline'] == 0 ? '否' : '是' ?>
                        </td>
                        <td class="default_desc"
                            data-old="<?php echo $s['default_desc'] ?>"><?php echo $s['default_desc'] ?>
                        </td>
                        <td class="restrict" data-old="<?php echo $s['restrict'] ?>">
                            <?php echo $s['restrict'] ?>
                        </td>
                        <td class="weight"
                            data-old="<?php echo $s['weight'] ?>"><?php echo $s['weight'] ?>
                        </td>
                        <td class="is_hot"
                            data-old="<?php echo $s['hot'] ?>"><?php echo $s['hot'] == 0 ? '否' : '是' ?>
                        </td>
                        <td><span class="btn btn-xs btn-primary editBtn" data-type="<?php echo $item['type'] ?>"
                                  data-subtype="<?php echo $s['subtype'] ?>"><i class="fa fa-edit"></i><label>编辑</label>
                            </span>
                            <span class="btn btn-sm btn-success saveBtn" data-type="<?php echo $item['type'] ?>"
                                  data-subtype="<?php echo $s['subtype'] ?>"><i class="fa fa-send"></i><label>保存</label>
                            </span>&nbsp;
                            <span class="btn btn-sm  cancelBtn" data-type="<?php echo $item['type'] ?>"
                                  data-subtype="<?php echo $s['subtype'] ?>"><i
                                    class="fa fa-close"></i><label>取消</label>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
                <tr style="background-color: #f2f2f2">
                    <!-- <td colspan="6">
                        <span class="btn btn-sm btn-inverse btnAdd" data-type="<?php /*echo $item['type'] */ ?>"><i
                                class="fa fa fa-plus"></i> 添加技能</span>
                    </td>-->
                    <td colspan="11 right">
                        <select name="p_type" id="p_type_<?php echo $item['type'] ?>">
                            <?php foreach ($parent_skill as $k => $s) { ?>
                                <option
                                    data-type="<?php echo $s['name'] ?>" <?php echo $item['type'] == $k ? "selected" : '' ?>
                                    value="<?php echo $k ?>"><?php echo $s['name'] ?></option>
                            <?php } ?>
                        </select>
                        <span class="btn btn-xs btn-primary btnRemove"
                              data-type="<?php echo $item['type'] ?>">确认移动</span>
                    </td>
                </tr>
                </tbody>
            </table>
            <p style="line-height: 10px;height: 10px;width: 100%"></p>
        <?php } ?>
    </section>

</main>
<div class="modal fade" id="skillModal">
    <div class="modal-dialog" style="width: 550px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">添加技能</h4>
            </div>
            <div class="modal-body" style="overflow:visible;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">父级技能:</label>

                        <div class="col-sm-9">
                            <select class="parent_type">
                                <option value="0" data-type="">顶级</option>
                                <?php foreach ($parent_skill as $k => $s) { ?>
                                    <option data-type="<?php echo $s['name'] ?>"
                                            value="<?php echo $k ?>"><?php echo $s['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">技能名称:</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="title" maxlength="50" placeholder="">
                        </div>
                    </div>
                    <div class="form-group icon_group">
                        <label for="logo" class="col-sm-3 control-label">小图标：</label>
                        <div class="col-sm-9">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="icon" id="thumb2" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon" id="iconUpload2" href="javascript:;">选择图片</a>
                                </div>
                            </div>
                    <span class="col-xs-4 pic-review" id="picReviewer" data-list-item-id="12">
                        <img src=""
                             class="preview-thumb2"
                             style="height: 32px;" title="图片预览">
                        <label class="help-block with-errors"></label>
                    </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">权重:</label>

                        <div class="col-sm-9">
                            <input type="number" class="" value="0" id="weight" placeholder="权重【越大越靠前】">
                        </div>
                    </div>
                    <div class="subAttr" style="display: none">

                        <!--  <div class="form-group">
                              <label for="ruleName" class="col-sm-2 control-label">排序:</label>

                              <div class="col-sm-10">
                                  <input type="text" class="form-control" id="sort_num" placeholder="排序越小越靠前">
                              </div>
                          </div>-->
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">最低出售价格:</label>

                            <div class="col-sm-9">
                                <input type="number" class="" value="0" id="min_price" placeholder="最低出售价格"> 分
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">最高出售价格:</label>

                            <div class="col-sm-9">
                                <input type="number" class="" value="0" id="max_price" placeholder="最高出售价格"> 分
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">平台服务费率:</label>

                            <div class="col-sm-9">
                                <input type="number" class="" value="0" id="service_rate" placeholder="平台服务费率"> %
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">是否为线下服务:</label>

                            <div class="col-sm-9">
                                <input id="offline" type="checkbox"
                                       class="ace ace-switch ace-switch-5"/>
                                <span class="lbl"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">是否热门:</label>

                            <div class="col-sm-9">
                                <input id="is_hot" type="checkbox"
                                       class="ace ace-switch ace-switch-5"/>
                                <span class="lbl"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="ruleName" class="col-sm-3 control-label">技能限制 &nbsp;
                                <a href="javascript:;" class="fa blue fa-question-circle tip"></a> :</label>


                            <div class="col-sm-6">
                                <input type="number" value="0" min="0" max="3" id="restrict"
                                       maxlength="1" placeholder="技能限制【0,1,2,3】">
                            </div>
                        </div>

                    </div>

                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="editModal">
    <div class="modal-dialog" style="width: 550px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">添加编辑</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">技能名称:</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control type_title" maxlength="50" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="logo" class="col-sm-3 control-label">小图标：</label>
                        <div class="col-sm-9">
                            <div class="col-xs-8" style="padding-left: 0">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-picture-o"></i></span>
                                    <input class="form-control img" name="icon" id="thumb1" type="text" readonly=""
                                           value="">
                                    <a class="input-group-addon" id="iconUpload1" href="javascript:;">选择图片</a>
                                </div>
                            </div>
                    <span class="col-xs-4 pic-review" id="picReviewer" data-list-item-id="12">
                        <img src=""
                             class="preview-thumb1"
                             style="height: 32px;" title="图片预览">
                        <label class="help-block with-errors"></label>
                    </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ruleName" class="col-sm-3 control-label">权重:</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control weight" maxlength="50" placeholder="">
                        </div>
                    </div>

                    <p class="alert alert-danger error-widget" style="display: none"><i class="fa fa-warning"></i>
                        <span class="error_msg"></span>
                    </p>
                    <p class="alert alert-success success-widget" style="display: none"><i class="fa fa-check"></i>
                        <span class="success_msg"></span>
                    </p>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-type="" data-original="" id="sureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="tip_box"
     style="width:600px;height: auto;padding: 10px;display: none;background: #fff;border: 1px solid #e4e4e4;bottom:20px;left: 50%;margin-left: -300px;border-radius: 2px;z-index: 1041">
    <div class="tip_content" style="text-align: left;line-height: 26px;color: #444;font-weight: bold">
        1、restrict等于0时，该技能正常使用，不受任何限制<br/>
        2、restrict等于1时，无法通过拉取技能列表获取，但是该技能可以正常使用<br/>
        3、restrict等于2时，无法通过拉取技能列表获取，买家可以对该技能正常下单，但是卖家无法再申请该技能<br/>
        4、restrict等于3时，无法通过拉取技能列表获取，同时买家不能看到该技能，卖家也无法再申请该技能，已经申请的卖家将被劝说下架该技能
    </div>
</div>
<script>

    seajs.use('app/panel/rent/skillConfig.js?v=1.2.3', function (api) {
        api.edit();
        $('[data-rel=tooltip]').tooltip();
    });

</script>
