<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/echarts/echart-all.2.2.7.min.js"></script>
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script type="text/javascript" src="/srv/static/panel/js/tools/Url.js"></script>

<style>
    .stat_component .time {
        width: 80px;
        height: 24px;
        line-height: 24px;
        margin: 0 0 0 7px;
        padding: 0 0 0 6px;
        border: 1px solid #e1e3e4;
        border-right: none;
        text-indent: 0;
        color: #323437;
        cursor: pointer;
        float: left;
        border-top-left-radius: 2px !important;
        border-bottom-left-radius: 2px !important;
    }

    .stat_component .time_picker {
        width: 24px;
        height: 24px;
        display: inline-block;
        float: left;
        border: 1px solid #e4e4e4;
        border-top-right-radius: 2px;
        border-bottom-right-radius: 2px;
        text-align: center;
        color: #666;
        cursor: pointer;
    }


</style>

<div class="stat_component">
    <div class="content_wrap left " style="height: 850px;width:99%;max-width:99%">

        <div id="filters" class="filters" style="padding-top:10px">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">

                    <div class="select-bar-item l time_filter" style="display: ">
                        <span style="float:left;vertical-align: middle;font-weight:bold" class="blue">统计截止日期：</span>
                        <input type="text" class="time start" id="start" data-id="start" value="<?php echo substr($d,0,4) . '-' . substr($d,4,2) . '-' . substr($d,6,2)?>" style="border-radius: 10px;">
                        <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                        <span style="float:left;vertical-align: middle;font-weight:bold;margin-left:30px" class="blue">类型：</span>
                        <select name="" id="type" style="height:24px">
                            <?php echo $type?>
                            <option value="order_dtb" <?php if( $type == 'order_dtb') echo 'selected'?> >买家</option>
                            <option value="seller_dtb" <?php if( $type == 'seller_dtb') echo 'selected'?> >卖家</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <hr class="hr-10">
        <div id="province" style="width:50%;height:600px;float:left;border-right:1px dotted #ccc;"></div>
        <div id="city" style="width:50%;height:600px;float:right;;text-align: center">
            <span style="font-size:20px;color:#ccc;display: block;margin-top:300px">
                <i class="fa fa-arrow-left fa-3" aria-hidden="true" ></i>
                &nbsp;点击左侧省份显示详细信息
            </span>
        </div>
        <div class="clearfix"></div>
        <hr class="hr-10">
        <div id="city_bar" style="width:100%;height:600px"></div>
    </div>
</div>

<script>
    var citys = <?php echo $citys?>;
    var myChart = echarts.init(document.getElementById('province'),'blue');
    var ecConfig = echarts.config;
    var option_map = {
        title : {
            text: '全国',
            subtext: '',
            x:'left'
        },
        tooltip : {
            trigger: 'item'
        },

        dataRange: {
            min: 0,
            max: <?php echo $max?>,
            x: 'left',
            y: 'bottom',
            text:['高','低'],           // 文本，默认为数值文本
            calculable : true
        },

        series : [
            {
                name: '<?php echo  $type == 'order_dtb' ? '买家' : '卖家' ?>',
                type: 'map',
                mapType: 'china',
                selectedMode : 'single',
                roam: false,
                itemStyle:{
                    normal:{label:{show:true}},
                    emphasis:{label:{show:true}}
                },
                data:<?php echo $province?>
            }
        ]
    };
    var option_bar = {
        title : {
            text: '全国市区数据',
            subtext: ''
        },
        tooltip : {
            trigger: 'axis'
        },
        toolbox: {
            show: true,
            feature: {
                mark: {show: true},
                dataView: {show: true, readOnly: false},
                magicType: {show: true, type: ['line', 'bar', 'stack', 'tiled']},
                restore: {show: true},
                saveAsImage: {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                data : <?php echo json_encode($bar['xAxis'],true)?>
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'<?php echo $type == 'order_dtb' ? '买家' : '卖家' ?>个数',
                type:'bar',
                data:<?php echo json_encode($bar['data'],true)?>,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }
        ]
    };


    myChart.on(ecConfig.EVENT.MAP_SELECTED,function (param) {
        var selected = param.selected;
        var selectedProvince = '';
        for( var key in selected){
            if(selected[key] ){
                selectedProvince = key;
                break;
            }
        }
        option_map.title.text = selectedProvince
        option_map.dataRange.x = 'right'
        option_map.series[0].selectedMode=null
        option_map.series[0].mapType = selectedProvince;
        option_map.series[0].data = <?php echo $citys?>;
        echarts.init(document.getElementById('city')).setOption(option_map,true);

    });
    myChart.setOption(option_map,true);//初始化
    echarts.init(document.getElementById('city_bar'),'macarons').setOption(option_bar,true);//初始化
    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        onChangeDateTime: function (e) {
            var url = new Url();
            url.setArgs({d:$('#start').val().replace(/-/g,'')});
            window.location.href = url.getUrl();
        }
    });
    $('#type').on('change',function(){
        var url = new Url();
        url.setArgs({type:$('#type').val()});
        window.location.href = url.getUrl();
    });
</script>