<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/echarts/echart-all.2.2.7.min.js"></script>
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script type="text/javascript" src="/srv/static/panel/js/tools/Url.js"></script>
<script type="text/javascript" src="/srv/static/panel/js/app/panel/panel.base.js"></script>
<style>
    .stat_component .time {
        width: 80px;
        height: 24px;
        line-height: 24px;
        margin: 0 0 0 7px;
        padding: 0 0 0 6px;
        border: 1px solid #e1e3e4;
        border-right: none;
        text-indent: 0;
        color: #323437;
        cursor: pointer;
        float: left;
        border-top-left-radius: 2px !important;
        border-bottom-left-radius: 2px !important;
    }

    .stat_component .time_picker {
        width: 24px;
        height: 24px;
        display: inline-block;
        float: left;
        border: 1px solid #e4e4e4;
        border-top-right-radius: 2px;
        border-bottom-right-radius: 2px;
        text-align: center;
        color: #666;
        cursor: pointer;
    }


</style>

<div class="stat_component">
    <div class="content_wrap left " style="height: 850px;width:99%;max-width:99%">

        <div id="filters" class="filters" style="padding-top:10px">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">

                    <div class="select-bar-item l time_filter" style="display: ">
                        <span style="float:left;vertical-align: middle;font-weight:bold" class="blue">统计周期：</span>
                        <input type="text" class="time start" id="start" data-id="start" value="<?php echo substr($start,0,4) . '-' . substr($start,4,2) . '-' . substr($start,6,2)?>" style="border-radius: 10px;">
                        <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                        <span style="float:left;height:24px;line-height:24px;padding-left:9px">-</span>
                        <input type="text" class="time start" id="end" data-id="start" value="<?php echo substr($end,0,4) . '-' . substr($end,4,2) . '-' . substr($end,6,2)?>" style="border-radius: 10px;">
                        <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                        <input type="button" class="btn btn-xs btn-primary " id="time" value="查询" style="margin-left:15px;border-width: 2px;">
                    </div>
                </div>
            </div>
        </div>
        <hr class="hr-10">
        <div id="seller_bar" style="width:100%;height:500px;"></div>
        <hr class="hr-10">
        <div id="buyer_bar" style="width:100%;height:500px;"></div>
<!--        <div id="seller_pie" style="width:50%;height:500px;float:right;"></div>-->
    </div>
</div>

<script>
    var option_bar = {
        title : {
            text: '接单/拒单时间分布',
            subtext: ''
        },
        tooltip : {
            trigger: 'axis'
        },
        toolbox: {
            show: true,
            feature: {
                magicType: {show: true, type: ['line', 'bar']},
                saveAsImage: {show: true}
            }
        },
        calculable : true,
        legend:{
            data:['接单数','拒单数'],
            selected:{'拒单数':false}
        },
        xAxis : [
            {
                type : 'category',
                axisLabel:{
                    interval:0,
                    rotate:-45
                },
                data : ['0点','1点','2点','3点','4点','5点','6点','7点','8点','9点','10点','11点','12点','13点','14点','15点','16点','17点','18点','19点','20点','21点','22点','23点']
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'接单数',
                type:'bar',
                data:<?php echo json_encode($res_seller['pick'],true)?>,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            },
            {
                name:'拒单数',
                type:'bar',
                data:<?php echo json_encode($res_seller['refuse'],true)?>,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }
        ]
    };

    echarts.init(document.getElementById('seller_bar'),'macarons').setOption(option_bar,true);
    option_bar.title.text = '下单时间分布';
    option_bar.legend.data = ['下单数'];
    option_bar.series.name = '下单数';
    option_bar.series = [{
        name:'下单数',
        type:'bar',
        data:<?php echo json_encode($res_buyer,true)?>,
        markPoint : {
            data : [
                {type : 'max', name: '最大值'},
                {type : 'min', name: '最小值'}
            ]
        },
        markLine : {
            data : [
                {type : 'average', name: '平均值'}
            ]
        }
    }];
    echarts.init(document.getElementById('buyer_bar'),'macarons').setOption(option_bar,true);

    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
    });

    $('#end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,

    });
    seajs.use('app/panel/panel.base',function(api){
        $('#time').on('click',function(){
            var start = $('#start').val().replace(/-/g,'');
                end = $('#end').val().replace(/-/g,'');
            if(end < start)
                tip.showTip('err','开始时间不能大于结束时间','1000');
            var url = new Url();
            url.setArgs({start:start,end:end});
            window.location.href = url.getUrl();
            //console.log(url.getUrl());

        });
    });

</script>