<div class="page-header">
    <h1>基础设置</h1>
</div>

{{ content() }}

{{ form('panel/users/setting', 'id': 'registerForm', 'class': 'form-horizontal', 'onbeforesubmit': 'return false', 'data-toggle':"validator", 'role':'form') }}
<fieldset>
    <div class="form-group">
        <label class="col-sm-2 control-label">分享得积分</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <label><input type="radio" name="share_point" value="1" {%if setting and setting.share_point==
                              1%}checked{% endif %}/>开启</label> <label><input type="radio" name="share_point" value="0"
                                                                              {%if !setting or setting.share_point==
                                                                              0%}checked{% endif %}/>关闭</label>
                <span class="help-block with-errors">开启用户分享后赚积分功能</span>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">积分抵现</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <label><input type="radio" name="point_cash" value="1" {%if setting and setting.point_cash==
                              1%}checked{% endif %}/>开启</label> <label><input type="radio" name="point_cash" value="0"
                                                                              {%if !setting or setting.point_cash==
                                                                              0%}checked{% endif %}/>关闭</label>
                <span class="help-block with-errors">开启积分抵现功能</span>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">积分抵现比例</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <input type="text" name="point_cash" value="10"/>
                <span class="help-block with-errors">比例为￥1：x积分，只有开启了积分抵现功能，此项设置才会生效</span>
            </p>
        </div>
    </div>
</fieldset>

<div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <span style="margin: 0 0 0 24px;">
    {{ submit_button('保存', 'class': 'btn btn-primary btn-large') }}

    </span>
</div>
{{end_form()}}