<?php
$userInfo = $this->userInfo;
$groups = $this->groups;
?>
<script type="text/javascript">
    seajs.use('app/admin/admin.manager', function (api) {
        api.updateAdmin('#infoBtn');
        api.resetPasswd('#passwdBtn');
    });
</script>
<h2 class="title">基本信息 【 <a href="<?php echo $this->controllerUrl('userPerm/uid/' . $userInfo['uid']); ?>">管理权限 »</a> 】
</h2>

<form class="form" id="updateAdminForm" action="javascript:;">
    <p><span class="rowspan">用户名</span> <input type="text" class="txt " id="user"
                                               value="<?php echo $userInfo['user_name']; ?>">
        <span id="status">用于登陆</span></p>

    <p><span class="rowspan">真实姓名</span> <input type="text" class="txt" id="true_name"
                                                value="<?php echo $userInfo['true_name']; ?>"> <span id="status"></span>
    </p>

    <p><span class="rowspan">邮箱</span> <input type="text" class="txt" id="email"
                                              value="<?php echo $userInfo['email']; ?>"> <span id="status"></span></p>

    <p>
        <span class="rowspan">所属组</span>
        <select name="" id="group_id" class='selc'>
            <option value="0">系统默认组</option>
            <?php
            foreach ($groups as $group) {
                if ($group['id'] == $userInfo['group_id']) {
                    echo '<option value="' . $group['id'] . '" selected="selected">' . $group['name'] . '</option>';
                } else {
                    echo '<option value="' . $group['id'] . '">' . $group['name'] . '</option>';
                }
            }
            ?>
        </select>
        <a href="<?php echo $this->controllerUrl('groupPerm/gid/' . $userInfo['group_id']); ?>">管理组权限 »</a>
    </p>
    <p class="action">
        <span class="rowspan"></span>
        <input type="submit" class="deep_btn" id="infoBtn"  data-uid="<?php echo $userInfo['uid']; ?>" value="提交">
        <input type="reset" class="deep_btn" value="重置">
    </p>
</form>
<h2 class="title">重置密码</h2>
<form class="form" action="javascript:;" id="changePasswdForm">
    <p><span class="rowspan">输入新密码</span> <input type="password" class="txt" id="newPasswd" name="newPasswd" value="">
    </p>

    <p class="action">
        <span class="rowspan"></span>
        <input type="submit" class="deep_btn" id="passwdBtn" data-uid="<?php echo $userInfo['uid']; ?>" value="提交">
        <input type="reset" class="deep_btn" value="重置">
    </p>
</form>