<style type="text/css">
    ul {
        margin: 0;
        padding: 0;
    }

    .topMenu {
        line-height: 36px;
        font-size: 14px;
        font-family: 'Microsoft YaHei';
        font-weight: bold;
        border-bottom: 1px solid #999;
        margin: 0;
        padding: 0;
    }

    .secMenu {
        line-height: 30px;
        font-weight: normal;
        background: #F4FAFE;
        font-size: 14px;
        margin: 0;
        padding: 0;
        border: 1px solid #DEEFFB;
        border-bottom: none;
    }

    .thrMenu {
        line-height: 24px;
        color: #666;
        border: 1px solid #DEEFFB;
        padding: 6px 2px;
        margin: 0 0 8px;
    }

    .thrMenu label {
        padding: 0 8px;
        display: inline-block;
    }

    .menu {
        margin: 0 8px 0 4px;
    }

    .chooseTip {
        margin: 20px;
        color: #ff0000;
    }
</style>
<script type="text/javascript">
    seajs.use('app/admin/admin.manager.js?v=1.0.1', function (api) {
        api.setUserPermission();
    });
</script>
<div class="content">
    <form action="javascript:;" id="permissionForm">
        <table width='100%' class='list'>
            <caption>
                <b class="captitle">管理员权限设置</b>
            </caption>
            <tr class="showpage">
                <td style="font-size: 14px;">
                    选择管理员：
                    【<?php
                    foreach ($users as $user) {
                        ?>
                        <a href="<?php echo $this->uri->actionUrl('?uid=' . $user['id']); ?>"
                           style="<?php echo $this->request->get('uid') == $user['id'] ? 'color:red;' : ''; ?>"><?php echo $user['name']; ?></a> |
                        <?php
                    }
                    ?>
                    】
                    <input type="button" value="全选" class="btn-light selcAll">
                    <input type="button" value="全不选" class="btn-light selcNone">
                    <input type="button" value="提交权限设置" data-uid='<?php echo $uid; ?>' id=""
                           class="btn-light setPermissionBtn">
                </td>
            </tr>
            <?php if ($userInfo) { ?>

                <tr>
                    <td>
                        <div class="alert alert-warning" style="margin-bottom:0" id="tip">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>提示：</strong>

                            <span id="tip"><span class="red">红色</span> 不可选的权限选项为用户所属 <span class="red">角色权限</span>，修改该类权限请至 <span
                                    class="blue"> <a href="/panel/admin/groupPerm<?php echo '?gid=' . $gid; ?>">系统管理->账号设置->角色权限</a></span></span>
                            <br>
                        </div>
                        <ul>
                            <?php

                            $userPerms = array();
                            $userRights = array();

                            foreach ($userPermissions as $val) {
                                $userPerms[$val['id']] = $val['menu_id'];
                                $userRights[$val['id']] = $val['right_type'];
                            }
                            foreach ($menuCats as $topCat) {
                                if ($topCat['parent_id'] == 0) {
                                    ?>
                                    <li class="menu">
                                        <h2 class="topMenu"><?php echo $topCat['title']; ?> </h2>
                                        <?php
                                        foreach ($menuCats as $secCat) {
                                            if ($secCat['parent_id'] == $topCat['id']) {
                                                ?>
                                                <h3 class="secMenu"> >> <?php echo $secCat['title']; ?>
                                                    [ <a href="javascript:;" class="selcAll"
                                                         data-cid="<?php echo $secCat['id']; ?>">全选</a> |
                                                    <a href="javascript:;" class="selcNone"
                                                       data-cid="<?php echo $secCat['id']; ?>">全不选</a> ] </h3>
                                                <div class="thrMenu">
                                                    <?php
                                                    foreach ($menus as $menu) {
                                                        //过滤账号相关权限
                                                        if ($secCat['id'] == 7) {
                                                            //管理员可以给以 管理账号的权限
                                                            if ($userInfo['level'] == \Multiple\Panel\Plugins\AdminPrivilege::$LEVEL_ADMIN) {
                                                                if (in_array($menu['id'], [2, 3, 4, 5, 6])) {
                                                                    continue;
                                                                }
                                                            } else {
                                                                if (in_array($menu['id'], [1, 2, 3, 4, 5, 6])) {
                                                                    continue;
                                                                }
                                                            }
                                                        }
                                                        if ($menu['cid'] == $secCat['id']) {
                                                            ?>
                                                            <label value='<?php echo $menu['id']; ?>' class="change">
                                                                <?php
                                                                $key = array_search($menu['id'], $userPerms);
                                                                if ($key !== false) {/*附加权限*/
                                                                    ?>
                                                                    <input type="checkbox"
                                                                           data-old-perm="<?php echo $userRights[$key]; ?>"
                                                                           data-cid="<?php echo $secCat['id']; ?>"
                                                                           value="<?php echo $userRights[$key]; ?>"
                                                                           data-menu-id="<?php echo $menu['id']; ?>"
                                                                           data-perm-id="<?php echo $key; ?>"
                                                                        <?php if ($userRights[$key] == 1) echo 'checked="checked"'; ?>
                                                                           class='chk ace'/>

                                                                    <?php
                                                                } else {/*组权限*/

                                                                    ?>

                                                                    <input type="checkbox"
                                                                           data-old-perm="0"
                                                                           value="0"
                                                                           data-cid="<?php echo $secCat['id']; ?>"
                                                                           data-menu-id="<?php echo $menu['id']; ?>"
                                                                        <?php $k = array_search($menu['id'], $pg);
                                                                        if ($k !== false) echo "checked disabled"; ?>

                                                                           class='chk ace'>
                                                                    <?php
                                                                }

                                                                ?>
                                                                <span class="lbl"></span>
                                                                <span
                                                                    title='<?php echo $menu['controller'] . '/' . $menu['action']; ?>'
                                                                    class="<?php if (($k = (array_search($menu['id'], $pg))) !== false) echo "red tips" ?> "><?php echo $menu['title']; ?>
                                                                    <?php if ($menu['module'] == 'panel') { ?>
                                                                        <i class="badge badge-primary">展示</i>
                                                                    <?php } else { ?>
                                                                        <i class="badge badge-success">api</i>

                                                                    <?php } ?>
                                                                </span>
                                                            </label>
                                                            <?php
                                                        }
                                                    } ?>
                                                </div>
                                                <?php
                                            }
                                        } ?>
                                    </li>
                                    <?php
                                }

                            }
                            ?>
                        </ul>
                    </td>
                </tr>
                <tr class="showpage">
                    <td>
                        <p style="margin:8px 0;">
                            <input type="button" value="提交" data-uid='<?php echo $uid; ?>'
                                   class="btn-gray setPermissionBtn">
                            <input type="button" value="全选" class="btn-light selcAll">
                            <input type="button" value="全不选" class="btn-light selcNone">
                        </p>
                    </td>
                </tr>
            <?php } else { ?>
                <tr>
                    <td>
                        <p class="chooseTip">请选择一个用户~~~~~</p>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </form>
</div>

<script>
    $(document).ready(function () {
        $(".tips").click(function () {
            $('html').animate({
                scrollTop: 0
            }, 'fast', 'swing', function () {
                setTimeout(function () {
                    $('#tip').toggleClass('animated fadeIn');
                }, 200)
            });
        });
        $('#tip').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
            $(this).toggleClass('animated fadeIn');
        });
    });
</script>