<link rel="stylesheet" href="/srv/static/panel/css/stat.css">
<link rel="stylesheet" href="/srv/static/panel/css/stat2.css">
<link rel="stylesheet" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/ace/js/date-time/moment.min.js"></script>
<script src="/srv/static/panel/js/echarts/echart-all.2.2.7.min.js"></script>

<div class="col-xs-12 " style="margin-top:10px;margin-bottom:10px">
    <label for="ac_type" style="font-weight:bold;">请选择统计时段：</label>
    <input type="text" class="start" value="{{begin}}" > - <input type="text" class="end" value="{{end}}" >
    <input type="button" class="btn btn-xs btn-primary" value="查询" style="margin-left:10px" id="query">
</div>

<div class="stat_component" >

    <div class="content_wrap left" style="height:400px">
        <div class="page-header" style="margin-bottom: 2px">
            <b style="padding-left: 10px;">iOS各版本占比：</b>
        </div>
        <div class="main_wrap">
            <div class="loading" style="display: none;"><img src="/srv/static/panel/images/admin/loading2.gif">&nbsp;&nbsp;数据加载中...</div>
            <div class="main" id="pie-ios" style="width:100%;height:320px" ></div>
        </div>
    </div>

    <div class="content_wrap right" style="height:400px">
        <div class="page-header" style="margin-bottom: 2px">
            <b style="padding-left: 10px;">Android各版本占比：</b>
        </div>
        <div class="main_wrap">
            <div class="loading" style="display: none;"><img src="/srv/static/panel/images/admin/loading2.gif">&nbsp;&nbsp;数据加载中...</div>
            <div class="main" id="pie-android" style="width:100%;height:320px" ></div>
        </div>
    </div>




</div>

<script>
    $('.start,.end').datetimepicker({
        format:'Y/m/d',
        lang:'ch',
        minDate:'2018/04/11',
        maxDate:"<?php echo date('Y/m/d',time())?>",
        timepicker:false,
        allowBlank:true
    });

    seajs.use('app/panel/stat/panel.appVersion.js?0.0.1',function (api) {
        api.reload()
    })
</script>



