<link rel="stylesheet" href="/srv/static/panel/css/stat.css"/>
<link rel="stylesheet" href="/srv/static/ace/css/chosen.css"/>
<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/ace/js/chosen.jquery.min.js"></script>
<style>
    .stat_component .filters {
        padding-bottom: 10px;
    }

    .stat_component .filter {
        margin-left: 15px;
        display: inline-block;
        overflow: hidden;
    }

    .stat_component .control-bar-wrapper {
        position: relative;
        padding-top: 20px;
        padding-bottom: 15px;
        color: #323437;
        padding-left: 20px;
    }

    .stat_component .stat_label {
        display: inline-block;
        height: 26px;
        padding-right: 5px;
        line-height: 26px;
        color: #787a7d;
    }

    .stat_component .control-bar-wrapper .control-bar .date-select-bar {
        border: 1px solid #e1e3e4;
        border-radius: 2px;
    }

    .stat_component .control-bar-wrapper .control-bar .date-select-bar a {
        display: inline-block;
        float: left;
        height: 24px;
        line-height: 24px;
        padding: 0 10px;
        color: #323437;
        background-color: #fff;
    }

    .stat_component .control-bar-wrapper .control-bar .date-select-bar a {
        display: inline-block;
        float: left;
        height: 24px;
        line-height: 24px;
        padding: 0 10px;
        color: #323437;
        background-color: #fff;
    }

    .stat_component .control-bar-wrapper .control-bar .date-select-bar a:last-child.cur {
        border-radius: 0 2px 2px 0;
        right: -1px;
    }

    .stat_component .control-bar-wrapper .control-bar .date-select-bar .cur {
        position: relative;
        bottom: -1px;
        margin-top: -2px;
        padding-top: 1px;
        height: 25px;
        background-color: #438eb9;
        color: #fff;
    }

    .stat_component .filter .group {
        float: left;
        background-color: #fff;
        border-radius: 2px;
        margin: 0;
    }

    .stat_component .filter .group li:first-child {
        margin-left: 0;
        border-top-left-radius: 2px;
        border-bottom-left-radius: 2px;
    }

    .stat_component .filter .group .cur {
        position: relative;
        z-index: 1;
        border: 1px solid #438eb9;
        color: #fff;
    }

    .stat_component .filter .group li:hover {
        background-color: #f3f4f4;
    }

    .stat_component .filter .group .cur, .filter .group li.cur:hover {
        background-color: #438eb9;
    }

    .stat_component .filter .group li {
        cursor: pointer;
        padding: 0 12px;
        border: 1px solid #e1e3e4;
        margin-left: -1px;
    }

    .stat_component .filter .group li, .filter label {
        height: 24px;
        line-height: 24px;
        float: left;
    }

    .stat_component .time {
        width: 80px;
        height: 24px;
        line-height: 24px;
        margin: 0 0 0 7px;
        padding: 0 0 0 6px;
        border: 1px solid #e1e3e4;
        border-right: none;
        text-indent: 0;
        color: #323437;
        cursor: pointer;
        float: left;
        border-top-left-radius: 2px !important;
        border-bottom-left-radius: 2px !important;
    }

    .stat_component .time_picker {
        width: 24px;
        height: 24px;
        display: inline-block;
        float: left;
        border: 1px solid #e4e4e4;
        border-top-right-radius: 2px;
        border-bottom-right-radius: 2px;
        text-align: center;
        color: #666;
        cursor: pointer;
    }

    .stat_component .split_line {
        display: inline-block;
        float: left;
        margin-left: 7px;
        font-size: 16px;
        color: #666
    }

    .stat_component .control-bar-wrapper .select-bar-item {
        position: relative;
        margin-left: 5px;
        height: 24px;
        line-height: 24px;
    }

    .stat_component .filter .group li:last-child {
        border-top-right-radius: 2px;
        border-bottom-right-radius: 2px;
    }

    .stat_component .filters .item div {
        padding:7px;
        border:1px solid #eee;
        border-collapse:collapse;
        margin-right: -1px;
        margin-bottom: -1px;
    }
    .stat_component .filters .item div span:first-child {
        font-style:italic;
    }
    .stat_component .filters .item div span:last-child {
        font-weight:bold;
    }

</style>
<div class="stat_component">
    <div class="content_wrap left " style="height: 850px;width:99%;max-width:99%">
        <div id="filters" class="filters">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div style="margin-bottom:20px;">
                    <span style="font-size:15px;font-weight:bold">汇总统计：</span><span style="font-style: italic;" id="range" ></span><br />
                    <div style="padding:10px" class="item blue " >


                        <div class="col-xs-2 col-md-1 " style="width:200px">
                            <span >注册人数：</span><span ></span>
                        </div>
                        <div class="col-xs-2 col-md-2" style="width:200px">
                            <span >激活人数：</span><span ></span>
                        </div>
                        <div class="col-xs-2 col-md-2" style="width:200px">
                            <span >激活百分比：</span><span ></span>
                        </div>
                        <div class="col-xs-2 col-md-2 red" style="width:200px">
                            <span >一级花费：</span><span ></span>元
                        </div>
                        <div class="col-xs-2 col-md-2 red" style="width:200px">
                            <span >二级花费：</span><span ></span>元
                        </div>
                        <div class="col-xs-2 col-md-2 red" style="width:200px">
                            <span >三级花费：</span><span ></span>元
                        </div>
                        <div class="col-xs-2 col-md-2 red" style="width:200px">
                            <span >总花费：</span><span ></span>元
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="hr hr-dotted "></div>
                <div class="control-bar bg-iframe l" id="redbag_type">
                    <span class="l stat_label " style="font-weight:bolder;color:black">类型：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <span class="seprator"></span>
                        <a href="javascript:;" data-type="user"  class=" cur promo_type">推广成效</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-type="spend"  class=" promo_type">推广花费</a>


                    </div>
                </div>
                <div class="control-bar bg-iframe l" id="control-bar">
                    <span class="l stat_label " style="margin-left:10px;font-weight:bolder;color:black">统计周期：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="all"  class="trackable cur">全部</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="custom"  class="trackable">自定义</a>

                    </div>
                    <div class="select-bar-item l time_filter" style="display: none">
                        <input type="text" class="time start" id="start1" data-id="start" readonly style="border-radius: 10px;">
                        <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                        <span class="split_line">-</span>
                        <input type="text" data-id="end" class="time end" id="end1" readonly>
                        <span class="time_picker" data-id="end"> <i class="fa fa-calendar-check-o"></i></span>
                        &nbsp;
                        <input type="button" class="btn btn-primary btn-xs" value="查询" id="chart_area_send">

                    </div>
                </div>
            </div>
        </div>
        <div class="main" id="chart_area" chart_area></div>
    </div>

</div>

<script type="text/javascript" src="/static/panel/js/echarts/echarts.min.js"></script>
<script type="text/javascript">
    $('.chosen-select').chosen();
    seajs.use('app/panel/stat/panel.promote.js?v=0.0.13', function (api) {
        api.complex();
    })
</script>