<link rel="stylesheet" href="/static/panel/css/stat.css"/>
<div class="stat_component">
    <div class="header_bar">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">今日分享</b></div>
        <table width="100%">
            <tbody>
            <tr class="title">
                <th></th>
                <th>参与用户数</th>
                <th>分享总数</th>
                <th>分享动态数</th>
                <th>邀请好友数</th>
                <th>名片数</th>
                <th>分享回链</th>
                <th></th>
            </tr>
            <tr class="highlight">

                <td class="normal">今日</td>
                <?php foreach ($data['today'] as $i => $item) {
                    if ($i == 'share_user') continue; ?>
                    <td><?php echo $item ?></td>
                <?php } ?>
            </tr>
            <tr class="">
                <td class="normal">昨日</td>
                <?php foreach ($data['yesterday'] as $i => $item) {
                    if ($i == 'share_user') continue; ?>
                    <td><?php echo $item ?></td>
                <?php } ?>
            </tr>
            <tr class="expect_today">
                <td class="normal">预计今日</td>
                <?php foreach ($data['expect'] as $i => $item) {
                    ?>
                    <td><?php echo $item > $data['yesterday'][$i] ? '<i class="fa fa-arrow-up green"></i>' : ($item == $data['yesterday'][$i] ? '' : '<i class="fa fa-arrow-down red"></i>') ?><?php echo $item ?></td>
                <?php } ?>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="content_wrap left">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">总分享统计</b></div>
        <div class="main" id="total" style="width: 100%; height: 320px"></div>
    </div>
    <div class="content_wrap right">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">动态分享</b></div>
        <div class="main" id="discuss" style="width: 100%; height: 320px"></div>
    </div>
    <div class="content_wrap left">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">邀请好友</b></div>
        <div class="main" id="invite" style="width: 100%; height: 320px"></div>
    </div>
    <div class="content_wrap right">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">名片</b></div>
        <div class="main" id="user" style="width: 100%; height: 320px"></div>
    </div>
</div>

<script type="text/javascript" src="/static/panel/js/echarts/echarts.min.js"></script>
<script type="text/javascript">
    seajs.use('app/panel/stat/panel.share', function (api) {
        api.shareChart();
    })
</script>