<link rel="stylesheet" href="/srv/static/panel/css/stat.css"/>
<link rel="stylesheet" href="/srv/static/panel/css/stat2.css?v=1"/>
<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">

<style>
    label.line {
        color: #666;
        padding: 0 2px;
    }

    table.list td {
        text-align: left !important;
    }
</style>
<div class="stat_component">
    <div class="header_bar">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;"> <i
                    class="fa fa-keyboard-o"></i> 昨日统计</b></div>
        <table width="100%">
            <tbody>
            <tr class="title">
                <th></th>
                <th>发红包总/真实/机器 <b>【人数】</b></th>
                <th>发出红包总/真实/机器 <b>【金额】</b></th>
                <th>发出的红包总/真实/机器 <b>【个数】</b></th>
                <th>抢红包总/真实/机器 <b>【用户数】</b></th>
                <th>抢到红包总/真实/机器 <b>【金额】</b></th>
                <th>抢到的红包总/真实/机器 <b>【个数】</b></th>
                <th></th>
            </tr>
            <tr class="highlight">
                <td class="normal">昨日</td>
                <td><?php echo $data['today']['send_person_count'] . "<label class='line'>/</label>" . $data['today']['send_person_real_count'] . "<label class='line'>/</label>" . $data['today']['send_person_robot_count'] ?></td>
                <td>
                    ￥<?php echo sprintf("%.2f", $data['today']['send_total_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['today']['send_real_user_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['today']['send_robot_user_money'] / 100) ?></td>
                <td><?php echo $data['today']['send_person_count'] . "<label class='line'>/</label>" . $data['today']['send_person_real_count'] . "<label class='line'>/</label>" . $data['today']['send_person_robot_count'] ?></td>

                <td><?php echo $data['today']['pick_person_count'] . "<label class='line'>/</label>" . $data['today']['pick_person_real_count'] . "<label class='line'>/</label>" . $data['today']['pick_person_robot_count'] ?></td>

                <td>
                    ￥<?php echo sprintf("%.2f", $data['today']['pick_total_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['today']['pick_real_user_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['today']['pick_robot_user_money'] / 100) ?></td>
                <td><?php echo $data['today']['pick_total_count'] . "<label class='line'>/</label>" . $data['today']['pick_real_user_count'] . "<label class='line'>/</label>" . $data['today']['pick_robot_user_count'] ?></td>
            </tr>
            <tr class="">
                <td class="normal">前日</td>
                <td><?php echo $data['yesterday']['send_person_count'] . "<label class='line'>/</label>" . $data['yesterday']['send_person_real_count'] . "<label class='line'>/</label>" . $data['yesterday']['send_person_robot_count'] ?></td>
                <td>
                    ￥<?php echo sprintf("%.2f", $data['yesterday']['send_total_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['yesterday']['send_real_user_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['yesterday']['send_robot_user_money'] / 100) ?></td>
                <td><?php echo $data['yesterday']['send_person_count'] . "<label class='line'>/</label>" . $data['yesterday']['send_person_real_count'] . "<label class='line'>/</label>" . $data['yesterday']['send_person_robot_count'] ?></td>

                <td><?php echo $data['yesterday']['pick_person_count'] . "<label class='line'>/</label>" . $data['yesterday']['pick_person_real_count'] . "<label class='line'>/</label>" . $data['yesterday']['pick_person_robot_count'] ?></td>

                <td>
                    ￥<?php echo sprintf("%.2f", $data['yesterday']['pick_total_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['yesterday']['pick_real_user_money'] / 100) . "<label class='line'>/</label>" . sprintf("%.2f", $data['yesterday']['pick_robot_user_money'] / 100) ?></td>
                <td><?php echo $data['yesterday']['pick_total_count'] . "<label class='line'>/</label>" . $data['yesterday']['pick_real_user_count'] . "<label class='line'>/</label>" . $data['yesterday']['pick_robot_user_count'] ?></td>

            </tr>
            </tbody>
        </table>
    </div>
    <div class="content_wrap left" style="height: 500px;width: 99%;max-width:100%">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;"><i class="fa fa-user-o"></i>
                用户统计</b></div>
        <div id="filters" class="filters">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">
                    <span class="l stat_label">时间：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <a href="javascript:;" data-id="7" data-type="user" class="trackable cur">最近7天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="30" data-type="user" class="trackable">最近30天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="custom" data-type="user" class="trackable">自定义</a>
                    </div>
                    <div class="select-bar-item l time_filter" style="display: none"><input type="text"
                                                                                            class="time start"
                                                                                            id="start" data-id="start"
                                                                                            readonly
                                                                                            style="border-radius: 10px;">
                        <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                        <span class="split_line">-</span>
                        <input type="text" data-id="end" class="time end" id="end" readonly>
                        <span class="time_picker" data-id="end"> <i class="fa fa-calendar-check-o"></i></span>

                    </div>
                </div>
            </div>
        </div>
        <div class="main" id="user"
             style="width: 70%; height: 320px;border-left: 1px dotted #e4e4e4;float: right"></div>
        <table class="list user" style="width: 25%;float: left;margin-left: 1%">
            <thead>
            <tr class="head">
                <th>说明</th>
                <th>天数</th>
                <th>总人数</th>
                <th>平均人数</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="">发红包人数</td>
                <td class="send"></td>
                <td class="send"></td>
                <td class="send"></td>
            </tr>
            <tr>
                <td>领红包人数</td>
                <td class="pick"></td>
                <td class="pick"></td>
                <td class="pick"></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="content_wrap left" style="height: 500px;width: 99%;max-width:100%">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;"><i class="fa fa-money"></i>
                金额统计</b></div>
        <div id="filters" class="filters">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">
                    <span class="l stat_label">时间：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <a href="javascript:;" data-id="7" data-type="money" class="trackable cur">最近7天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="30" data-type="money" class="trackable">最近30天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="custom" data-type="money" class="trackable">自定义</a>
                    </div>
                    <div class="select-bar-item l time_filter" style="display: none"><input type="text"
                                                                                            class="time start"
                                                                                            id="start1" data-id="start1"
                                                                                            readonly
                                                                                            style="border-radius: 10px;">
                        <span class="time_picker" data-id="start1"><i class="fa fa-calendar-check-o"></i></span>
                        <span class="split_line">-</span>
                        <input type="text" data-id="end1" class="time end" id="end1" readonly>
                        <span class="time_picker" data-id="end1"> <i class="fa fa-calendar-check-o"></i></span>

                    </div>
                </div>
            </div>
        </div>
        <div class="main" id="money"
             style="width: 70%; height: 320px;border-left: 1px dotted #e4e4e4;float: right"></div>
        <table class="list money" style="width: 25%;float: left;margin-left: 1%">
            <thead>
            <tr class="head">
                <th>说明</th>
                <th>天数</th>
                <th>红包总额</th>
                <th>每天平均额</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="">发红包总金额</td>
                <td class="cl0"></td>
                <td class="cl0"></td>
                <td class="cl0"></td>
            </tr>
            <tr>
                <td>领红包总金额</td>
                <td class="cl1"></td>
                <td class="cl1"></td>
                <td class="cl1"></td>
            </tr>
            <tr>
                <td>机器人发红包总金额</td>
                <td class="cl2"></td>
                <td class="cl2"></td>
                <td class="cl2"></td>
            </tr>
            <tr>
                <td>真实用户发红包总金额</td>
                <td class="cl3"></td>
                <td class="cl3"></td>
                <td class="cl3"></td>
            </tr>
            <tr>
                <td>真实用户领红包总金额</td>
                <td class="cl4"></td>
                <td class="cl4"></td>
                <td class="cl4"></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="content_wrap left" style="height: 500px;width: 99%;max-width:100%">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;"><i class="fa fa-book"></i>
                红包个数统计</b></div>
        <div id="filters" class="filters">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">
                    <span class="l stat_label">时间：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <a href="javascript:;" data-id="7" data-type="package_count" class="trackable cur">最近7天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="30" data-type="package_count" class="trackable">最近30天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="custom" data-type="package_count" class="trackable">自定义</a>
                    </div>
                    <div class="select-bar-item l time_filter" style="display: none"><input type="text"
                                                                                            class="time start"
                                                                                            id="start2" data-id="start2"
                                                                                            readonly
                                                                                            style="border-radius: 10px;">
                        <span class="time_picker" data-id="start2"><i class="fa fa-calendar-check-o"></i></span>
                        <span class="split_line">-</span>
                        <input type="text" data-id="end2" class="time end" id="end2" readonly>
                        <span class="time_picker" data-id="end2"> <i class="fa fa-calendar-check-o"></i></span>

                    </div>
                </div>
            </div>
        </div>
        <div class="main" id="package_count"
             style="width: 70%; height: 320px;border-left: 1px dotted #e4e4e4;float: right"></div>
        <table class="list package_count" style="width: 25%;float: left;margin-left: 1%">
            <thead>
            <tr class="head">
                <th>说明</th>
                <th>天数</th>
                <th>红包总个数</th>
                <th>平均红包个数</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="">发红包总个数</td>
                <td class="cl0"></td>
                <td class="cl0"></td>
                <td class="cl0"></td>
            </tr>
            <tr>
                <td>领红包总个数</td>
                <td class="cl1"></td>
                <td class="cl1"></td>
                <td class="cl1"></td>
            </tr>
            <tr>
                <td>机器人发红包总个数</td>
                <td class="cl2"></td>
                <td class="cl2"></td>
                <td class="cl2"></td>
            </tr>
            <tr>
                <td>真实用户发红包总个数</td>
                <td class="cl3"></td>
                <td class="cl3"></td>
                <td class="cl3"></td>
            </tr>
            <tr>
                <td>真实用户领红包总个数</td>
                <td class="cl4"></td>
                <td class="cl4"></td>
                <td class="cl4"></td>

            </tr>
            </tbody>
        </table>
    </div>
    <div class="content_wrap left" style="height: 600px;width: 99%;max-width:100%;margin-bottom: 100px">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;"><i class="fa fa-book"></i>
                领红包统计</b></div>
        <div id="filters" class="filters">
            <div class="control-bar-wrapper clearfix" id="control-bar-wrapper">
                <div class="control-bar bg-iframe l" id="control-bar">
                    <span class="l stat_label">时间：</span>
                    <div class="l date-select-bar" id="date-select-bar">
                        <a href="javascript:;" data-id="today" data-type="pick_count"
                           class="trackable date-bar-single-day cur">今天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="yesterday" data-type="pick_count"
                           class="trackable date-bar-single-day">昨天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="before_yesterday" data-type="pick_count"
                           class="trackable date-bar-single-day">前天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="7" data-type="pick_count" class="trackable">最近7天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="30" data-type="pick_count" class="trackable">最近30天</a>
                        <span class="seprator"></span>
                        <a href="javascript:;" data-id="custom" data-type="pick_count" class="trackable">自定义</a>
                    </div>
                    <div class="select-bar-item l time_filter" style="display: none"><input type="text"
                                                                                            class="time start"
                                                                                            id="start3" data-id="start3"
                                                                                            readonly
                                                                                            style="border-radius: 10px;">
                        <span class="time_picker" data-id="start3"><i class="fa fa-calendar-check-o"></i></span>
                        <span class="split_line">-</span>
                        <input type="text" data-id="end3" class="time end" id="end3" readonly>
                        <span class="time_picker" data-id="end3"> <i class="fa fa-calendar-check-o"></i></span>

                    </div>
                </div>
            </div>
        </div>
        <table class="list pick_count" style="width: 80%;float: left;margin-left: 1%;">
            <thead>
            <tr class="head">
                <th>用户ID</th>
                <th>用户名</th>
                <th>天数</th>
                <th style="width: 150px" class="arrow" data-sort="" data-order="pick_count">
                    <span class="text">领取个数</span>
                <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span></th>
                <th style="width: 150px" class="arrow" data-sort="" data-order="pick_money">
                    <span class="text">领取金额</span>
                <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span></th>
                <th>平均个数</th>
                <th>平均金额</th>
            </tr>
            </thead>
            <tbody class="content">

            </tbody>
        </table>
        <!--        <table class="list pick_money" style="width: 40%;float: left;margin-left: 1%">-->
        <!--            <thead>-->
        <!--            <tr class="head">-->
        <!--                <th>用户ID</th>-->
        <!--                <th>用户名</th>-->
        <!--                <th>天数</th>-->
        <!--                <th>领取金额</th>-->
        <!--                <th>平均值</th>-->
        <!--            </tr>-->
        <!--            </thead>-->
        <!--            <tbody class="content">-->
        <!---->
        <!--            </tbody>-->
        <!--        </table>-->
    </div>
</div>
<script type="text/javascript" src="/srv/static/panel/js/echarts/echarts.min.js"></script>
<script type="text/javascript">
    seajs.use('app/panel/stat/panel.squarePackage.js?v=1.2.5', function (api) {
        api.load();
    })
</script>
