<script type="text/javascript" src="/static/panel/js/echarts/echarts.min.js"></script>
<script type="text/javascript" src="/static/panel/js/echarts/themes/blue.js"></script>
<div class="tabbable">
    <ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
        <li class="active">
            <a data-toggle="tab" href="#home4">最近一周</a>
        </li>

        <li class="">
            <a data-toggle="tab" href="#profile4">最近一个月</a>
        </li>

        <li class="">
            <a data-toggle="tab" href="#dropdown14">最近一年</a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="home4" class="tab-pane active">
            <div id="week" style="width: 600px;height:300px;"></div>
        </div>

        <div id="profile4" class="tab-pane">
            <div id="month" style="width:800px;height:300px;overflow: hidden"></div>
        </div>

        <div id="dropdown14" class="tab-pane ">
            <div id="year" style="width:800px;height:300px;overflow: hidden"></div>
        </div>
    </div>
</div>
<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<script type="text/javascript">
    $(document).ready(function () {
        var myChart_week = echarts.init(document.getElementById('week'), 'blue');
        var myChart_month = echarts.init(document.getElementById('month'), 'blue');
        var myChart_year = echarts.init(document.getElementById('year'), 'blue');

        week_option = {
            title: {
                text: '用户登录周统计'
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                    type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
         /*   legend: {
                data: ['登录用户']
            },*/
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true,
            },
            xAxis: [
                {
                    type: 'category',
                    data: [<?php echo $week_date['labels']?>]
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name: '登录用户',
                    type: 'bar',
                    data: [<?php echo implode(',', $week_date['values'])?>],
                    /*markLine: {
                     lineStyle: {
                     normal: {
                     type: 'dashed'
                     }
                     },
                     data: [
                     [{type: 'min'}, {type: 'max'}]
                     ]
                     },*/
                    itemStyle: {
                        normal: {
                            color: function (params) {
                                // build a color map as your need.
                                var colorList = [
                                    "#C1232B", "#B5C334", "#FCCE10", "#E87C25", "#27727B",
                                    "#FE8463", "#9BCA63"
                                ];
                                return colorList[params.dataIndex]
                            }
                        }
                    }
                }
            ]
        };
        month_option = {
            title: {
                text: '用户登录按月统计'
            },
            tooltip: {
                trigger: 'axis'
            },
        /*    legend: {
                data: ['注册用户']
            },*/
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true,
            },
            xAxis: [
                {
                    type: 'category',
                    boundaryGap: false,
                    data: [<?php echo $month_date['labels']?>]
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name: '登录会员数',
                    type: 'line',
                    stack: '总量',
                    areaStyle: {normal: {}},
                    data: [<?php echo implode(',', $month_date['values'])?>]
                },
            ]
        };
        year_option = {
            title: {
                text: '用户登录年统计'
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                    type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
         /*   legend: {
                data: ['登录用户']
            },*/
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true,
            },
            xAxis: [
                {
                    type: 'category',
                    data: [<?php echo $year_date['labels']?>]
                }
            ],
            yAxis: [
                {
                    type: 'value'
                }
            ],
            series: [
                {
                    name: '登录用户',
                    type: 'bar',
                    data: [<?php echo implode(',', $year_date['values'])?>],
                    /*markLine: {
                     lineStyle: {
                     normal: {
                     type: 'dashed'
                     }
                     },
                     data: [
                     [{type: 'min'}, {type: 'max'}]
                     ]
                     },*/
                    itemStyle: {
                        normal: {
                            color: function (params) {
                                // build a color map as your need.
                                var colorList = [
                                    "#C1232B", "#B5C334", "#FCCE10", "#E87C25", "#27727B",
                                    "#FE8463", "#9BCA63"
                                ];
                                return colorList[params.dataIndex]
                            }
                        }
                    }
                }
            ]
        };


        // 使用刚指定的配置项和数据显示图表。
        myChart_week.setOption(week_option);
        myChart_month.setOption(month_option);
        myChart_year.setOption(year_option);

    })


</script>