<link rel="stylesheet" href="/srv/static/panel/css/stat.css">
<link rel="stylesheet" href="/srv/static/panel/css/stat2.css">
<link rel="stylesheet" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/ace/js/date-time/moment.min.js"></script>
<script src="/srv/static/panel/js/echarts/echart-all.2.2.7.min.js"></script>

<div class="stat_component" >

    <div class="control-bar-wrapper clearfix" id="control-bar-wrapper" style="background-color:white;margin-bottom:8px;margin-left:0.5%;margin-right:0.5%">
        <div class="control-bar l " style="margin-right:20px">
            <span class="l stat_label" >虚拟币类型：</span>
            <div class="l date-select-bar type-btn " id="date-select-bar">
                <a href="javascript:;"  data-type=0 class="trackable date-bar-single-day cur">龙钻</a>
                <span class="seprator"></span>
                <a href="javascript:;"  data-type=1 class="trackable date-bar-single-day">收益</a>

            </div>
        </div>
        <div class="control-bar bg-iframe l " >
            <span class="l stat_label">统计周期：</span>
            <div class="l date-select-bar date-btn" id="date-select-bar">
                <a href="javascript:;" data-day="3"  class="trackable date-bar-single-day cur">3天</a>
                <span class="seprator"></span>
                <a href="javascript:;" data-day="7"  class="trackable ">7天</a>
                <span class="seprator"></span>
                <a href="javascript:;" data-day="30"  class="trackable">30天</a>
                <span class="seprator"></span>
                <a href="javascript:;" data-day="custom"  class="trackable">自定义</a>
            </div>
            <div class="left date-selected " style="margin-left:10px;height:26px;line-height: 26px;color:#787a7d">
                <span> 【 </span>
                <span style="">2018/01/03</span> -
                <span>2018/03/21</span>
                <span>】</span>
            </div>

            <div class="select-bar-item l time_filter" style="display: none">
                <input type="text" class="time start" id="start" data-id="start" readonly="" style="border-radius: 10px;">
                <span class="time_picker" data-id="start"><i class="fa fa-calendar-check-o"></i></span>
                <span class="split_line">-</span>
                <input type="text" data-id="end" class="time end" id="end" readonly="">
                <span class="time_picker" data-id="end"> <i class="fa fa-calendar-check-o"></i></span>
                <a href="javascript::" class="btn btn-xs btn-primary query-btn" style="padding:0 5px;margin-left:10px;">查询</a>

            </div>
        </div>

        <div style="float:left;height:26px;line-height: 26px;margin-left:50px;font-weight:bold" class="red summary-box">
            <span>总产生：<span class="income-total" style="min-width:50px;display:inline-block;text-align: right;"></span><span style="margin-left:10px">个</span></span>
            <span style="margin-left:30px">总消耗：<span class="defray-total" style="min-width:50px;display:inline-block;text-align: right;"></span><span style="margin-left:10px">个</span></span>
        </div>
    </div>
    <div class="content_wrap left">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">各渠道产生趋势图</b></div>
        <div class="main_wrap">
            <div class="loading" style="display: none;"><img src="/srv/static/panel/images/admin/loading2.gif">&nbsp;&nbsp;数据加载中...</div>
            <div class="main" id="income-line" style="width:100%;height:320px" ></div>
        </div>
    </div>
    <div class="content_wrap right">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">各渠道产生占比</b>
        </div>
        <div class="main_wrap">
            <div class="loading" style="display: none;"><img src="/srv/static/panel/images/admin/loading2.gif">&nbsp;&nbsp;数据加载中...</div>
            <div class="main" id="income-pie" style="width:100%;height:320px"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="content_wrap  " style="margin-left:0.5%;width:99%;max-width:99%">
        <div class="page-header" style="margin-bottom: 2px"><b style="padding-left: 10px;">产生/消耗趋势</b>
        </div>
        <div class="main_wrap">
            <div class="loading" style="display: none;"><img src="/srv/static/panel/images/admin/loading2.gif">&nbsp;&nbsp;数据加载中...</div>
            <div class="main" id="income-defray-line" style="width:100%;height:320px"></div>
        </div>
    </div>


</div>
<script>
    seajs.use('app/panel/stat/panel.virtualCoin.js?1.0.7',function (api) {
        api.reload();
    });
</script>