<link rel="stylesheet" type="text/css" href="/srv/static/panel/js/tools/datetimepicker/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" type="text/css" href="/srv/static/panel/ali_iconfont/iconfont.css?v=1.0">
<script src="/srv/static/panel/ali_iconfont/iconfont.js?v=1.0"></script>
<style>
    .icon {
        width: 1em;
        height: 1em;
        vertical-align: -0.15em;
        fill: currentColor;
        overflow: hidden;
        display: inline-block;
    }

</style>
<!--<form action="" method="get"-->
<!--      style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px; line-height: 50px;">-->
<!--    &nbsp;<label for="name">时间:</label>-->
<!--    <input type="text" id="start" value="--><?php //echo $start; ?><!--" placeholder="开始时间" name="start"-->
<!--           data-date-format="yyyy-mm-dd"/>-->
<!--    - <input type="text" id="end" value="--><?php //echo $end; ?><!--" placeholder="结束时间" name="end"-->
<!--             data-date-format="yyyy-mm-dd"/>-->
<!--    <input type="submit" class="btn btn-primary btn-sm" value="搜索">-->
<!--</form>-->
<div class="tabs">
    <a href="<?php echo $this->uri->setUrl(['type' => 0], ['p']); ?>"
       class="tab <?php echo $type == 0 ? 'active' : ''; ?>">今日榜单</a>
    <a href="<?php echo $this->uri->setUrl(['type' => 1], ['p']); ?>"
       class="tab <?php echo $type == 1 ? 'active' : ''; ?>">周榜</a>
</div>
<table id="article-list" class=' list'>
    <thead>
    <tr class="head">
        <th style='width:36px'>ID</th>
        <!-- <th style='width:60px'>批量</th>-->
        <th style='width:150px'>发布人</th>
        <th style='width:160px'>
            发布时间
        </th>
        <th>标签</th>
        <th style='width:200px'>文本内容</th>
        <!--    <th style='width:300px'>审核</th>-->
        <th style='width:60px'>类型</th>
        <th style='width:60px'>
            红包
        </th>
        <th style='width:50px'>状态</th>
        <th style='width:70px'>
            点赞
        </th>
        <th style='width:70px'>
            收藏
        </th>
        <th style='width:70px'>
            评论
        </th>
        <th style='width:70px'>
            转发
        </th>
        <th style='width:70px'>
            阅读
        </th>
        <th style='width:70px'>
            举报
        </th>
        <th style='width:70px'>
            热度
        </th>
        <th style='width:70px'>
            榜单日
        </th>
        <th>操作</th>
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>

    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        $content = \Util\FilterUtil::unPackageContentTag($item['content'], 0, "/panel/users/detail?user_id=");
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">
            <th class='name'><?php echo $item['id']; ?></th>
            <!--   <td class="center"><label>
                    <input type="checkbox" class="chk ace" data-id="<?php /*echo $item['id']; */ ?>"/>
                    <span class="lbl"></span>
                </label>
            </td>-->
            <td><?php echo $item['user_id'] . '【' . $users[$item['user_id']]['username'] . '】'; ?></td>
            <td><?php echo date('Y-m-d H:i:s', $item['created']); ?></td>
            <td>
                <?php echo $item['tags_name']; ?>
            </td>
            <td style="width: 200px;word-break: break-all;">
                <?php if ($item['share_original_type'] == \Services\Social\SocialManager::TYPE_DISCUSS || $item['share_original_type'] == '') {

                    ?>
                    <?php echo mb_strlen($item['content'], 'utf-8') > 20 ? mb_substr($content, 0, 20, 'utf-8') . '...<a target="_blank"  href="javascript:;" class="newTarget" data-title="动态详情" data-id="discuss_detail_' . $item['id'] . '" data-href="/panel/discuss/detail/' . $item['id'] . '">查看更多</a>' : $content; ?>

                <?php } else {
                    if (empty($item['parent_item_id_str'])) {
                        $content = json_decode($item['content'])->content;
                    } else {
                        $content = $item['content'];
                    }
                    ?>

                    <?php echo mb_strlen($content, 'utf-8') > 20 ? mb_substr($content, 0, 20, 'utf-8') . '...<a target="_blank" href="javascript:;" class="newTarget" data-title="动态详情" data-id="discuss_detail_' . $item['id'] . '" data-href="/panel/discuss/detail/' . $item['id'] . '">查看更多</a>' : $content; ?>
                <?php } ?>

            </td>
            <td>

                <?php if ($item['media_type'] == 1) {
                    echo '<label class="badge badge-inverse">纯文本</label>';
                } else if ($item['media_type'] == 2) {
                    echo '<label class="badge badge-pink">小视频</label>';
                } else if ($item['media_type'] == 3) {
                    echo '<label class="badge badge-info">图片</label>';
                } else if ($item['media_type'] == 4) {
                    echo '<label class="badge badge-purple">音频</label>';
                };

                ?>
            </td>
            <td>
                <?php if ($item['package_id']) { ?>
                    <svg class="icon" style="font-size: 25px;" aria-hidden="true">
                        <use xlink:href="#icon-hongbao"></use>
                    </svg>
                <?php } ?>
            </td>
            <td>

                <?php if ($item['status'] == 0) {
                    echo "<label class='badge badge-danger'>已被系统屏蔽</label>";
                } else if ($item['status'] == 1) {
                    echo "<label class='badge badge-success'>正常</label>";
                } else if ($item['status'] == 2) {
                    echo "<label class='badge badge-gray'><i class='fa fa-trash'></i> 用户已删除</label>";
                }; ?>
            </td>
            <td>
                <?php echo $item['like_cnt']; ?>
            </td>
            <td>
                <?php echo $item['fav_cnt']; ?>
            </td>
            <td>
                <?php echo $item['comment_cnt'] > 0 ? "<a  href='javascript:;' class='newTarget' data-title='评论列表' data-id='comment_list_" . $item['id'] . "' data-href='/panel/discuss/comment/" . $item['id'] . "' target='_blank'>" . $item['comment_cnt'] . "</a>" : 0; ?>
            </td>
            <td>
                <?php echo $item['forward_cnt']; ?>
            </td>
            <td>
                <?php echo $item['view_cnt']; ?>
            </td>
            <td>
                <?php echo $item['report_cnt']; ?>
            </td>
            <td>
                <?php echo $item['order_num']; ?>
            </td>
            </td>
            <td>
                <?php echo $item['ymd']; ?>
            </td>
            <td>
                <a target="_blank"
                   href="javascript:;"
                   data-href="/panel/discuss/detail/<?php echo $item['id']; ?>/<?php echo $where ?>"
                   data-title="动态详情"
                   data-id="discuss_detail_<?php echo $item['id']; ?>"
                   class="btn btn-minier btn-primary newTarget">详情</a>
                <span data-url="http://wap.klgwl.com/discuss/detail?item_id=<?php echo $item['id'] ?>&from=panel"
                      data-original-url="http://wap.klgwl.com/discuss/detail?item_id=<?php echo $item['id'] ?>"
                      class="btn btn-minier btn-primary btnScan">H5</span>
               <span class="btn btn-minier btn-gray btnBillboardRemove" data-id="<?php echo $item['id'] ?>"><i
                       class="fa fa-arrow-down"></i> 取消榜单</span>
            </td>
        </tr>
        <?php
    }
    } else {
        ?>
        <tr>
            <td colspan="17">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--  <tr class="showpage">
          <th class="name">操作</th>
          <td colspan="17">
                  <span>
                      [ <a href="javascript:;" class="selectAll">全选</a> ]
                      [ <a href="javascript:;" class="selectNone">全不选</a> ]
                      [ <a href="javascript:;" class="selectInvert">反选</a> ]
                      <a class="btn-light delAllSelected" href="javascript:;">批量屏蔽</a>
                  </span>
          </td>
      </tr>-->
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="17">
            <?php \Util\Pagination::instance($this->view)->display($this->view); ?>
        </td>
    </tr>
</table>
<div class="" id="app-frame" style=" background-color:white; position: fixed;right: 0;z-index: 99999;top:0;
       /* box-shadow:0 0 5px rgba(0,0,0,0.3);*/
        display: none;">
    <p style="background: #fff;height: 36px;line-height: 36px;padding: 0 8px;">
        <a href="javascript:;" class="close-app">关闭预览</a> | <a href="javascript:;" class="refresh-app">重新预览</a> | <a
            href="javascript:;" data-clipboard-text="" class="copy-link">复制链接地址</a>
    </p>
    <iframe name="appFrame" id="appFrame"
            src=""
            style="width: 400px;height: 600px;margin: 0;padding: 0;border: 2px solid #e4e4e4;border-top: 1px solid #e4e4e4;border-radius:0 0 10px 10px;"></iframe>
</div>

<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/panel/js/tools/Url.js"></script>
<script>
    $('[data-rel=tooltip]').tooltip();
    seajs.use('app/panel/discuss/discuss.edit.js?v=1.1.3', function (api) {
        api.del();
        api.recommend();
        api.hideTag();
        api.btnBillboard();
    });
    //  var receive_start_val;
    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
    $('#end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
</script>
<script type="text/javascript" src="/srv/static/panel/js/tools/clipboard/clipboard.min.js"></script>

<script>
    var clipboard = new Clipboard('.copy-link', {});
    clipboard.on('success', function (e) {
        alert("复制成功");
        /* var sel = "#" + e.text;
         $(sel).tooltip('show');
         setTimeout(function () {
         // $(sel).tooltip('hide');
         }, 1500);*/
    });
    $(".btnScan").on('click', function () {
        var url = $(this).attr('data-url');
        $(".copy-link").attr('data-clipboard-text', $(this).attr('data-original-url'));
        $('#appFrame').attr('src', url);
        $('#app-frame').show();
    })
    $("#app-frame .close-app").click(function () {
        $('#app-frame').hide();
    });

    $("#app-frame .refresh-app").click(function () {
        $('#appFrame').attr('src', $('#appFrame').attr('src'));
    });
</script>
