<style>
    .comment_list {
        margin: 0;

    }

    .comment_list .comment_item {
        clear: both;
        width: 100%;
        margin-bottom: 10px;
        padding: 5px;
        /*   border-bottom: 1px dotted #e4e4e4;*/
        height: auto;
        overflow: hidden;
        line-height: 30px;
    }

    .comment_list .comment_item .info {
        /*   float: left;*/
        width: 100%;
        clear: both;
        height: auto;
        overflow: hidden;
    }

    .comment_list .comment_item .info .avatar {
        float: left;
        width: 50px;
        height: 50px;
        border-radius: 100%;
    }

    .comment_list .reply_avatar {
        width: 50px;
        height: 50px;
        border-radius: 100%;
    }

    .comment_list .comment_item .info .user {
        float: left;
        margin-left: 10px;
        width: 80%;
    }

    .comment_list .comment_item .info .user .sex, .comment_list .comment_item .info .user .hot {
        background-color: #80DFFA;
        padding: 2px 5px;
        color: white;
        font-size: 11px;
        margin-left: 5px;
        border-radius: 3px;
    }

    .comment_list .comment_item .info .user .female {
        background-color: #FEB3C5;
    }

    .comment_list .comment_item .info .user .hot {
        background-color: #FF2F2F;
    }

    .comment_list .comment_item .content_img {
        width: 30px;
        height: 30px;
        border-radius: 2px;
    }

    .reply_list {
        margin-left: 80px;
        background-color: #efefef;
        padding: 20px;
        min-width: 300px;
        height: auto;
        overflow: visible;
        border-radius: 5px;
    }

    #wrapper {
        width: 100%;
        height: 100%;
        overflow: hidden;
    }

    #scroller-pullDown, #scroller-pullUp {
        background: #fff;
        height: 40px;
        line-height: 40px;
        padding: 5px 10px;
        border-bottom: 1px solid #ccc;
        font-weight: bold;
        font-size: 14px;
        color: #888;
        text-align: center;
        position: absolute;
        left: 0px;
        width: 100%;
    }

    #scroller-pullDown {
        top: -40px;
    }

    #scroller-pullUp {
        bottom: -40px;
    }

    #scroller-pullDown .pull-up-msg, #scroller-pullUp .pull-down-msg {
        padding-left: 20px;
    }

    #scroller-pullDown .pull-down-icon, #scroller-pullUp .pull-up-icon {
        display: inline-block;
        color: dodgerblue;
        font-size: 1.4em;
        -webkit-transform: rotate(0deg);
        -webkit-transition-property: -webkit-transform;
        -webkit-transition-duration: 500ms;
    }

    #scroller-pullDown .pull-down-icon.reverse_icon, #scroller-pullUp .pull-up-icon.reverse_icon {
        -webkit-transform: rotate(-180deg);
    }

    #scroller {
        -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
        -webkit-transform: translateZ(0);
        -moz-transform: translateZ(0);
        -ms-transform: translateZ(0);
        -o-transform: translateZ(0);
        transform: translateZ(0);
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-text-size-adjust: none;
        -moz-text-size-adjust: none;
        -ms-text-size-adjust: none;
        -o-text-size-adjust: none;
        text-size-adjust: none;
    }

    .item_content {
        cursor: pointer;
        position: relative;
        display: inline-block;
        overflow: visible;
    }

    .item_content:hover {
        color: #00a0c7;
    }

    .item_content:hover .handle {
        color: darkred;
    }

    .handle {
        position: absolute;
        width: 80px;
        height: auto;
        padding: 5px;
        display: none;
        text-align: center;
        z-index: 10;
        background-color: #fff;
        border: 1px solid #efefef;
        border-radius: 2px;
        overflow: hidden;
    }

    .handle .handle_item {
        background-color: #e4e4e4;
        border-radius: 2px;
        padding: 0;
    }

    .handle .handle_item span {
        font-size: 14px;
    }

    .handle .handle_item:hover {
        color: darkred;
    }

    .handle .handle_item:hover span {
        font-size: 15px;
    }
</style>
<div class="page-header">
    <h1><i class="fa fa-th-list"></i> 评论列表【<?php echo $discuss['comment_cnt'] ?>】
        <span class="pull-right">
          <!--  <span class="btn-group">-->

            <!--            </span>
            -->        </span>
    </h1>
    <!-- /.col-lg-12 -->
</div>
<div class="handle"
     style="">
    <p class="handle_item btnRemove" data-type="" data-id=""><span>屏 蔽</span></p>

</div>
<div
    style="width: 100%;height:700px;border: 1px solid #e4e4e4;border-radius: 5px;padding: 10px;background-color: #fff;overflow: hidden">
    <div id="wrapper" style="height:700px;">
        <div id="scroller"
             style="transition-timing-function: cubic-bezier(0.1, 0.57, 0.1, 1); transition-duration: 0ms; transform: translate(0px, 0px) translateZ(0px);">
            <div id="scroller-pullDown">
                <span id="down-icon" class=" fa fa-angle-double-down pull-down-icon reverse_icon"></span>
                <span id="pullDown-msg" class="pull-down-msg">下拉加载</span>
            </div>
            <div id="scroller-content">

                <ul style="width: 100%;height: auto;overflow: hidden" class="comment_list">
                    <!-- <?php /*if ($comment['hot_list']) { */ ?>
                        <?php /*foreach ($comment['hot_list'] as $item) { */ ?>
                            <li class="comment_item">
                                <div class="info">
                                    <img
                                        src="<?php /*echo $item['avatar'] */ ?>?x-oss-process=image/resize,m_fill,h_100,w_100"
                                        style="" class="avatar">

                                    <div style="" class="user">
                                        <p><?php /*echo $item['username'] */ ?>
                                            <?php /*if ($item['sex'] == 1) { */ ?>
                                                <span class="male sex"><i
                                                        class="fa fa-mars"></i>  V<?php /*echo $item['grade'] */ ?></span>

                                            <?php /*} else { */ ?>
                                                <span class="female sex"><i
                                                        class="fa fa-venus"> V<?php /*echo $item['grade'] */ ?></i></span>
                                            <?php /*} */ ?>
                                            <span class="hot"><i class="fa fa-fire"></i> 热评</span>
                                        </p>
                                        <p><?php /*echo $item['show_time'] */ ?></p>
                                        <p><?php /*echo $item['content'] */ ?></p>
                                    </div>
                                </div>
                                <?php /*if ($item['reply_list']) { */ ?>
                                    <div class="reply_list">
                                        <?php /*foreach ($item['reply_list'] as $reply) { */ ?>
                                            <p>  <span
                                                    class="item_sy"><span
                                                        class="blue"><?php /*echo $reply['username']; */ ?></span> <em>回复</em> <span
                                                        class="blue"><?php /*echo $reply['to_username']; */ ?></span>:</span>
                                                <span><?php /*echo $reply['content']; */ ?></span></p>
                                        <?php /*} */ ?>
                                        <p><a href="/discuss/reply?item_id=<?php /*echo $item['comment_id']; */ ?>"
                                              class="check_all">共有<?php /*echo $item['reply_cnt'] */ ?>条回复<i></i></a>
                                        </p>
                                    </div>

                                <?php /*} */ ?>

                            </li>
                        <?php /*} */ ?>
                    --><?php /*} */ ?>
                    <?php if ($comment) { ?>
                        <?php foreach ($comment as $item) { ?>
                            <?php $this->partial('discuss/partial/comment') ?>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
            <div id="scroller-pullUp" style="display: none">
                <span id="up-icon" class=" fa fa-angle-double-up pull-up-icon"></span>
                <span id="pullUp-msg" class="pull-up-msg">上拉刷新</span>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/srv/static/panel/js/tools/iscroll.js"></script>
<link rel="stylesheet" href="/srv/static/panel/css/lightbox/lightbox.css"/>

<script src="/srv/static/panel/js/jquery/lightbox/lightbox.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        lightbox.option({
            albumLabel: '%1/%2',
            'resizeDuration': 200,
            "fadeDuration":0,
            "imageFadeDuration":0
        });
    })

</script>

<script>
    seajs.use('app/panel/panel.base', function (api) {
        $(function () {
            var upIcon = $("#up-icon"), //上拉
                downIcon = $("#down-icon"); //下拉
            var is_loading = false; //是否正在加载
            var item_id = "<?php echo $item_id?>";
            var limit = "<?php echo $limit?>";

            var current_last_id = "<?php echo $comment ? $comment[count($comment) - 1]['comment_id'] : 0?>"
            var current_first_id = "<?php echo $comment ? $comment[0]['comment_id'] : 0 ?>"
            var myScroll = new IScroll('#wrapper', {
                probeType: 3,
                'scrollbars': true,
                'mouseWheel': true,
                'interactiveScrollbars': true,
                'shrinkScrollbars': 'scale',
                'fadeScrollbars': true,
            });
            myScroll.on("scrollEnd", function () {
                if (this.y == 0) {
                    fresh(1);
                }
                else if (this.maxScrollY == this.y) {
                    fresh(2);
                }
            });
            myScroll.on("scroll", function () {
                var y = this.y,
                    maxY = this.maxScrollY - y,
                    downHasClass = downIcon.hasClass("reverse_icon"),
                    upHasClass = upIcon.hasClass("reverse_icon");

                if (y >= 40) {
                    !downHasClass && downIcon.addClass("reverse_icon");
                    return "";
                } else if (y < 40 && y > 0) {
                    downHasClass && downIcon.removeClass("reverse_icon");
                    return "";
                }

                if (maxY >= 40) {
                    !upHasClass && upIcon.addClass("reverse_icon");
                    return "";
                } else if (maxY < 40 && maxY >= 0) {
                    upHasClass && upIcon.removeClass("reverse_icon");
                    return "";
                }
            });

            myScroll.on("slideDown", function () {
                if (this.y > 40) {
                    fresh(1);
                    upIcon.removeClass("reverse_icon")
                }
            });

            myScroll.on("slideUp", function () {
                if (this.maxScrollY - this.y > 40) {
                    fresh(2);
                    upIcon.removeClass("reverse_icon")
                }
            });
            if (($("#scroller-content ul").height() >= 700)) {
                $("#scroller-pullUp").show();
            }

            $("#wrapper").on('mouseenter', '.item_content', function (e) {
                $(".handle").css({
                    'left': 0,
                    'bottom': $(this).height()
                }).show().appendTo($(this));
                $(".handle .btnRemove").attr('data-id', $(this).data('id')).attr('data-type', $(this).data('type'))
            }).on('mouseleave', '.item_content', function (e) {
                $(".handle").hide();
            }).on('mouseenter', '.handle', function (e) {
                $(this).show();
            }).on('mouseleave', '.handle', function (e) {
                $(this).hide();
            });
            $("#wrapper").on('click', ".btnRemove", function () {
                var type = $(this).data('type');
                var item_id = $(this).data('id');
                var __this = $(this);
                api.requestApi('/api/social/removeComment', {
                    type: type,
                    item_id: item_id
                }, function (res) {
                    if (res.result == 1) {
                        tip.showTip("ok", "屏蔽成功", 1000, function () {
                            //先移动操作层
                            var handle = $(".handle").clone();

                            //删除的是评论
                            if (type == 'comment') {
                                $(".comment_item[data-id='" + item_id + "']").remove();
                            }
                            //删除的是回复
                            else {
                                $(".reply_item[data-id='" + item_id + "']").remove();
                            }
                            handle.appendTo($(".page-content"));
                        });
                    }
                })
            });

            //回复加载

            $("#wrapper").on('click', '.loadMore', function () {
                var __this = $(this);
                api.requestApi('/api/discuss/replyList', {
                    last_id: __this.data('last-id'),
                    item_id: __this.data('comment-id'),
                    limit: limit
                }, function (res) {
                    if (res.result == 1) {
                        if (res.data.list.length > 0) {
                            $.each(res.data.list, function () {
                                $(".reply_item_list[data-id='" + __this.data('comment-id') + "']").append(this);
                            });
                            myScroll.refresh();
                            console.log(res.data.last_id);
                            __this.data('last-id', res.data.last_id);
                            console.log(__this.data('last-id'))
                            /*   myScroll.scrollTo(0, myScroll.maxScrollY, 1000);*/
                        } else {
                            __this.hide();
                        }

                    }
                }, false, true)

            });

            function fresh(type) {
                if (is_loading) {
                    return
                }
                is_loading = true;
                //下拉
                if (type == 1) {
                    api.requestApi('/api/discuss/commentList', {
                        item_id: item_id,
                        limit: limit,
                        first_id: current_first_id
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                var html = "";
                                for (var i in res.data.list) {
                                    html += res.data.list[i]
                                }
                                $("#scroller-content .comment_list").prepend(html);
                                myScroll.refresh();
                                current_first_id = res.data.first_id;
                            }
                            setTimeout(function () {
                                is_loading = false
                            }, 1000);
                        }
                    }, false, true)
                }
                //上拉
                else if (type == 2) {
                    api.requestApi('/api/discuss/commentList', {
                        last_id: current_last_id,
                        item_id: item_id,
                        limit: limit
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                $.each(res.data.list, function () {
                                    $("#scroller-content .comment_list").append(this);
                                });
                                myScroll.refresh();
                                current_last_id = res.data.last_id;

                                /*   myScroll.scrollTo(0, myScroll.maxScrollY, 1000);*/
                            }
                            setTimeout(function () {
                                is_loading = false
                            }, 1000);
                        }
                    }, false, true)
                }
                //重新加载
                else {
                    api.requestApi('/api/message/commentList', {
                        item_id: item_id,
                        limit: limit
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                var html = "";
                                $.each(res.data.list, function () {
                                    html += this;
                                });
                                $("#scroller-content .comment_list").html(html);
                                myScroll.refresh();
                                current_last_id = res.data.last_id;
                                current_first_id = res.data.first_id;
                                /*   myScroll.scrollTo(0, myScroll.maxScrollY, 1000);*/
                            }
                        }
                        if (($("#scroller-content .comment_list").height() >= 500)) {
                            $("#scroller-pullUp").show();
                        }
                        setTimeout(function () {
                            is_loading = false
                        }, 1000);


                    }, false, true)
                }
            }
        })
    })
</script>