<link rel="stylesheet" type="text/css" href="/srv/static/panel/js/tools/datetimepicker/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" type="text/css" href="/srv/static/panel/ali_iconfont/iconfont.css?v=1.0">
<script src="/srv/static/panel/ali_iconfont/iconfont.js?v=1.0"></script>
<style>
    .icon {
        width: 1em;
        height: 1em;
        vertical-align: -0.15em;
        fill: currentColor;
        overflow: hidden;
        display: inline-block;
    }

</style>
<form action="" method="get"
      style="border-bottom: 1px solid #e4e4e4;padding: 8px;margin: 0 0 8px; line-height: 50px;">
    <label for="name">关键字</label>
    <input name="key" type="text" id="key" placeholder="用户昵称/手机/用户ID" value="<?php echo $key; ?>">
    &nbsp;
    <label for="name">状态</label>
    <select name="status">
        <option value="-1" <?php echo $status == -1 ? 'selected' : ''; ?>>全部</option>
        <option value="0" <?php echo $status == 0 ? 'selected' : ''; ?>>被系统屏蔽</option>
        <option value="1" <?php echo $status == 1 ? 'selected' : ''; ?>>正常</option>
        <option value="2" <?php echo $status == 2 ? 'selected' : ''; ?>>被用户删除</option>
    </select>&nbsp;
    <label for="name">标签</label>
    <select name="tag">
        <option value="-1" <?php echo $status == -1 ? 'selected' : ''; ?>>全部</option>
        <?php foreach ($tags as $item) { ?>
            <option value="<?php echo $item['id'] ?>"><?php echo $item['name'] ?></option>
        <?php } ?>
    </select>&nbsp;
    <label for="name">是否后台添加</label>
    <select name="is_admin">
        <option value="-1" <?php echo $status == -1 ? 'selected' : ''; ?>>全部</option>
        <option value="1" <?php echo $is_admin == 1 ? 'selected' : ''; ?>>是</option>
        <option value="0" <?php echo $is_admin == 0 ? 'selected' : ''; ?>>否</option>
    </select>
    &nbsp;<label for="name">分类</label>
    <select name="media_type">
        <option value="0" <?php echo $media_type == 0 ? 'selected' : ''; ?>>全部</option>
        <option value="1" <?php echo $media_type == 1 ? 'selected' : ''; ?>>纯文本</option>
        <option value="2" <?php echo $media_type == 2 ? 'selected' : ''; ?>>小视频</option>
        <option value="3" <?php echo $media_type == 3 ? 'selected' : ''; ?>>图片</option>
        <option value="4" <?php echo $media_type == 4 ? 'selected' : ''; ?>>音频</option>
    </select>
    &nbsp;<label for="name">时间:</label>
    <input type="text" id="start" value="<?php echo $start; ?>" placeholder="开始时间" name="start"
           data-date-format="yyyy-mm-dd"/>
    - <input type="text" id="end" value="<?php echo $end; ?>" placeholder="结束时间" name="end"
             data-date-format="yyyy-mm-dd"/>
    <input type="submit" class="btn btn-primary btn-sm" value="搜索">
</form>
<div class="tabs">
    <a href="<?php echo $this->uri->setUrl(['type' => 0], ['p']); ?>"
       class="tab <?php echo $type == 0 ? 'active' : ''; ?>">全部</a>
    <a href="<?php echo $this->uri->setUrl(['type' => 1], ['p']); ?>"
       class="tab <?php echo $type == 1 ? 'active' : ''; ?>">推荐</a>
    <a href="<?php echo $this->uri->setUrl(['type' => 2], ['p']); ?>"
       class="tab <?php echo $type == 2 ? 'active' : ''; ?>">有效动态</a>
</div>
<table id="article-list" class=' list'>
    <thead>
    <tr class="head">
        <th style='width:36px'>ID</th>
        <!-- <th style='width:60px'>批量</th>-->
        <th style='width:150px'>发布人</th>
        <th style='width:160px' class="arrow" data-sort="" data-order="created">
            <span class="text">发布时间</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!--
            <?php /*if ($sort && $sort == 'created') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 发布时间</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'created']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 发布时间</a>
            --><?php /*} */ ?>
        </th>
        <th>标签</th>
        <th style='width:200px'>文本内容</th>
        <!--    <th style='width:300px'>审核</th>-->
        <th style='width:60px'>类型</th>
        <th style='width:60px' class="arrow" data-sort="" data-order="package">
            <span class="text">红包</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span></th>
        <th style='width:50px'>状态</th>
        <th style='width:70px' class="arrow" data-sort="" data-order="like">
            <span class="text">点赞</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!-- <?php /*if ($sort && $sort == 'like') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 点赞</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'like']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 点赞</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:70px' class="arrow" data-sort="" data-order="fav">
            <span class="text">收藏</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!-- <?php /*if ($sort && $sort == 'fav') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 收藏</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'fav']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 收藏</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:70px' class="arrow" data-sort="" data-order="comment">
            <span class="text">评论</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!--  <?php /*if ($sort && $sort == 'comment') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 评论</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'comment']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 评论</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:70px' class="arrow" data-sort="" data-order="forward">
            <span class="text">转发</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!-- <?php /*if ($sort && $sort == 'forward') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 转发</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'forward']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 转发</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:70px' class="arrow" data-sort="" data-order="view">
            <span class="text">阅读</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!-- <?php /*if ($sort && $sort == 'view') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 阅读</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'view']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 阅读</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:70px' class="arrow" data-sort="" data-order="report">
            <span class="text">举报</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!--   <?php /*if ($sort && $sort == 'report') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 举报</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'report']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 举报</a>
            --><?php /*} */ ?>

        </th>
        <th style='width:60px'>置顶</th>
        <th style='width:100px' class="arrow" data-sort="" data-order="weight">
            <span class="text">权重</span>
            <span class="arrow_wrap">
                <i class="fa fa-caret-down arrow-down"></i>
                <i class="fa fa-caret-up arrow-up "></i>
            </span>
            <!--  <?php /*if ($sort && $sort == 'weight') { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => $sort_order == 'desc' ? 'asc' : 'desc']); */ ?>"
                   class="order active">
                    <i class="fa fa-long-arrow-<?php /*echo $sort_order == 'desc' ? 'down' : 'up'; */ ?>"></i> 权重</a>
            <?php /*} else { */ ?>
                <a href="<?php /*echo $this->uri->setUrl(['order' => 'desc', 'sort' => 'weight']); */ ?>" class="order">
                    <i class="fa fa-arrows-v"></i> 权重</a>
            --><?php /*} */ ?>

            <a href="javascript:;" class="fa fa-question-circle blue tooltip-info" data-rel="tooltip"
               data-placement="top" data-original-title="根据评论数,点赞数,转发数,阅读数,收藏数按照一定规则生成"></a>
        </th>
        <th>操作</th>
    </tr>
    </thead>
    <?php
    if ($list) {
    ?>

    <tbody class="listData">
    <?php
    foreach ($list as $item) {
        $content = \Util\FilterUtil::unPackageContentTag($item['content'], 0, "/panel/users/detail?user_id=");
        ?>
        <tr class="item" data-id="<?php echo $item['id']; ?>">
            <th class='name'><?php echo $item['id']; ?></th>
            <!--   <td class="center"><label>
                    <input type="checkbox" class="chk ace" data-id="<?php /*echo $item['id']; */ ?>"/>
                    <span class="lbl"></span>
                </label>
            </td>-->
            <td><?php echo $item['user_id'] . '【' . $users[$item['user_id']]['username'] . '】'; ?></td>
            <td><?php echo date('Y-m-d H:i:s', $item['created']); ?></td>
            <td>
                <?php echo $item['tags_name']; ?>
            </td>
            <td style="width: 200px;word-break: break-all;">
                <?php if ($item['share_original_type'] == \Services\Social\SocialManager::TYPE_DISCUSS || $item['share_original_type'] == '') {

                    ?>
                    <?php echo mb_strlen($item['content'], 'utf-8') > 20 ? mb_substr($content, 0, 20, 'utf-8') . '...<a target="_blank"  href="javascript:;" class="newTarget" data-title="动态详情" data-id="discuss_detail_' . $item['id'] . '" data-href="/panel/discuss/detail/' . $item['id'] . '">查看更多</a>' : $content; ?>

                <?php } else {
                    if (empty($item['parent_item_id_str'])) {
                        $content = json_decode($item['content'])->content;
                    } else {
                        $content = $item['content'];
                    }
                    ?>

                    <?php echo mb_strlen($content, 'utf-8') > 20 ? mb_substr($content, 0, 20, 'utf-8') . '...<a target="_blank" href="javascript:;" class="newTarget" data-title="动态详情" data-id="discuss_detail_' . $item['id'] . '" data-href="/panel/discuss/detail/' . $item['id'] . '">查看更多</a>' : $content; ?>
                <?php } ?>

            </td>
            <td>

                <?php if ($item['media_type'] == 1) {
                    echo '<label class="badge badge-inverse">纯文本</label>';
                } else if ($item['media_type'] == 2) {
                    echo '<label class="badge badge-pink">小视频</label>';
                } else if ($item['media_type'] == 3) {
                    echo '<label class="badge badge-info">图片</label>';
                } else if ($item['media_type'] == 4) {
                    echo '<label class="badge badge-purple">音频</label>';
                };

                ?>
            </td>
            <td>
                <?php if ($item['package_id']) { ?>
                    <svg class="icon" style="font-size: 25px;" aria-hidden="true">
                        <use xlink:href="#icon-hongbao"></use>
                    </svg>
                <?php } ?>
            </td>
            <td>

                <?php if ($item['status'] == 0) {
                    echo "<label class='badge badge-danger'>已被系统屏蔽</label>";
                } else if ($item['status'] == 1) {
                    echo "<label class='badge badge-success'>正常</label>";
                } else if ($item['status'] == 2) {
                    echo "<label class='badge badge-gray'><i class='fa fa-trash'></i> 用户已删除</label>";
                }; ?>
            </td>
            <td>
                <?php echo $item['like_cnt']; ?>
            </td>
            <td>
                <?php echo $item['fav_cnt']; ?>
            </td>
            <td>
                <?php echo $item['comment_cnt'] > 0 ? "<a  href='javascript:;' class='newTarget' data-title='评论列表' data-id='comment_list_" . $item['id'] . "' data-href='/panel/discuss/comment/" . $item['id'] . "' target='_blank'>" . $item['comment_cnt'] . "</a>" : 0; ?>
            </td>
            <td>
                <?php echo $item['forward_cnt']; ?>
            </td>
            <td>
                <?php echo $item['view_cnt']; ?>
            </td>
            <td>
                <?php echo $item['report_cnt']; ?>
            </td>
            <td>
                <?php echo $item['is_top'] == 1 ? "是" : '否'; ?>
            </td>
            <td>
                <?php echo $weight['comment_cnt']['val'] * $item['comment_cnt'] + $weight['like_cnt']['val'] * $item['like_cnt'] + $weight['fav_cnt']['val'] * $item['fav_cnt'] + $weight['view_cnt']['val'] * $item['view_cnt'] + $weight['forward_cnt']['val'] * $item['forward_cnt']; ?>
                <?php echo $item['is_recommend'] == 1 ? '<label class="badge badge-warning"><i class="fa fa-tag"></i> 荐</label>' : ''; ?>
            </td>
            <td>
                <a target="_blank"
                   href="javascript:;"
                   data-href="/panel/discuss/detail/<?php echo $item['id']; ?>/<?php echo $where ?>"
                   data-title="动态详情"
                   data-id="discuss_detail_<?php echo $item['id']; ?>"
                   class="btn btn-minier btn-primary newTarget">详情</a>
                <?php if ($item['scan_type'] = \Services\Discuss\DiscussManager::SCAN_TYPE_ALL && $item['parent_item_id'] == 0 && $item['media_type'] == \Services\Discuss\DiscussManager::TYPE_VIDEO) { ?>
                    <?php if ($item['status'] == \Services\Discuss\DiscussManager::STATUS_NORMAL) { ?>
                        <?php if ($item['is_recommend'] == 0 && $item['scan_type'] == \Services\Discuss\DiscussManager::SCAN_TYPE_ALL) { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-primary btn-minier recommendBtn"><i class="fa fa-thumbs-up"></i> 推荐</a>
                        <?php } else { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-primary btn-minier delRecommendBtnBtn"><i class="fa fa-thumbs-o-up"></i>
                                推荐</a>
                        <?php } ?>

                        <?php if ($item['status'] == 1) { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-danger btn-minier delBtn">屏蔽</a>
                        <?php } else if ($item['status'] == 0) { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-danger btn-minier recoveryBtn">恢复</a>
                        <?php } ?>
                    <?php } ?>
                <?php } else { ?>
                    <?php if ($item['status'] == \Services\Discuss\DiscussManager::STATUS_NORMAL) { ?>
                        <?php if ($item['status'] == 1) { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-danger btn-minier delBtn">屏蔽</a>
                        <?php } else if ($item['status'] == 0) { ?>
                            <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                               class="btn btn-danger btn-minier recoveryBtn">恢复</a>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
                <?php if (!$item['is_filter']) { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-danger btn-minier hideTag">在标签页隐藏</a>
                <?php } else { ?>
                    <a href="JavaScript:;" data-id="<?php echo $item['id']; ?>"
                       class="btn btn-primary btn-minier showTag">在标签页显示</a>
                <?php } ?>
                <span data-url="http://wap.klgwl.com/discuss/detail?item_id=<?php echo $item['id'] ?>&from=panel"
                      data-original-url="http://wap.klgwl.com/discuss/detail?item_id=<?php echo $item['id'] ?>"
                      class="btn btn-minier btn-primary btnScan">H5</span>
                <?php if ($item['is_billboard'] == 1) { ?>
                    <span class="btn btn-minier btn-gray btnBillboardRemove" data-id="<?php echo $item['id'] ?>"><i
                            class="fa fa-arrow-down"></i> 取消今日榜单</span>
                <?php } else { ?>
                    <span class="btn btn-minier btn-purple btnBillboard" data-id="<?php echo $item['id'] ?>"><i
                            class="fa fa-arrow-up"></i> 推荐至今日榜单</span>
                <?php } ?>

            </td>
        </tr>
        <?php
    }
    } else {
        ?>
        <tr>
            <td colspan="17">
                <p style="margin: 20px;color:#f00;"> 暂无内容 </p>
            </td>
        </tr>
    <?php } ?>
    </tbody>
    <!--  <tr class="showpage">
          <th class="name">操作</th>
          <td colspan="17">
                  <span>
                      [ <a href="javascript:;" class="selectAll">全选</a> ]
                      [ <a href="javascript:;" class="selectNone">全不选</a> ]
                      [ <a href="javascript:;" class="selectInvert">反选</a> ]
                      <a class="btn-light delAllSelected" href="javascript:;">批量屏蔽</a>
                  </span>
          </td>
      </tr>-->
    <tr class="showpage">
        <th class="name">分页</th>
        <td colspan="17">
            <?php \Util\Pagination::instance($this->view)->display($this->view); ?>
        </td>
    </tr>
</table>
<div class="" id="app-frame" style=" background-color:white; position: fixed;right: 0;z-index: 99999;top:0;
       /* box-shadow:0 0 5px rgba(0,0,0,0.3);*/
        display: none;">
    <p style="background: #fff;height: 36px;line-height: 36px;padding: 0 8px;">
        <a href="javascript:;" class="close-app">关闭预览</a> | <a href="javascript:;" class="refresh-app">重新预览</a> | <a
            href="javascript:;" data-clipboard-text="" class="copy-link">复制链接地址</a>
    </p>
    <iframe name="appFrame" id="appFrame"
            src=""
            style="width: 400px;height: 600px;margin: 0;padding: 0;border: 2px solid #e4e4e4;border-top: 1px solid #e4e4e4;border-radius:0 0 10px 10px;"></iframe>
</div>

<link rel="stylesheet" type="text/css" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script type="text/javascript" src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/panel/js/tools/Url.js"></script>
<script>
    $('[data-rel=tooltip]').tooltip();
    seajs.use('app/panel/discuss/discuss.edit.js?v=1.1.3', function (api) {
        api.del();
        api.recommend();
        api.hideTag();
        api.btnBillboard();
    });
    //  var receive_start_val;
    $('#start').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
    $('#end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y-m-d",
        maxDate: 0,
        timepicker: false,
        allowBlank: true,
        onChangeDateTime: function () {
        }
    });
    var order = '<?php echo $sort ?>'
    var sort_order = '<?php echo $sort_order ?>'
    if (order != '' && sort_order != '') {
        var current = $(".arrow[data-order='" + order + "']");
        current.addClass("active");
        current.attr('data-sort', sort_order);
        if (sort_order == 'desc') {
            current.find('.arrow-down').addClass('active');
            current.find('.arrow-up').addClass('disabled');
        } else {
            current.find('.arrow-down').addClass('disabled');
            current.find('.arrow-up').addClass('active');
        }
    }
    var url = new Url();
    $(".arrow").on('click', function () {
        var order = $(this).attr('data-order');
        var sort = $(this).attr('data-sort');
        sort = sort == 'desc' ? 'asc' : 'desc';
        url.setArgs({order: sort, sort: order, p: 1});
        window.location.href = url.getUrl();
    });
</script>
<script type="text/javascript" src="/srv/static/panel/js/tools/clipboard/clipboard.min.js"></script>

<script>
    var clipboard = new Clipboard('.copy-link', {});
    clipboard.on('success', function (e) {
        alert("复制成功");
        /* var sel = "#" + e.text;
         $(sel).tooltip('show');
         setTimeout(function () {
         // $(sel).tooltip('hide');
         }, 1500);*/
    });
    $(".btnScan").on('click', function () {
        var url = $(this).attr('data-url');
        $(".copy-link").attr('data-clipboard-text', $(this).attr('data-original-url'));
        $('#appFrame').attr('src', url);
        $('#app-frame').show();
    })
    $("#app-frame .close-app").click(function () {
        $('#app-frame').hide();
    });

    $("#app-frame .refresh-app").click(function () {
        $('#appFrame').attr('src', $('#appFrame').attr('src'));
    });
</script>
