<style>
    .footer ul li{
        display:inline-block;
    }
</style>
<div class="footer">
    <div style="margin-bottom:6px">
        <ul>
            <li><a href="/about">关于恐龙谷</a></li>
            |
            <li><a href="/service">特色服务</a></li>
            |
            <li><a href="/dynamic">恐龙谷动态</a></li>
            |
            <li><a href="/agreement">用户协议</a></li>
            |
            <li><a href="/guide">用户帮助</a></li>
        </ul>
    </div>
    Copyright © 恐龙谷 All Rights Reserved 深圳市恐龙谷网络科技有限公司版权所有
    <a href="http://www.miitbeian.gov.cn">粤ICP备15089260号-2</a>
</div>
<script>

</script>