<div class="nav" style="background-color: #FFA800">
    <div class="container clearfix">
        <div class="logo fl">
            <img src="/static/home/images/logo.png" alt="">
            <span>恐龙谷</span>
        </div>
        <div class="nav-list fr">
            <ul>
                <li >
                    <a href="" class="active">
                        首页
                    </a>
                    <span class=""></span>
                    <b></b>
                </li>

                <li class="line-two">
                    <a href="/dynamic" class="active ">恐龙谷动态</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/about" class="active">关于我们</a>
                    <span class="active navin"></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/service" class="active">特色服务</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/guide" class="active">用户帮助</a>
                    <span class=""></span>
                    <b></b>
                </li>
                <li class="line-two">
                    <a href="/agreement" class="active">用户协议</a>
                    <span class=""></span>
                    <b></b>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>

</script>
