<tr class="item" data-id="<?php echo $item['id']; ?>">
    <td class="center">
        <?php if ($item['status'] == 0) { ?>
            <label>
                <input type="checkbox" class="chk ace" data-id="<?php echo $item['id']; ?>"/>
                <span class="lbl"></span>
            </label>
        <?php } ?>
    </td>
    <th class='name'><?php echo $item['id']; ?></th>
    <td><?php echo $item['user_id'] . '【' . $item['username'] . '】'; ?></td>
    <td><?php echo '【' . ($item['admin_name'] ? $item['admin_name'] : '') . '】'; ?></td>
    <td> <?php if ($item['status'] == 0) { ?>
            <input type="text" class="title" value="<?php echo $item['title'] ?>" style="width: 400px"/>&nbsp;
            <btn class="miBtn btn-green btnSaveTitle" data-id="<?php echo $item['id'] ?>">保存</btn>
        <?php } else { ?>
            <?php echo $item['title'] ?>
        <?php } ?></td>
    <td><?php echo date('Y-m-d H:i', $item['created']); ?></td>
    <td><?php echo $item['publish_time'] ? date('Y-m-d H:i', $item['publish_time']) : ''; ?></td>
    <td>
        <a href="javascript:;" class="btn btn-sm btn-primary btnScan" data-url="<?php echo $item['url'] ?>"><i
                class="fa fa-video-camera"></i> 查看视频</a>&nbsp;

        <?php if ($item['status'] == 0) { ?>
            <a target="_blank" href="javascript:;"
               class="btn btn-sm btn-success publishBtn" data-id="<?php echo $item['id'] ?>"><i
                    class="fa fa-paper-plane"></i> 立即发布</a>
        <?php } ?>

    </td>
</tr>
