<section>
    <article>
      <!--  <div class="field set-field">
            <label for="" class="field-label">视频截图</label>
            <span class="upload-widget" data-unique="1"><a class="btn btn-sm btn-success  browse-button"
                                                           href="javascript:;">选择视频截图</a></span>
            <img alt="请选择视频截图" src="" id="videoThumb"
                 style="height: 32px;"/>
            <span class="tip"><span class="red"></span></span>
        </div>-->
        <video style="display:none;" controls="controls" id="video" data-duration="0"></video>
        <div class="field set-field videoSection">
            <label for="" class="field-label">视频</label>
            <span class="upload-widget" data-unique="2"><a class="btn btn-sm btn-success  browse-button"
                                                           href="javascript:;">选择视频</a></span>
            <input type="hidden" id="video_ID" value=""/>
            <span id="videoUrl" style="height: 32px;"></span>

            <span class="tip"><span class="red"></span></span>
        </div>

    </article>
</section>

