<?php
if (strpos($this->request->getUserAgent(), 'KLG') === false ) { ?>
    <div class="public-header">
        <div class="public_download">
            <dl>
                <dt class="klg-icon"><img src="/static/wap/images/logo.png" alt="恐龙谷"/></dt>
                <dd>
                    <h6>恐龙谷</h6>
                    <p>娱乐自媒体社交平台</p>
                </dd>
                <dd class="down_btn">
                    <a  href="javascript:;" onclick="APPCommon.init()">打开</a>
                </dd>
            </dl>
        </div>
    </div>
    <a href="" id="bridge" style="display: none"></a>
    <img src="/static/wap/images/download/appletips.png" id="imgtip" alt="">

<?php }?>

<script>
    var APPCommon = {
        iphoneSchema: "",
        iphoneDownUrl: 'https://itunes.apple.com/cn/app/kong-long-gu/id1208329358?mt=8',
        androidSchema: '',
        androidDownUrl: "<?php echo $download_url?>",
        params:"",
        openApp: function () {
            // event.stopPropagation();
            var browser = {
                versions: function () {
                    var u = navigator.userAgent, app = navigator.appVersion;
                    return {//移动终端浏览器版本信息
                        trident: u.indexOf('Trident') > -1, //IE内核
                        presto: u.indexOf('Presto') > -1, //opera内核
                        webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                        gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                        mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
                        ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                        android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                        iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
                        iPad: u.indexOf('iPad') > -1, //是否iPad
                        webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
                    };
                }()
            };
            //                pc
            if (!browser.versions.mobile) {
                window.location.href = "http://www.klgwl.com";
            } else {
                var this_ = this;
                //微信
                var u = navigator.userAgent.toLowerCase();
                if (this_.isWeixin()) {
                    if (u.indexOf('android') > -1 || u.indexOf('linux') > -1) {//安卓手机
                        $("#imgtip").show();
                        $("#imgtip").attr("src", "/static/wap/images/download/androdtips.png");
                    } else if (u.indexOf('iphone') > -1) {//苹果手机
                        //window.location.href = APPCommon.iphoneDownUrl;
                        $("#imgtip").show();
                        $("#imgtip").attr("src", "/static/wap/images/download/appletips.png");
                    }
                } else {//非微信浏览器
                    if (u.toLowerCase().indexOf('iphone') > -1 || u.toLowerCase().indexOf('ipad') > -1) {
                        window.location.href = APPCommon.iphoneDownUrl;
                    } else if (navigator.userAgent.match(/android/i)) {

                        window.location.href = APPCommon.androidDownUrl;
                    }
                }
            }
        },
        isWeixin: function () { //判断是否是微信
            var ua = navigator.userAgent.toLowerCase();
            if (ua.match(/MicroMessenger/i) == "micromessenger") {
                return true;
            } else {
                return false;
            }
        },
        init: function () {
            var _this = this;
            var params = _this.params;
            _this.iphoneSchema = "DValleyNew://response_from_klg?" + params;
            _this.androidSchema = "klg://klg.com?" + params;
            var u = navigator.userAgent.toLowerCase();
            if (u.toLowerCase().indexOf('iphone') > -1 || u.toLowerCase().indexOf('ipad') > -1) {
                //window.location.href =  APPCommon.iphoneSchema;
                _this.openByAnchor(APPCommon.iphoneSchema);
                setTimeout(function () {
                    _this.openApp()
                }, 500);
            } else if (navigator.userAgent.match(/android/i)) {
                //window.location.href = APPCommon.androidSchema;
                _this.openByAnchor(APPCommon.androidSchema);
                setTimeout(function () {
                    _this.openApp()
                }, 500);
            }
        },
        setParams:function(params){
            this.params = params;
        },
        openByAnchor:function(href){
            $('#bridge').attr('href',href);
            document.getElementById('bridge').click();
        }
    };

    $("#imgtip").on("click", function () {
        event.stopPropagation();
        $("#imgtip").hide();
    })

</script>



