<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=no" >
    <title>恐龙谷</title>
    <script src="/static/panel/js/ueditor/third-party/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="/static/panel/js/ueditor/third-party/video-js/video-js.min.css">
    <script src="/static/panel/js/ueditor/third-party/video-js/video.js"></script>
    <style>
        body{
            font-family: -apple-system-font, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
            background-color: #fff;
        }
        h2{
            font-weight:400;
            font-size:25px;
            margin:0;
        }
        img {
            max-width:100%;
            height:auto;
        }
        .video-js{
            margin:0 auto;
        }
        .rich_media{
            max-width: 740px;
            margin-left:auto;
            margin-right:auto;
        }
        .rich_media_area_primary{
            position: relative;
            padding: 10px 15px 15px;
            background-color: #fff;
        }
        .rich_media_meta_list {
            position: relative;
            z-index: 1;
            margin-top: 15px;
            margin-bottom: 10px;
            line-height: 20px;
            font-size: 16px;
        }
        .rich_media_meta_text {
            font-style: normal;
            color: #8c8c8c;
        }

        .rich_media_meta {
            display: inline-block;
            vertical-align: middle;
            margin-right: 8px;
            margin-bottom: 10px;
            font-size: 16px;
        }
        @media(min-device-width:375px) and (max-device-width:667px) and (-webkit-min-device-pixel-ratio:2) {
            .rich_media_inner,
            .rich_media_meta {
                font-size: 17px

            }
            .rich_media_title{
                font-size:22px;
            }
            .rich_media_content{
                font-size:16px
            }
            .rich_media_area_primary {
                position: relative;
                padding: 10px 15px 15px;
                background-color: #fff;
            }
        }
        @media only screen and (device-width:375px) and (device-height:812px) and (-webkit-device-pixel-ratio:3) and (orientation:landscape) {
            .rich_media_area_primary {
                padding: 20px 59px 15px 59px
            }
        }
        @media screen and (min-width:1024px) {
            .rich_media {
                width: 740px;
                margin-left: auto;
                margin-right: auto
            }

            .rich_media_inner {
                padding: 20px
            }

            body {
                background-color: #fff
            }
        }
        @media screen and (min-width:1025px) {
            body {
                font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", "Microsoft YaHei", Arial, sans-serif
            }

            .rich_media {
                position: relative
            }

            .rich_media_inner {
                background-color: #fff;
                padding-bottom: 100px
            }
        }
        @media screen and (min-width:1024px) {
            .rich_media_meta {
                max-width: none
            }

            .rich_media_content {
                min-height: 350px
            }

            .rich_media_title {
                padding-bottom: 10px;
                margin-bottom: 14px;
                border-bottom: 1px solid #e7e7eb
            }
        }
    </style>
</head>
<body>

    <div class="rich_media">
        <div class="rich_media_inner">
            <div class="rich_media_area_primary">
                <div class="img-content">
                    <h2 class="rich_media_title"><?php echo $title ?></h2>
                    <div id="meta_content" class="rich_media_meta_list">
                        <em id="post-date" class="rich_media_meta rich_media_meta_text"><?php echo date('Y/m/d',$created) ?></em>

                        <em class="rich_media_meta rich_media_meta_text">恐龙谷</em>
                    </div>
                    <div class="rich_media_content">
                        <?php echo $content ?>
                    </div>
                </div>
            </div>
        </div>

    </div>


</body>
</html>
<script>

</script>