<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content="商户入驻">
    <meta name="author" content="Estt Team">
    {{ get_title() }}
    {{ stylesheet_link('static/ace/css/bootstrap.min.css') }}
    {{ stylesheet_link('static/ace/css/font-awesome.min.css') }}
    {{ stylesheet_link('static/fonts/font-awesome/css/font-awesome.min.css') }}
    {{ stylesheet_link('static/ace/css/ace.min.css') }}
    {{ stylesheet_link('static/panel/css/ace-estt-panel.css') }}

    {{ javascript_include('static/panel/js/seajs.js') }}
    {{ javascript_include('static/panel/js/jquery.min.js') }}
    <script>
        seajs.config({
            base: '/static/panel/js',
            charset: 'utf-8',
            timeout: 10000
        });
    </script>
    <!--[if lt IE 9]>
    {{ javascript_include('static/ace/js/html5shiv.js') }}
    {{ javascript_include('static/ace/js/respond.min.js') }}
    <![endif]-->

</head>
<body>
<main class="wrap">
    <?php if (!($this->dispatcher->getControllerName() == 'account' && $this->dispatcher->getActionName() == 'login')) { ?>
        <header class="header">
            <div style="width: 1040px;margin: 0 auto;">
                <p class="panel-tit">
                    <span class="right tit">管理登陆</span>
                    <span>Control</span>
                    <span style="color: #FFC600;">Panel</span>
                    <span class="name"> - <span style="color: #FFC600;"><?php echo HOST_BRAND; ?></span>运营平台</span>
                </p>
            </div>
        </header>
    <?php } ?>

    <section class="main">
        <?php
        echo $this->getContent();
        ?>
    </section>
    <footer>
    </footer>
</main>
<div id="ajaxStatus">
    <p id='ajaxTip' class="wait">加载中...</p>
</div>
</body>
</html>