<script src="/srv/static/ace/js/bootstrap-wysiwyg.min.js"></script>
<script src="/srv/static/ace/js/jquery.hotkeys.min.js"></script>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog" style="width:60%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">添加/编辑问题</h4>
            </div>
            <div class="modal-body">
                <div id="box" >
                    <div style="width:80%;margin:0 auto">
                        <div style="margin-top:10px">
                            <input type="hidden" id="id" value="0">
                            <label for="ques" class="col-xs-2">问&nbsp;&nbsp;&nbsp;&nbsp;题：</label>
                            <input type="text" id="ques" class="col-xs-10" >
                            <div class=" hr-10 clearfix "></div>
                            <label for="type" class="col-xs-2">问题分类：</label>
                            <select name="" id="type" class="col-xs-10">
                                <option value=0>--请选择问题类型--</option>
                                <option value=1>最新问题</option>
                                <option value=2>热门问题</option>
                                <option value=3>账号与账号安全</option>
                                <option value=4>功能介绍</option>
                            </select>
                            <div class="clearfix"></div>
                        </div>
                        <div style="height:20px;"></div>
                        <div id="editor" style="min-height:500px;border:1px solid #E5E5E5" ></div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="save">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
<script>
    $(function(){
        //初始化编辑器
        $('#editor').ace_wysiwyg({
            toolbar:
                [
                    'font',
                    null,
                    'fontSize',
                    null,
                    {name:'bold', className:'btn-info'},
                    {name:'italic', className:'btn-info'},
                    {name:'strikethrough', className:'btn-info'},
                    {name:'underline', className:'btn-info'},
                    null,
                    {name:'insertunorderedlist', className:'btn-success'},
                    {name:'insertorderedlist', className:'btn-success'},
                    {name:'outdent', className:'btn-purple'},
                    {name:'indent', className:'btn-purple'},
                    null,
                    {name:'justifyleft', className:'btn-primary'},
                    {name:'justifycenter', className:'btn-primary'},
                    {name:'justifyright', className:'btn-primary'},
                    {name:'justifyfull', className:'btn-inverse'},
                    null,
                    {name:'createLink', className:'btn-pink'},
                    {name:'unlink', className:'btn-pink'},
                    null,
                    {name:'insertImage', className:'btn-success'},
                    null,
                    'foreColor',
                    null,
                    {name:'undo', className:'btn-grey'},
                    {name:'redo', className:'btn-grey'}
                ]

        }).prev().addClass('wysiwyg-style2');
    });
    seajs.use('app/panel/panel.base',function(api){
        //保存编辑内容
        $('#save').on('click',function(){
            var content = $('#editor').html();
            var ques = $.trim($('#ques').val());
            var type = $('#type').val();
            var id = $('#id').val();
            var isOk = true;
            if( type == 0 )
            {
                isOk = false;
                tip.showTip('err','请选择问题类型',1000);
                return;
            }
            if( ques === '' )
            {
                isOk = false;
                tip.showTip('err','请输入问题',1000);
                return;
            }
            if( isOk )
            {
                api.requestApi('/api/article/saveGuides',{id:id,content:content,ques:ques,type:type},function (res) {
                    if( res.result === 1 )
                    {
                        tip.showTip('ok','操作成功',800,function () {
                            $('#myModal').modal('hide');
                            location.reload();
                        });

                    }else
                    {
                        tip.showTip('err','操作失败',1000)
                    }
                });
            }
        });
    });

</script>