<style>
    .inner-nav, .page-header {
        background: #fff;
    }

    .inner-nav {
        box-shadow: none;
    }

    .page-header {
        margin: -5px;;
        margin-bottom: 5px;
        border-bottom: 1px solid #e4e4e4;
        position: fixed;
        top: 85px;
        left: 196px;
        width: 100%;
        max-width: 100%;
        padding-right: 280px;;
        padding-bottom: 5px;
    }

    .page-content {
        padding: 4px;
    }

    .main-container:after, .page-content {
        background: #ececec
    }

    #wrapper {
        position: relative;
        width: 100%;
        background: #fff;
        overflow: hidden;
        max-height: 500px;
    }

    #scroller {
        position: absolute;
        z-index: 1;
        -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
        width: 100%;
        -webkit-transform: translateZ(0);
        -moz-transform: translateZ(0);
        -ms-transform: translateZ(0);
        -o-transform: translateZ(0);
        transform: translateZ(0);
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-text-size-adjust: none;
        -moz-text-size-adjust: none;
        -ms-text-size-adjust: none;
        -o-text-size-adjust: none;
        text-size-adjust: none;
    }

    #scroller-pullDown, #scroller-pullUp {
        background: #fff;
        height: 40px;
        line-height: 40px;
        padding: 5px 10px;
        border-bottom: 1px solid #ccc;
        font-weight: bold;
        font-size: 14px;
        color: #888;
        text-align: center;
        position: absolute;
        left: 0px;
        width: 100%;
    }

    #scroller-pullDown {
        top: -40px;
    }

    #scroller-pullUp {
        bottom: -40px;
    }

    #scroller-pullDown .pull-up-msg, #scroller-pullUp .pull-down-msg {
        padding-left: 20px;
    }

    #scroller-pullDown .pull-down-icon, #scroller-pullUp .pull-up-icon {
        display: inline-block;
        color: dodgerblue;
        font-size: 1.4em;
        -webkit-transform: rotate(0deg);
        -webkit-transition-property: -webkit-transform;
        -webkit-transition-duration: 500ms;
    }

    #scroller-pullDown .pull-down-icon.reverse_icon, #scroller-pullUp .pull-up-icon.reverse_icon {
        -webkit-transform: rotate(-180deg);
    }

    #wrapper {
        height: 500px;
        overflow: hidden;
        max-width: 100%;
    }

    #wrapper ul {
        width: 100%;
        margin: 0;
        height: auto;
        overflow: hidden;
    }

    #wrapper ul li {
        clear: both;
        width: 90%;
        margin-bottom: 10px;
    }

    #wrapper ul li .tip {
        width: 100%;
        text-align: center;
        /*  margin: 20px;*/
        font-size: 13px;
        height: 30px;
        line-height: 30px;
        vertical-align: middle;
    }

    #wrapper ul li .tip:first-child {
        margin-top: 0;
    }

    #wrapper ul li .avatar {
        width: 50px;
        height: 50px;
        display: inline-block;
        margin-top: 10px;

    }

    #wrapper ul li .info {
        display: inline-block;
        min-width: 80px;
    }

    #wrapper ul li .info .msg_info {
        border: 1px solid #ececec;
        padding: 8px 10px 8px;
        position: relative;
        border-radius: 5px;
        max-width: 600px;
        min-height: 30px;
        word-break: break-all;
    }

    #wrapper ul li .info .dur {
        float: left;
        margin-right: 5px;;
    }

    #wrapper ul li .info .right .dur {
        float: right;
    }

    #wrapper ul li .info .voice {
        cursor: pointer;
        float: left;
    }

    #wrapper ul li .info .right .voice {
        float: right;
    }

    #wrapper ul li .info .name {
        margin-bottom: 5px;;
    }

    #wrapper ul li .info .desc {
    }

    #wrapper ul li .avatar img {
        width: 50px;
        height: 50px;
        border-radius: 100%;
    }

    #wrapper ul li.right .avatar {
        float: right;
    }

    #wrapper ul li.left .avatar {
        float: left;
    }

    #wrapper ul li .info .msg_img {
        max-width: 100px;
        border-radius: 5px;
    }

    #wrapper ul li.right .info {
        float: right;
        text-align: right;
        max-width: 600px;
        margin-right: 10px;
    }

    #wrapper ul li.left .info {
        max-width: 600px;
        margin-left: 10px;
        float: left;
    }

    #wrapper ul li.right .info .arrow {
        position: absolute;
        right: -6px;
        height: 10px;
        width: 10px;
        background-color: #fff;
        border: 1px solid #e4e4e4;
        top: 10px;
        border-left: none;
        border-bottom: none;
        transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -webkit-transform: rotate(45deg);
        -o-transform: rotate(45deg);
    }

    #wrapper ul li.left .info .arrow {
        position: absolute;
        left: -5px;
        height: 10px;
        width: 10px;
        background-color: #fff;
        border: 1px solid #ececec;
        top: 10px;
        border-top: none;
        border-right: none;
        transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -webkit-transform: rotate(45deg);
        -o-transform: rotate(45deg);
    }

    .msg_content {
        width: 1100px;
        resize: none;
        height: 50px;
        border: 1px solid #ececec;
        border-top: none;
        border-radius: 0 0 0 5px !important;
        margin: 0 !important;
        float: left;
        line-height: 30px;
        vertical-align: middle;
        font-size: 16px;
    }

    .send_btn {
        width: 98px;
        height: 49px;
        line-height: 49px;
        text-align: center;
        vertical-align: middle;
        display: inline-block;
        background-color: #438eb9;
        font-size: 18px;
        color: #fff;
        float: left;
        border-radius: 0 0 5px 0;
        cursor: pointer;

    }

    .disabled {
        background-color: #ddd;
    }

    .video_box {
        max-width: 360px;
        min-width: 80px;
        min-height: 100px;
        height: auto;
        overflow: hidden;
        position: relative;
        z-index: 1;
    }

    .video_box .video {
        max-width: 180px;
        max-height: 320px;
        border-radius: 5px;
        display: none;
    }

    .video_box .video_thumb {
        display: none;
        max-width: 180px;
        max-height: 320px;
        border-radius: 5px;
    }

    .video_box .play {
        position: absolute;
        height: 100%;
        width: 100%;
        z-index: 10;
        left: 0;
        top: 0;
        font-size: 40px;
        line-height: 100%;
        vertical-align: middle;
        text-align: center;
        cursor: pointer;
        color: #000;
    }

    .video_box .play i {
        height: 50px;
    }

</style>
<div
    style="width:1200px;height: auto;border: 1px solid #ececec;overflow: hidden;background-color: #fff;padding: 20px;padding-top:5px;margin: 10px;margin-bottom: 0">
    <div class="header" style="border-bottom: 1px dotted #ececec;overflow: hidden;margin-top: 0"><span>与 <b
                style="font-size: 16px" class="blue"><?php echo $user_info['username'] ?></b> 的会话</span><span
            class="right btn btn-sm btn-primary refreshBtn"><i class="fa fa-refresh"></i>刷新</span></div>
    <div id="wrapper">
        <div id="scroller"
             style="transition-timing-function: cubic-bezier(0.1, 0.57, 0.1, 1); transition-duration: 0ms; transform: translate(0px, 0px) translateZ(0px);">

            <div id="scroller-pullDown">
                <span id="down-icon" class=" fa fa-angle-double-down pull-down-icon reverse_icon"></span>
                <span id="pullDown-msg" class="pull-down-msg">下拉加载</span>
            </div>
            <div id="scroller-content">
                <ul>
                    <?php
                    $pre = 0;
                    foreach ($list as $item) {

                        ?>
                        <?php if (date("YmdHi", floor($item['send_time']/1000)) != $pre) { ?>
                            <li><p class="tip" data-id="<?php echo $item['id'] ?>"
                                   style="width: 100%;text-align: center"><?php echo date("Y-m-d H:i:s", floor($item['send_time']/1000)) ?></p>
                            </li>
                        <?php } ?>
                        <?php if ($item['from_uid'] == \Services\Im\ImManager::ACCOUNT_SYSTEM) { ?>
                            <li class="right">
       <span class="avatar">
           <img src="/static/panel/images/logo.png"/></span>
                                <div class="info">
                                    <p class="name"><a href="javascript:;">恐龙君</a></p>
                                    <div class="msg_info">
                                        <p class="desc grey">
                                            <?php if ($item['media_type'] == 'audio') {
                                                $body = json_decode($item['body'], true);
                                                ?>
                                                <span
                                                    class="dur"><?php echo round($body['dur'] / 1000, 1) . 's' ?></span>
                                                <span class="voice" data-id="<?php echo $item['id'] ?>"
                                                      data-src="<?php echo $body['url'] ?>"
                                                      style="width: 16px;height: 16px;display:inline-block;background: url(/static/panel/images/admin/voice-right.png) no-repeat;"></span>
                                            <?php } else if ($item['media_type'] == 'picture') {
                                                $body = json_decode($item['body'], true);
                                                ?>
                                                <a href="<?php echo $body['url'] ?>" data-lightbox="roadtrip"> <img
                                                        class="msg_img"
                                                        src="<?php echo $body['url'] ?>"/></a>
                                            <?php } else if ($item['media_type'] == 'file') {
                                                $body = json_decode($item['body'], true);
                                                if ($body['ext'] != 'gif') {

                                                } else {
                                                    ?>
                                                    <a href="<?php echo $body['url'] ?>" data-lightbox="roadtrip"> <img
                                                            class="msg_img"
                                                            src="<?php echo $body['url'] ?>"/></a>
                                                <?php } ?>
                                            <?php } else if ($item['media_type'] == 'video') {
                                            $body = json_decode($item['body'], true);
                                            ?>
                                        <div class="video_box">
                                            <video class="video video_<?php echo $item['id'] ?>"
                                                   data-id="<?php echo $item['id'] ?>" crossorigin="anonymous"
                                                   src="<?php echo $body['url'] ?>"></video>
                                            <img src="" style="display: none" data-id="<?php echo $item['id'] ?>"
                                                 class="video_thumb  video_thumb_<?php echo $item['id'] ?>"/>
                                            <span class="play">
                                                  <i class="fa fa-play-circle"></i></span>
                                        </div>
                                        <?php } else { ?>
                                            <?php echo $item['body'];
                                        } ?>
                                        </p>
                                        <span class="arrow"></span>
                                    </div>
                                </div>
                            </li>
                        <?php } else { ?>
                            <li class="left">
       <span class="avatar">
           <img src="<?php echo $user_info['avatar'] ?>?x-oss-process=image/resize,m_fill,h_160,w_160"/></span>
                                <div class="info">
                                    <p class="name"><a
                                            href="javascript:;" data-title="用户详情" class="newTarget"
                                            data-href="/panel/users/detail?user_id=<?php echo $item['from_uid'] ?>"><?php echo $user_info['username'] ?></a>
                                    </p>
                                    <div class="msg_info">
                                        <p class="desc grey"><?php if ($item['media_type'] == 'audio') {
                                                $body = json_decode($item['body'], true);
                                                ?>
                                                <span
                                                    class="dur"><?php echo round($body['dur'] / 1000, 1) . 's' ?></span>
                                                <span
                                                    class="voice" data-id="<?php echo $item['id'] ?>"
                                                    data-src="<?php echo $body['url'] ?>"
                                                    style="width: 16px;height: 16px;display:inline-block;background: url(/static/panel/images/admin/voice-left.png) no-repeat;"></span>
                                            <?php } else if ($item['media_type'] == 'picture') {
                                                $body = json_decode($item['body'], true);
                                                ?>
                                                <a href="<?php echo $body['url'] ?>" data-lightbox="roadtrip"> <img
                                                        class="msg_img"
                                                        src="<?php echo $body['url'] ?>"/></a>
                                            <?php } else if ($item['media_type'] == 'file') {
                                                $body = json_decode($item['body'], true);
                                                if ($body['ext'] != 'gif') {

                                                } else {
                                                    ?>
                                                    <a href="<?php echo $body['url'] ?>" data-lightbox="roadtrip"> <img
                                                            class="msg_img"
                                                            src="<?php echo $body['url'] ?>"/></a>
                                                <?php } ?>
                                            <?php } else if ($item['media_type'] == 'video') {
                                            $body = json_decode($item['body'], true);
                                            ?>
                                        <div class="video_box" data-id="<?php echo $item['id'] ?>">
                                            <!-- <video width="90" height="160" controls>
                                                <source src="<?php /*echo $body['url'] */ ?>" type="video/mp4">
                                                您的浏览器不支持Video标签。
                                            </video>-->
                                            <video data-id="<?php echo $item['id'] ?>" crossOrigin="anonymous"
                                                   class="video video_<?php echo $item['id'] ?>">
                                                <source src="<?php echo $body['url'] ?>">
                                            </video>
                                            <img src="" style="display: none" data-id="<?php echo $item['id'] ?>"
                                                 class="video_thumb video_thumb_<?php echo $item['id'] ?>""/>
                                            <span class="play"><i
                                                    class="fa fa-play-circle"></i></span>
                                        </div>
                                        <?php } else { ?>
                                            <?php echo $item['body'];
                                        } ?>
                                        </p>
                                        <span class="arrow"></span>
                                    </div>
                                </div>
                            </li>
                        <?php } ?>
                        <?php $pre = date("YmdHi",floor($item['send_time']/1000));
                    } ?>
                </ul>
            </div>
            <div id="scroller-pullUp" style="display: none">
                <span id="up-icon" class=" fa fa-angle-double-up"></span>
                <span id="pullUp-msg" class="pull-up-msg">上拉刷新</span>
            </div>
        </div>
    </div>
</div>
<div style="position: fixed;width: 1200px;height: 50px;margin-left: 10px">
    <textarea placeholder="输入需要发送的内容" class="msg_content"
    ></textarea>
    <span class="send_btn disabled" data-id="<?php echo $uid ?>"
    ><i
            class="fa fa-paper-plane"></i> 发 送</span>
</div>

<audio src="" id="voice_box">

</audio>
<script type="text/javascript" src="/srv/static/panel/js/tools/iscroll.js"></script>

<link rel="stylesheet" href="/srv/static/panel/css/lightbox/lightbox.css"/>

<script src="/srv/static/panel/js/jquery/lightbox/lightbox.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        lightbox.option({
            albumLabel: '%1/%2',
            'resizeDuration': 200,
            "fadeDuration": 0,
            "imageFadeDuration": 0
        });
    })

</script>


<script type="text/javascript">
    seajs.use('app/panel/panel.base', function (api) {
        $(function () {

            var video = null;
            //视频
            $(".video").on('loadeddata', function () {
                captureImage(this);
            });
            $(".video").on('ended', function () {
                video_end(this);
            });
            $(document).on('click', '.play', function () {
                var is_visible = $(this).find('i').is(":visible");
                if ($(".video:visible").length > 0) {
                    video_end($(".video:visible"), 'click');
                }
                if (is_visible) {
                    video = $(this).parent().find("video")[0];
                    $(this).parent().find('img').hide();
                    $(this).parent().find('video').show();
                    $(this).find("i").hide();
                    video.play();
                }


                /*  $(this).parent().find('video')[0].webkitRequestFullScreen();
                 $(this).parent().find('video')[0].mozRequestFullScreen();
                 $(this).parent().find('video')[0].requestFullscreen();*/
            });

            //语音
            var voice_timer = false;
            var voice_play = 0;
            var voice_box = document.getElementById("voice_box");
            //播放结束
            voice_box.addEventListener('ended', function () {
                $(".voice.active").css({'width': '16px'}).removeClass("active");
                voice_timer && clearInterval(voice_timer);
            }, false);

            $("#wrapper").on('click', '.voice', function () {
                if ($(this).hasClass("active")) {
                    $(this).removeClass("active");
                    voice_play = 0;
                    $(this).css({'width': '16px'});
                    voice_timer && clearInterval(voice_timer);
                    voice_box.pause();
                } else {
                    var __this = $(this);
                    $(".voice.active").css({'width': '16px'}).removeClass("active");
                    $(this).addClass('active');
                    voice_timer && clearInterval(voice_timer);

                    voice_play = $(this).data('id');
                    var i = 1;
                    voice_box.src = __this.data('src');
                    voice_box.play();

                    voice_timer = setInterval(function () {
                        if (i == 1) {
                            __this.css({'width': '6px'});
                        } else if (i == 2) {
                            __this.css({'width': '9px'});
                        } else {
                            __this.css({'width': '16px'});
                            i = 0;
                        }
                        i++;
                    }, 300)
                }
            });
            var current_last_id = "<?php echo $list ? $list[count($list) - 1]['id'] : 0?>"
            var current_first_id = "<?php echo $list ? $list[0]['id'] : 0 ?>"

            var myScroll,
                upIcon = $("#up-icon"),
                downIcon = $("#down-icon");

            var is_loading = false;


            $(".msg_content").on('input', function () {
                if ($.trim($(this).val()) != "") {
                    $(".send_btn").removeClass("disabled");
                } else {
                    $(".send_btn").addClass("disabled");
                }
            });
            $(".send_btn").on('click', function () {
                if ($(this).hasClass("disabled")) {
                    return false;
                }
                api.requestApi('/api/message/sendNormalMsg', {
                    uid: $(".send_btn").attr('data-id'),
                    msg: $.trim($(".msg_content").val())
                }, function (res) {
                    if (res.result == 1) {
                        $("#scroller-content ul").append(res.data);
                        myScroll.refresh();
                        myScroll.scrollTo(0, myScroll.maxScrollY, 1000);
                        /* checkMsg();*/
                    }
                }, false, true)
            });
            $(".refreshBtn").on('click', function () {
                fresh();
            });
            if (($("#scroller-content ul").height() >= 500)) {
                $("#scroller-pullUp").show();
            }
            /*
             //轮询 2-秒跑一次
             var timer = setInterval(checkMsg, 5000);

             function checkMsg() {
             api.requestApi('/api/message/checkMsg', {
             uid: $(".send_btn").attr('data-id'),
             last_id: current_last_id
             }, function (res) {
             if (res.result == 1) {
             if (res.data.list.length > 0) {
             $.each(res.data.list, function () {
             $("#scroller-content ul").append(this);
             });
             myScroll.refresh();
             myScroll.scrollTo(0, myScroll.maxScrollY, 1000);
             current_last_id = res.data.last_id;
             }
             }
             }, false, true)
             }*/

            function fresh(type) {
                if (is_loading) {
                    return
                }
                is_loading = true;
                //下拉
                if (type == 1) {
                    api.requestApi('/api/message/getList', {
                        uid: $(".send_btn").attr('data-id'),
                        first_id: current_first_id
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                var html = "";
                                for (var i in res.data.list) {
                                    html += res.data.list[i]
                                }
                                $("#scroller-content ul").prepend(html);
                                /*  $.each(res.data.list, function () {
                                 console.log(this);

                                 });*/
                                if (res.data.hide_tip) {
                                    console.log(res.data.hide_tip);
                                    $(".tip[data-id='" + res.data.hide_tip + "']").remove();
                                }
                                myScroll.refresh();

                                //视频加载
                                if (res.data.video_ids.length > 0) {
                                    $.each(res.data.video_ids, function () {
                                        $(".video[data-id='" + this + "']").on('loadeddata', function () {
                                            console.log(this);
                                            captureImage(this);
                                        }).on('ended', function () {
                                            video_end(this);
                                        });
                                    })
                                }
                                current_first_id = res.data.first_id;
                            }
                            setTimeout(function () {
                                is_loading = false
                            }, 1000);
                        }
                    }, false, true)
                }
                //上拉
                else if (type == 2) {
                    api.requestApi('/api/message/getList', {
                        uid: $(".send_btn").attr('data-id'),
                        last_id: current_last_id
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                $.each(res.data.list, function () {
                                    $("#scroller-content ul").append(this);
                                });
                                myScroll.refresh();
                                /*   myScroll.scrollTo(0, myScroll.maxScrollY, 1000);*/
                                current_last_id = res.data.last_id;
                            }
                            setTimeout(function () {
                                is_loading = false
                            }, 1000);

                            //视频加载
                            if (res.data.video_ids.length > 0) {
                                $.each(res.data.video_ids, function () {
                                    $(".video[data-id='" + this + "']").on('loadeddata', function () {
                                        console.log(this);
                                        captureImage(this);
                                    }).on('ended', function () {
                                        video_end(this);
                                    });
                                })
                            }
                        }
                    }, false, true)
                }
                //重新加载
                else {
                    api.requestApi('/api/message/getList', {
                        uid: $(".send_btn").attr('data-id'),
                    }, function (res) {
                        if (res.result == 1) {
                            if (res.data.list.length > 0) {
                                var html = "";
                                $.each(res.data.list, function () {
                                    html += this;
                                });
                                $("#scroller-content ul").html(html);
                                myScroll.refresh();
                                /*   myScroll.scrollTo(0, myScroll.maxScrollY, 1000);*/
                                current_last_id = res.data.last_id;
                                current_first_id = res.data.first_id;
                            }
                        }
                        if (($("#scroller-content ul").height() >= 500)) {
                            $("#scroller-pullUp").show();
                        }
                        setTimeout(function () {
                            is_loading = false
                        }, 1000);

                        //视频加载
                        if (res.data.video_ids.length > 0) {
                            $.each(res.data.video_ids, function () {
                                $(".video[data-id='" + this + "']").on('loadeddata', function () {
                                    console.log(this);
                                    captureImage(this);
                                }).on('ended', function () {
                                    video_end(this);
                                });
                            })
                        }
                    }, false, true)
                }
            }

            //获取视频缩略图
            function captureImage(video) {
                var canvas = document.createElement("canvas");
                canvas.width = video.videoWidth;
                canvas.height = video.videoHeight;
                canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);

                $(".video_thumb[data-id='" + $(video).attr('data-id') + "']").attr('src', canvas.toDataURL("image/png")).show();
                $(".video_box[data-id='" + $(video).attr('data-id') + "']").find(".play i").css(
                    {
                        'margin-top': ( $(".video_thumb[data-id='" + $(video).attr('data-id') + "']").height() / 2 - 25)
                    })
                myScroll.refresh();
            }

            //视频播放完成
            function video_end(current_video, type) {

                try {
                    if (type == 'click') {
                        video.pause();
                    }
                } catch (e) {
                    console.log(e)
                }
                $(current_video).hide();
                $(current_video).siblings(".video_thumb").show();
                $(current_video).siblings('.play').find("i").show();

            }

            myScroll = new IScroll('#wrapper', {
                probeType: 3,
                'scrollbars': true,
                'mouseWheel': true,
                'interactiveScrollbars': true,
                'shrinkScrollbars': 'scale',
                'fadeScrollbars': false
            });
            myScroll.on("scrollEnd", function () {
                if (this.y == 0) {
                    fresh(1)
                }
                else if (this.maxScrollY == this.y) {
                    fresh(2)
                }
            });
            myScroll.on("scroll", function () {
                var y = this.y,
                    maxY = this.maxScrollY - y,
                    downHasClass = downIcon.hasClass("reverse_icon"),
                    upHasClass = upIcon.hasClass("reverse_icon");

                if (y >= 40) {
                    !downHasClass && downIcon.addClass("reverse_icon");
                    return "";
                } else if (y < 40 && y > 0) {
                    downHasClass && downIcon.removeClass("reverse_icon");
                    return "";
                }

                if (maxY >= 40) {
                    !upHasClass && upIcon.addClass("reverse_icon");
                    return "";
                } else if (maxY < 40 && maxY >= 0) {
                    upHasClass && upIcon.removeClass("reverse_icon");
                    return "";
                }
            });

            myScroll.on("slideDown", function () {
                if (this.y > 40) {
                    fresh(1);
                    upIcon.removeClass("reverse_icon")
                }
            });

            myScroll.on("slideUp", function () {
                if (this.maxScrollY - this.y > 40) {
                    fresh(2);
                    upIcon.removeClass("reverse_icon")
                }
            });


        });


    });


</script>
<script src="/static/panel/js/yunxin/NIM_Web_NIM_v3.8.0.js">

</script>
<script>
//    var uid = "40000";
//    var data = {};
//    // 注意这里, 引入的 SDK 文件不一样的话, 你可能需要使用 SDK.NIM.getInstance 来调用接口
//    var nim = NIM.getInstance({
//        // debug: true,
//        appKey: '98bc106cc840b07c869ec279a7d58d38',
//        account: '40001',
//        token: '384d0c87276912015e8f07b440f856ba',
//        onconnect: onConnect,
//        onwillreconnect: onWillReconnect,
//        ondisconnect: onDisconnect,
//        onerror: onError,
//        onroamingmsgs: onRoamingMsgs,
//        onofflinemsgs: onOfflineMsgs,
//        onmsg: onMsg
//    });
//
//    function onConnect() {
//        console.log('连接成功');
//        sendText()
//    }
//    function onWillReconnect(obj) {
//        // 此时说明 SDK 已经断开连接, 请开发者在界面上提示用户连接已断开, 而且正在重新建立连接
//        console.log('即将重连');
//        console.log(obj.retryCount);
//        console.log(obj.duration);
//    }
//    function onDisconnect(error) {
//        // 此时说明 SDK 处于断开状态, 开发者此时应该根据错误码提示相应的错误信息, 并且跳转到登录页面
//        console.log('丢失连接');
//        console.log(error);
//        if (error) {
//            switch (error.code) {
//                // 账号或者密码错误, 请跳转到登录页面并提示错误
//                case 302:
//                    break;
//                // 重复登录, 已经在其它端登录了, 请跳转到登录页面并提示错误
//                case 417:
//                    break;
//                // 被踢, 请提示错误后跳转到登录页面
//                case 'kicked':
//                    break;
//                default:
//                    break;
//            }
//        }
//    }
//    function onError(error) {
//        console.log(error);
//    }
//    function onRoamingMsgs(obj) {
//        console.log('收到漫游消息', obj);
//        pushMsg(obj.msgs);
//    }
//    function onOfflineMsgs(obj) {
//        console.log('收到离线消息', obj);
//        pushMsg(obj.msgs);
//    }
//    function getUserDone(error, user) {
//        console.log('获取用户名片' + (!error ? '成功' : '失败'), error, user);
//        if (!error && user) {
//            console.log(user);
//        }
//    }
//    function onMsg(msg) {
//        nim.getUser({
//            account: '50038',
//            sync: true,
//            done: getUserDone
//        });
//
//        console.log('收到消息', msg.scene, msg.type, msg);
//        if (msg.flow == 'in' && msg.target == uid && (msg.type == 'image' || msg.type == 'text' || msg.type == 'video' || msg.type == 'audio')) {
//            switch (msg.type) {
//
//            }
//
//        }
//    }
//
////    switch (msg.type) {
////        case 'custom':
////            onCustomMsg(msg);
////            break;
////        case 'notification':
////            // 处理群通知消息
////            onTeamNotificationMsg(msg);
////            break;
////        default:
////            break;
////    }
//    function sendText(){
//        var msg = nim.sendText({
//            scene: 'p2p',
//            to: '40000',
//            text: 'good boy',
//            done: sendMsgDone
//        });
//        console.log('正在发送p2p text消息, id=' + msg.idClient);
//        pushMsg(msg);
//        function sendMsgDone(error, msg) {
//            console.log(error);
//            console.log(msg);
//            console.log('发送' + msg.scene + ' ' + msg.type + '消息' + (!error?'成功':'失败') + ', id=' + msg.idClient);
//            pushMsg(msg);
//        }
//    }
//    function pushMsg(msgs) {
//        if (!Array.isArray(msgs)) {
//            msgs = [msgs];
//        }
//        var sessionId = msgs[0].sessionId;
//        data.msgs = data.msgs || {};
//        data.msgs[sessionId] = nim.mergeMsgs(data.msgs[sessionId], msgs);
//    }
//    function onCustomMsg(msg) {
//        // 处理自定义消息
//    }
</script>
