<style>
    table tr td{
        vertical-align: middle !important;
    }
</style>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th class="center">ID</th>
        <th class="center">类型</th>
        <th class="center">标题</th>
        <th class="center">定时时间</th>
        <th class="center">状态</th>
        <th class="center">操作</th>
    </tr>
    </thead>

    <tbody>
    <?php if($list) {?>
        <?php foreach ($list as $item) {
                $meta_data = json_decode($item['data'],true);
            ?>
            <tr data-id="{{item['id']}}">
                <td class="center">{{item['id']}}</td>
                <td class="center">
                    <?php
                        $msg_type = [ 1 => '链接','图文（单）','图文（多）'];
                        $badge_color = [1=>'','badge-purple','badge-info'];
                    ?>
                    <span class="badge <?php echo $badge_color[$meta_data['msg_type']] ?>"><?php echo $msg_type[$meta_data['msg_type']]; ?></span>
                </td>
                <td >
                    <?php if($meta_data['msg_type'] == 1) {?>
                        <i class="fa fa-link blue" aria-hidden="true"></i>
                       {{meta_data['content']}}
                    <?php }elseif( $meta_data['msg_type'] == 2) {?>
                    <div class="msg_container" style="width:250px;">
                        <div class="msg_first" style="padding:5px;position:relative;width:100%;height:100px;border:1px solid #ccc;border-collapse: collapse;background-image: url(<?php echo $meta_data['thumb']?>?x-oss-process=image/resize,m_fill,h_100,w_250);">
                            <div style="position:absolute;bottom:0;">
                                <a target="_blank" href="<?php echo $meta_data['link'] ?>" style="color:#fff;">
                                    <?php echo mb_substr($meta_data['title'],0,25)?>
                                </a><br>

                            </div>
                        </div>
                    </div>

                    <?php }elseif( $meta_data['msg_type'] == 3){?>
                        <div class="msg_container" style="width:250px;">
                        <div class="msg_first" style="padding:5px;position:relative;width:100%;height:100px;border:1px solid #ccc;border-collapse: collapse;background-image: url(<?php echo explode('?',$meta_data['media_data'][0]['thumb'])[0]?>?x-oss-process=image/resize,m_fill,h_100,w_250);">
                            <div style="position:absolute;bottom:0;color:#fff;">
                                <a target="_blank" href="<?php echo $meta_data['media_data'][0]['link'] ?>" style="color:#fff;">
                                    <?php echo mb_substr($meta_data['media_data'][0]['title'],0,25)?>
                                </a><br>
                            </div>
                        </div>
                            <?php foreach ($meta_data['media_data'] as $k => $v){
                                if ($k === 0) continue;
                                    ?>

                                        <div class="msg_item" style="padding:5px;height:60px;width:100%;border:1px solid #ccc;border-top:0;border-collapse: collapse">
                                            <div style="float:left;width:185px;padding-top: 5px;">
                                                <a target="_blank" href="<?php echo $v['link'] ?>">
                                                    <?php echo mb_substr($v['title'],0,25)?>
                                                </a><br>
                                            </div>
                                            <div style="float:right;width:45px;height:45px;background-image: url(<?php echo explode('?',$v['thumb'])[0]?>?x-oss-process=image/resize,m_fill,h_45,w_45);">

                                            </div>

                                        </div>



                            <?php } ?>
                        </div>
                    <?php } ?>
                </td>
                <td class="hidden-xs">
                    <?php echo date('Y/m/d H:i',$item['timing']) ?>
                </td>
                <td class="hidden-480">
                    <?php
                        $status = [1 => '等待推送','推送成功','推送失败'];
                        $status_color = [1 => 'label-warning','label-success','label-danger'];
                    ?>
                    <span class="label label-xlg <?php echo $status_color[$item['status']] ?> arrowed-in arrowed-right"><?php echo $status[$item['status']]; ?></span>

                </td>
                <td>
                    <?php if( $item['status'] == 1 ) {?>
                        <a href="javascript:;" class="btn btn-xs btn-danger cancelBtn">取消推送</a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    <?php }else{ ?>
        <tr>
            <td colspan="6" class="red center" style="">暂无数据</td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php \Util\Pagination::instance($this->view)->display($this->view) ?>

<script>
    seajs.use('app/panel/panel.base',function (api) {
        $('.cancelBtn').on('click',function () {
            var _this = this;
            var id = $(_this).closest('tr').data('id');
            $(_this).confirm("确认取消推送?", {
                ok: function () {
                    api.requestApi('/api/message/cancelTiming',{id:id},function (res) {
                        if( res.result === 1 )
                        {
                            $(_this).closest('tr').remove();
                            tip.showTip('ok','操作成功',1000);
                        }
                    });
                },
                cancel: function () {
                    return false;
                }
            });
        });
    });

</script>
