<link rel="stylesheet" href="/srv/static/panel/css/plugins/jquery/jquery.datetimepicker.css">
<script src="/srv/static/panel/js/jquery/jquery.datetimepicker.js"></script>
<script src="/srv/static/panel/js/tools/Url.js"></script>
<div style="">
    <label for="uid" style="margin-left:10px">用户ID:</label>
    <input type="text" id="uid" placeholder="请输入用户ID" value="<?php echo $this->request->get('uid')?>">
    <label for="" style="margin-left:10px">活动发起时间:</label>
    <input type="text" id="launch_start" placeholder="请选择" value="<?php echo $this->request->get('launch_start');?>"> -
    <input type="text" id="launch_end" placeholder="请选择" value="<?php echo $this->request->get('launch_end');?>">
    <label for="" style="margin-left:10px">活动开始时间:</label>
    <input type="text" id="play_start" placeholder="请选择" value="<?php echo $this->request->get('play_start');?>"> -
    <input type="text" id="play_end" placeholder="请选择" value="<?php echo $this->request->get('play_end');?>">
    <a href="javascript:;" class="btn btn-xs btn-primary" id="search">搜索</a>
    <a href="javascript:;" class="btn btn-xs btn-primary" id="reset">重置</a>


</div>

<hr class="hr-10">
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th class="center" style="width:120px">#</th>
        <th class="center" style="width:120px">用户</th>
        <th class="center" style="width:200px">
            活动类型
            <select  id="type">
                <option value=-1 <?php echo $type ? 'selected' :'' ?>>全部</option>
                <option value=0 <?php echo $type == 0 ? 'selected' :'' ?>>红包雨</option>
                <option value=1 <?php echo $type == 1 ? 'selected' :'' ?>>知识问答</option>
            </select>

        </th>
        <th class="center"  style="width:150px">
            奖金
        </th>
        <th class="center" style="width:150px">
            奖励份数
        </th>
        <th class="center" style="width:280px">
            位置
        </th>
        <th class="center" style="width:150px" >
            可见范围
        </th>
        <th class="center">
            发起时间
        </th>
        <th class="center">
            开始时间
        </th>
        <!--<th class="center">
            置顶活动
        </th>-->
        <!--<th class="center">充值/消费：
            <select  id="type">
                <option value=-1 <?php /*echo $type ? 'selected' :'' */?>>全部</option>
                <option value=0 <?php /*echo $type == 0 ? 'selected' :'' */?>>充值</option>
                <option value=1 <?php /*echo $type == 1 ? 'selected' :'' */?>>消费</option>
            </select>
        </th>
        <th class="center">交易描述</th>
        <th class="center">交易后龙钻个数</th>
        <th class="center <?php /*if(strpos($sort,'created') !== false) echo 'blue'*/?>" id="sort-created" style="cursor: pointer;user-select: none" >交易时间
            &nbsp;
            <i class="fa fa-sort <?php /*if( $sort == 'created desc' ) echo "fa-sort-down blue";elseif($sort == 'created') echo 'fa-sort-up blue'*/?>" data-order="created">

            </i>
        </th>-->

    </tr>
    </thead>
    <tbody>
    <?php if($list) {?>
        <?php foreach($list as $item) : ?>
            <tr>
                <td class="center">{{item['id']}}</td>
                <td style="text-align: left">
                    <a href="javascript:;" data-href="/panel/users/detail/?user_id={{item['uid']}}" data-title="用户详情" class="newTarget">{{item['uid']}}</a>

                </td>
                <td class="center">
                    <?php if( $item['type'] == 0 ) {?>
                        红包雨
                    <?php }elseif( $item['type'] == 1) {?>
                        知识问答
                    <?php } ?>
                </td>
                <td class="center">
                    <span class="green" style="font-weight:bold">{{item['reward'] / 100}}</span>
                    <span class="grey right">元</span>
                </td>
                <td class="center">
                   <span class="blue" style="font-weight:bold">{{item['copy_num']}}</span>
                    <span class="grey right">份</span>
                </td>
                <td class="center">
                    <?php /*echo $location[$item['id']]; */?>
                    <span  class="coordinate" style="color:#4aa4ce" data-lng="{{item['lng']}}" data-lat="{{item['lat']}}" >......</span>
                </td>
                <td class="center">
                   <span class="red" style="font-weight:bold">{{item['allow_range']}}</span>
                    <span class="grey right">米</span>
                </td>
                <td class="center">
                    <span class="" ><?php echo date('Y/m/d H:i:s',$item['created']) ?></span>
                </td>
                <td class="center">
                    <span class="" ><?php echo date('Y/m/d H:i:s',$item['start_time']) ?></span>
                </td>
                <!--<td class="center">
                    <?php /*if( $item['top'] == 1 ) {*/?>
                        是
                    <?php /*}else{*/?>
                    否
                    <?php /*} */?>
                </td>-->



            </tr>
        <?php endforeach; ?>
    <?php }else{ ?>
        <tr>
            <td colspan="10" class="center"><span class="red" style="font-weight:bold">暂无数据</span></td>
        </tr>
    <?php } ?>

    </tbody>
</table>
<?php \Util\Pagination::instance($this->view)->display($this->view) ?>

<script>
    $('#launch_start,#launch_end,#play_start,#play_end').datetimepicker({
        lang: "ch",
        step: 5,
        format: "Y/m/d",
        allowBlank: true,
        maxDate:0,
        timepicker: false
    });
    //搜索
    $('#search').on('click',function () {
        var uid = $('#uid').val();
        var launch_start = $('#launch_start').val();
        var launch_end = $('#launch_end').val();
        var play_start = $('#play_start').val();
        var play_end = $('#play_end').val();
        var url = new Url();
        url.rmArgs(['p']);
        url.setArgs({uid:uid,launch_start:launch_start,launch_end:launch_end,play_start:play_start,play_end:play_end});
        location.href = url.getUrl();
    });
    //重置
    $('#reset').on('click',function () {
        location.href = location.pathname;
    });
    $('.showInfo').on('click',function () {
        $(this).confirm()
    })
    //活动类型
    $('#type').on('change',function () {
        var type = $(this).val();
        var url = new Url();
        url.rmArgs(['p']);
        url.setArgs({type:type});
        location.href = url.getUrl();
    });

    seajs.use('app/panel/panel.base',function (api) {
        $('.coordinate').each(function () {
            var _this = this;
           var lng = $(this).attr('data-lng');
           var lat = $(this).attr('data-lat');
           api.requestApi('/api/activity/coordinate',{lng:lng,lat:lat},function (res) {
               var data = res.data;
                $(_this).text(data.province + '/' + data.city + '/' + data.district);
           },true,true)
        });
    });
</script>
