<link rel="stylesheet" href="/srv/static/panel/css/sweetalert.css">
<script type="text/javascript" src="/srv/static/panel/js/sweetalert/sweetalert.min.js"></script>
<style>
    .fa-times-circle-o:before {
        content: "\f05c";
        color:rgba(119, 119, 119, 0.88);
    }
</style>
<div class="width-60">
    <div class="widget-box">
        <div class="widget-header">
            <h4>红包雨活动配置：</h4>
        </div>

        <div class="widget-body">
            <div class="widget-main no-padding">
                <form id="config" action="">
                    <!-- <legend>Form</legend> -->
                    <fieldset>
                        <table class="table table-striped table-bordered" style="border:1px solid #eee">
                            <thead>
                            <tr>
                                <th width="17%" class="center">参数</th>
                                <th width="22%" class="center"">值</th>
                                <th  class="center"">说明</th>
                            </tr>
                            </thead>
                            <tbody>




                            <tr>
                                <td>倒计时：</td>

                                <td class="center">
                                    <input type="text" name="count_down"  value="<?php echo $config['count_down']?>" size="5" style="height:20px;padding:0 5px 0"><span style="color:red">秒</span>
                                </td>
                                <td>活动开始倒计时时间</td>
                            </tr>
                            <tr>
                                <td>单回合红包数：</td>

                                <td class="center">
                                    <input type="text" name="redbag_num"  value="<?php echo $config['redbag_num']?>" size="5" style="height:20px;padding:0 5px 0"><span style="color:red">个</span>
                                </td>
                                <td>单回合红包数</td>
                            </tr>

                            <tr>
                                <td>单回合持续时间：</td>

                                <td class="center">
                                    <input type="text" name="interval"  value="<?php echo $config['interval']?>" size="5" style="height:20px;padding:0 5px 0"><span style="color:red">秒</span>
                                </td>
                                <td>单回合持续时间</td>
                            </tr>

                            <tr>
                                <td>提交数据持续时间：</td>

                                <td class="center">
                                    <input type="text" name="commit"  value="<?php echo $config['commit']?>" size="5" style="height:20px;padding:0 5px 0"><span style="color:red">秒</span>
                                </td>
                                <td>提交数据持续时间</td>
                            </tr>
                            <tr>
                                <td>中场休息时长：</td>

                                <td class="center">
                                    <input type="text" name="idle"  value="<?php echo $config['idle']?>" size="5" style="height:20px;padding:0 5px 0"><span style="color:red">秒</span>
                                </td>
                                <td>中场休息时长</td>
                            </tr>

                            </tbody>
                        </table>
                    </fieldset>

                    <div class="form-actions center">
                        <button type="button" class="btn btn-sm btn-success" id="save">
                            保存
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>







<script>
    seajs.use("app/panel/panel.base.js",function (api) {

        $('#save').on('click',function(){
            //非空验证
            $('input').each(function (i) {
                if( $(this).val() === '' )
                {
                    tip.showTip('err','值不能为空',2000);
                    return false;
                }
            });
            api.requestApi('/panel/activity/redBagRain',$('#config').serialize(),function (res) {
                if(res.result == 1)
                {
                    tip.showTip('ok','保存成功',1500);
                    setTimeout(function () {
                        window.location.reload()
                    },1500)
                }
            });
        });

    });

</script>
