<div class="page-header">
    <h1>资料设置</h1>
</div>

{{ content() }}

{{ form('panel/setting/index', 'id': 'registerForm', 'class': 'form-horizontal', 'onbeforesubmit': 'return false', 'data-toggle':"validator", 'role':'form') }}
<fieldset class="col-sm-5">
    <!--  <legend>账号信息</legend>-->
    <div class="form-group">
        <label class="col-sm-2 control-label">登陆账号</label>

        <div class="col-sm-10">
            <p class="form-control-static"><?php echo $admin['account']; ?></p>
        </div>
    </div>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">用户姓名</label>

        <div class="col-sm-10">
    <span class="col-sm-6">
        <input type="text" class="form-control" id="name" name="name" placeholder="用户姓名"
               value="<?php echo $admin['name'] ?>"
               required data-error="用户姓名">
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <style>
        .bind_avatar_list li {
            overflow: hidden;
            height: auto;
            padding: 5px;
            background-color: #e4e4e4;
            border-radius: 5px;
            margin-bottom: 5px;
            cursor: pointer;
            width: 250px;
        }

        .bind_avatar_list ul {
            margin-left: 10px;
        }

        .bind_avatar_list .user_item img {
            width: 52px;
            height: 52px;
            border-radius: 100%
        }

        .bind_avatar_list .user_item:hover {
            background-color: #438eb9;
        }

        .bind_avatar_list .user_item:hover, .avatar_list li:hover .user_id {
            color: #fff;
        }

        .bind_avatar_list .user_item:hover .remove_wrap {
            display: block;
        }

        .bind_avatar_list li .user_info {
            float: left;
            margin-left: 10px;
        }

        .bind_avatar_list li .user_info .username {
            font-weight: bold;
        }

        .bind_avatar_list li .user_info .user_id {
            font-size: 12px;
            font-weight: bold;
        }

        .bind_avatar_list li p {
            line-height: 26px;
            vertical-align: middle;
            height: 26px;
        }

        .bind_avatar_list li img {
            float: left;
        }

        .bind_avatar_list .remove_wrap {
            float: right;
            width: 50px;
            height: 52px;
            line-height: 52px;
            color: #438eb9;
            text-align: center;
            vertical-align: middle;
            background-color: #fff;
            display: none;
            border-radius: 5px;
            font-weight: bold;
        }

        .bind_avatar_list .remove_wrap:hover {
            background-color: palevioletred;
            color: white;
        }
        .user_left {
            float: left;
            width: 48%;
            height: 450px;
        }

        .user_left .tip {
            color: red;
        }

        .user_middle {
            float: left;
            width: 10%;
            border-right: 1px solid #e4e4e4;
            border-left: 1px solid #e4e4e4;
            height: 450px;
            position: relative;

        }

        .user_middle span {
            font-size: 30px;
            font-weight: bold;
            display: block;
            position: absolute;
            top: 50%;
            left: 50%;
            margin-top: -10px;
            margin-left: -15px;
            border: 1px solid #d4d4d4;
            background-color: #e4e4e4;
            padding: 3px 10px;
            cursor: pointer;
        }

        .user_middle span:hover {
            background-color: #2a8a00;
            color: #fff;;
        }

        .userList img {
            border-radius: 100%;
            width: 20px;
            height: 20px;
        }

        .userList li {
            list-style-type: none;
            border-bottom: 1px dotted #e4e4e4;
            line-height: 30px;
            padding-right: 5px;
        }

        .user_right {
            float: right;
            width: 40%;
            height: 450px;
            overflow-y: auto;
        }

        .user_right .selectedUser li {
            line-height: 25px;
            border-bottom: 1px dotted #e4e4e4;
            padding-left: 20px;;
        }

        .user_right .selectedUser li img {
            width: 20px;
            height: 20px;
            border-radius: 100%;
        }

        .user_right .selectedUser li .remove {
            display: none;
            float: right;
            color: red;
            font-size: 20px;;
            margin-right: 20px;;
            line-height: 25px;;
            cursor: pointer;
        }

        .user_right .selectedUser li:hover {
            background-color: #e4e4e4;
        }

        .user_right .selectedUser li:hover .remove {
            display: inline-block;
        }

        .pageBar {
            margin-top: 5px;;
        }

        .pageBar a {
            display: inline-block;
            margin: 3px;
            border: 1px solid #e4e4e4;
            padding: 2px 6px;
        }

        .pageBar .curr {
            background-color: #2a8a00;
            color: #fff;;
        }


        .user_avatar_list img {
            display: inline-block;
            width: 30px;
            height: 30px;;
            border-radius: 100%;
            margin-left: 2px;
        }
    </style>
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">App关联账号:</label>

        <div class="col-sm-10">
            <div class="bind_avatar_list">
                <ul>
                    <?php if (!empty($users)) { ?>
                        <?php foreach ($users as $item) { ?>
                            <li class="user_item">
                                <img
                                    src="<?php echo $item['avatar'] ?>?x-oss-process=image/resize,m_fill,h_160,w_160">
                                <div class="user_info">
                                    <p class="username"><?php echo $item['username'] ?></p>
                                    <p class="user_id"><?php echo $item['id'] ?></p>
                                </div>
                                <div class="remove_wrap removeBtn" data-id="<?php echo $item['id'] ?>"
                                     style="">
                                    取消
                                </div>
                                <div class="remove_wrap editBtn" style="margin-right:5px;" data-id="<?php echo $item['id'] ?>" data-sex="{{item['sex']}}" data-birth="{{item['birthday']}}">
                                    编辑
                                </div>
                            </li>
                        <?php } ?>
                    <?php } ?>


                </ul>
            </div>

    <span class="col-sm-10">
        <input type="text" class="form-control" id="app_uid" name="app_uid" placeholder="一个账号只能被一个管理员绑定"
               value="" style="float: left;width: 60%"
               data-error="App账号">
        <span class="btn btn-success btn-sm selectUser" style="float: left;margin-left: 2px;border: 2px solid #87b87f;"><i
                class="fa fa-android"></i> 选择机器人</span>
                 <span class="btn btn-primary btnAdd" style="margin-top: 10px"><i class="fa fa-plus"></i> 添加账号</span>
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="contact" class="col-sm-2 control-label">角色权限</label>

        <div class="col-sm-10">
            <p class="form-control-static">
                <?php
                echo $admin['group_name'];
                ?>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label"></label>
    <span style="margin: 0 0 0 24px;">
    {{ submit_button('保存', 'class': 'btn btn-primary btn-sm') }}
    </span>
    </div>
</fieldset>

{{end_form()}}

<div class="modal fade" id="sendModal">
    <div class="modal-dialog" style="width: 800px;">
        <div class="modal-content" style="border-radius:5px">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">机器人用户列表</h4>
            </div>
            <div class="modal-body" style="overflow:hidden;">
                <div class="user_left">
                    <div class="field set-field diy-data" id="topic_type_box">
                        <div><input type="text" placeholder="ID/昵称/手机号" class="search"/> <span
                                class="btn btn-sm btn-primary btnSearch">搜索</span></div>
                        <label class="field-label" style="text-align: left">
                            <input type="checkbox"  name="checkAll" class="checkAll chk ace" id="checkAll"/>
                            <span class="lbl"></span>
                            选中
                        </label>
                        <section class="form-group userList">

                        </section>

                    </div>
                </div>
                <div class="user_middle">
                    <span class="fa fa-angle-double-right moveBtn"></span>
                </div>
                <div class="user_right">
                    <ul class="selectedUser"></ul>
                </div>
            </div>
            <div class="modal-footer" style="border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="updateSureBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--编辑绑定的恐龙谷账号信息-->
<div class="modal fade" id="editUser">
    <div class="modal-dialog" style="width: 600px;">
        <div class="modal-content" style="border-radius:5px">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">机器人用户列表</h4>
            </div>
            <div class="modal-body" >
                <form class="form-horizontal" role="form">
                    <input type="hidden" name="uid" value="">

                    <div class="form-group"><!--头像-->
                        <div class="" style="margin-left:40%;width:90px;height:90px;overflow:hidden;border:2px solid #ccc;border-radius:50%" id="selectAvator" >
                            <img src="/static/panel/images/avatar.png" alt="" id="pick-avatar" style="height:90px;cursor: pointer;" >
                            <input type="hidden" name="avatar" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 昵称 </label>

                        <div class="col-sm-8 ">
                            <input type="text" name="username"  placeholder="" class="col-xs-10 col-sm-5">
                            <span class="help-inline col-xs-12 col-sm-7 red hide">
                                <span class="middle">昵称4-16位字符</span>
                            </span>
                        </div>
                    </div>

                    <div class="space-4"></div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label no-padding-right" for="form-field-2"> 性别 </label>

                        <div class="col-sm-8">
                            <label>
                                <input name="sex"  type="radio" class="ace" value=0>
                                <span class="lbl"> 保密</span>
                            </label>
                            <label>
                                <input name="sex"  type="radio" class="ace" value=1>
                                <span class="lbl"> 男</span>
                            </label>
                            <label>
                                <input name="sex" type="radio" class="ace" value=2 >
                                <span class="lbl"> 女</span>
                            </label>
                        </div>
                    </div>

                    <div class="space-4"></div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label no-padding-right" for="form-input-readonly"> 生日 </label>

                        <div class="col-sm-8">
                            <input  name="birth" value="1995-01-01" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer" style="border-bottom-left-radius: 5px;border-bottom-right-radius: 5px;">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="saveBtn">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    seajs.use('app/panel/panel.setting.js?v=1.6', function (setting) {
        setting.bindUser()
    })
</script>