<div class="page-header">
    <h1>安全密码</h1>
</div>

{{ content() }}
{{ form('panel/setting/SecurityPassword', 'id': 'registerForm', 'class': 'form-horizontal', 'onbeforesubmit':"return false", 'data-toggle':"validator", 'role':'form') }}
<fieldset>
    <div class="form-group ">
        <label for="original" class="col-sm-2 control-label">原始密码</label>

        <div class="col-sm-10">
	    <span class="col-sm-5">
            {{ password_field('original', 'class':"form-control", 'required', 'data-error':"原始密码必须填写" ,'placeholder':"初次设置时不用填写") }}
        </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">新密码</label>

        <div class="col-sm-10">
    <span class="col-sm-5">
        {{ password_field('password', 'class':"form-control", 'required', 'data-error':"请填写新密码") }}
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="repeatPassword" class="col-sm-2 control-label">确认密码</label>

        <div class="col-sm-10">
    <span class="col-sm-5">
        {{ password_field('repeatPassword', 'class':"form-control", 'required', 'data-error':"请填写新密码") }}
    </span>
            <span class="help-block with-errors"></span>
        </div>
    </div>
</fieldset>

<div class="form-group">
    <label for="repeatPassword" class="col-sm-2 control-label"></label>

    <span style="margin:0 0 0 24px">{{ submit_button('保存', 'class': 'btn btn-primary btn-large') }}</span>
</div>
{{end_form()}}